### ISSUE TITLE
Unclear listing of "exclusive" points

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#101]
Some score sheets list points that might be hard to understand as "exclusive" points.
For example the GPSR lists points for 1st 2nd and 3rd attempt.
If you think about it it is pretty clear that you can only get either of those points but it should not only be clear due to context but as well by the listing/formatting of the score sheet.

**Comment by LoyVanBeek** [comment]
Do you mean that you can only get points for **one** category within each attempt, and that categories are mutually exclusive?

**Comment by semeyerz** [comment]
Initially i meant the three attepts in the Getting instructions section.
But you just found another example where it might not be clear that you can get those points only ONE time so that it is exclusive for each of the tries.

But there are some more examples in the score sheets where you have to find out that there have to be exclusive points in there by adding up all the points and seeing that they exceed that stated total score.

This is why i would like to have an indicator that makes clear which points belong to a group of points from which the points are given only one time.

**Comment by kyordhel** [comment]
Sorry if it is not clear enough, I build that Scoresheet during the German Open.

I believe that is clear enough that, if you score on 3rd attempt is because you couldn't score on 1st and 2nd. Plus, the rulebook says Team Leader chooses ONE category for the command to be generated, so you will be scored for that category only.

Scoresheets are for the TC/EC who (at least in *theory*) know and understand the rulebook, and are for scoring teams, not for explaining the rules. 

Moreover, the GPSR is being redesigned so that scoresheet will change.

**Comment by LoyVanBeek** [comment]
Note on the redesign: see pull #91
