### ISSUE TITLE
Score Sheet for Navigation Test remarks

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#104]
I know that score sheets are for the TCs but one of my students found these small mistakes:

- Under the Waypoint 3 heading it is noted that there are points for reentereing the arena after reaching Waypoint 4. Maybe that should belong to the waypoint 4 heading?

- Waypoint 3 heading exists twice.

**Comment by kyordhel** [comment]
Thanks!
No problem. Actually we really appreciate such colaboration from part of your students (it seems they are more involved in the league than most of team leaders). It helps us to have a better rulebook.

- It is stated under Waypoint 3 because the robot should:
  - Reach Waypoint 3
  - Follow the human to Waypoint 4
  - Navigate back to Waypoint 3

It is a loop, and the scoring is time-linear but grouped by waypoints. Remember we may decide to swap Waypoints regarding arena configuration. However I need to check that on the rulebook: ScoreSheets and Ruleboo must have same info.

- Waipoint 3 heading existing twice. Indeed this is an error. Since I made the scoresheets it is my fault (and it #$%€@@@!!! me off make mistakes).
