### ISSUE TITLE
Possible negative points when making an effort

### ISSUE THREAD

**Issue by rokusottervanger** [RoboCupAtHome/RuleBook#107]
In the wake me up, it is possible that one makes the effort of getting cereal and pouring it into the bowl. However, if the wrong cereal is selected and (a lot of) cereal is spilled while pouring it into the bowl, this results in negative points. I don't know if you meant it to be like that, but it seems unreasonable to me...

**Comment by kyordhel** [comment]
Nope, it is not possible to Score negative for those actions. 

If your robot grasps the cereal, it gets points for grasping the cereal (minus the penalty if is the wrong cereal). If your robot pours the cereal, it gets points for pouring the cereal (minus the penalty for spilling cereal out of the bowl). 

Therefore, in the end you score points , a few but there are points. We are not going to make you loose points for trying to do something. This is in order to push teams to solve the task. 

The exception is when, for instance, you pour the cereal out of the bowl (and obviously you are not trying to pour inside of it), or if you grasp a banana instead of a cereal and try to pour the banana content. Then you get zero points for that task.
