### ISSUE TITLE
RoboNurse Point Bonuses

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#108]
commit bd7b changed the rulebook to only have unknown objects.
Though the scoresheet says there are still 30 bonus points for that.

**Comment by kyordhel** [comment]
@semeyerz Can't find the commit you are referencing to, but the issue is present on the last one. Thanks for the report.

@LoyVanBeek @balkce we need to fix this ASAP.

My proposal is to leave the scoring as is and remove *Describe unknown pills' bottles*. We may also split those 30pts as follows:

- Real time description (given upon arrival) 70pts
- Description given within 5 seconds 40pts
- Description given with t \in [5, 15)sec 20pts
- Description given with t \in [15, 30)sec 10pts
- Description given with t > 30sec 0pts

**Comment by balkce** [comment]
Made the modification proposed by @kyordhel .
