### ISSUE TITLE
Custom container not mentioned in scoresheets

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#109]
The rulebook states that teams can use a custom container (e.g. tray). Using it may give a penalty, but what this penalty is, is never stated.

I propose to halve the points for when you use a custom container instead of the one supplied by the TC. 

@kyordhel @dragonjack @balkce What do you think?

**Comment by kyordhel** [comment]
@LoyVanBeek The original idea was to halve the points, however consider the following cases:

- a normal, unmodified tray with bright color
- an unmodified tray with colored handles
- an adapted tray with special handles designed for the robot
- an adapted tray with electronic devices for localization

I wouldn't allow the fourth (electronic) tray because I feel is not on the spirit on the competition and cannot be put into a dishwasher. 

On the other three, it's clear that the first is more challenging than the second one, and the second is more challenging than the third one. Still is hard to grasp a tray but I can see a BIG difference between trying to grasp a real-world object than an adapted one.

Therefore, the rule was kept open and the penalty can be decided after the robot inspection (the tray should be presented for inspection).

Waiting to read your opinions,
Mauricio

**Comment by balkce** [comment]
Agree.
C

**Comment by LoyVanBeek** [comment]
Electronics and artifical markers are forbidden, so that is not an issue.
Our goal with the trays was to **encourage bi-hand manipulation**. That is *not* explicitly in the rulebook, so one-hand manipulation is also allowed of course but that is difficult in a different regard because of the weight. 
Trays are means to be manipulation by 2 human hands. 

I propose:
- Special color on an otherwise unmodified tray, to be used with 2 hands: 75%  of the points
- Special color on a modified tray, to be used with 2 hands: 50%  of the points
- A tray modified to be used with 1 hand: 25%  of the points

**Comment by kyordhel** [comment]
About electronics, you are completely right (however, if team ToBI uses its smart-minibots to assembly a smart tray which can move like if carried by ants... I would consider that...), but for artificial markers I would think about QR Codes and OpenCV Marks. If a team provides a tray with a right *blinding fucsia* handle, a left *eye-burning cyan* handle, and a *pikachu-yellow* bottom... well, definitely is not the tray I would buy at the supermarket but can be found in a kindergarden or a center for treatment of epilepsia.

Other than that, I completely agree on what you propose (50% for specially colored handles).

P.S. Thanks for your detailed explanation @balkce

**Comment by balkce** [comment]
That's what I'm here for.
