### ISSUE TITLE
Poster Teaser Session

### ISSUE THREAD

**Issue by LoreChile** [RoboCupAtHome/RuleBook#111]
Hello, 
I would like to know what size the poster should be for the Poster Teaser Session. It should be A0 or A1 (as in the symposium)?
Thank you!

**Comment by dragonjack** [comment]
There is no constraint on the poster size, but if you ask I will suggest A0
because you would have more space.

Hope it helps.

On Fri, Jul 10, 2015 at 11:33 PM, María Loreto Sánchez <
notifications@github.com> wrote:

> Hello,
> I would like to know what size the poster should be for the Poster Teaser
> Session. It should be A0 or A1 (as in the symposium)?
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboCupAtHome/RuleBook/issues/111>.
>



-- 
Regards

Multi-Agent System Lab
University of Science and Technology of China

K.Chen

**Comment by LoreChile** [comment]
Thank you very much!
