### ISSUE TITLE
Allow cloud computing

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#128]
Cloud computing and deep learning can be very beneficial to robotics. Many current applications of AI (**deep learning**, **shared knowledge bases**) rely on large scale computing which cannot be done on a robot but only on huge datacenters.

To tap into this for RoboCup, the must allow the robots to access the internet so they can use such services.

A reliable internet connection has been difficult at RoboCup, but its 2015, this should be possible. It may even be possible to equip a robot with a 4G SIM-card to be independent of WiFi. 

A potential issue is that the internet connection will be used for teleoperating the robots. If we control the internet connection, we can deliberately add some delay/lag so teleoperation becomes difficult. This does not make teleoperation impossible of course. We can also restrict the IP-addresses the robots can access. And also trust the teams.

**Comment by kyordhel** [comment]
I completely disagree with this. I see no problem having a robot using its own hardware to interact at machine-level with the house/office, which is completely different of relying in external computing power. In my opinion, robots must be self-contained.

Moreover, teams with access to cloud computing may have a HUGE advantage over teams which don't. I foresee an scenario when running a downloaded version of SIFT over thousands of models outmacthes a home-made algorithm which is state of the art, just because the former has access to one hundred Xeons and the other runs in a single GPU.

Opinion from other TC members is very important. I wouldn't like to need asking Gaia for permission every time I'm microwaving popcorn.

**Comment by LoyVanBeek** [comment]
In the current situation, teams with access to better robots also have a huge advantage. Some teams may not have a very good robot hardware-wise but may have good computing facilities at their university back home. 

There is so much research going on that uses large scale computing, that a single robot cannot carry with it. 
Your smartphone is not fully self-contained; much of its functionality comes from the Internet.

**Comment by kyordhel** [comment]
Still, I don't think is a good idea. Too many setbacks, but I'm not the only TC. Robots are not smartphones, a smartphone is meant to be connected to function, a robot should be more independent (don't mess with my "smartphone", she is smarter than me and is mind-controlling me).

**Comment by balkce** [comment]
I can see both points:

On the one hand, what we want is to have a robot that is able to handle
difficult tasks, and we can't expect that a single computer (or even three,
in some cases) be able to analyze a whole 3D scene. At least not with our
current processing power, since there's too much information. It still
boggles me how we humans are able to do it. The Internet is there; it
doesn't make sense that our technology should be limited to whatever
artificial constraints we come up with.

On the other hand, what we want in the competition is to not open more
doors for cheating. It will be really difficult to know if the cloud
computing being accessed is not another team member in their lab back home
telling the robot what it is seeing and/or what to do.

Why not a compromise? Theme for a technical challenge: I would be really
interested in this, outside of the scope of a test.

Cheers,

Caleb

**Comment by balkce** [comment]
Besides we, humans, are supposed to be independent and we use the Internet
all the time to complement our abilities.

C

**Comment by kyordhel** [comment]
A Technical Challenge or Open Challenge sounds like a good idea to me. I would like to believe there will be no super-human processor doing the object/whatever recognition.

If we decide to allow cloud computing, then robots MUST continue operating regardless internet connection availability. We have seen too much of "it doesn't word because wifi is failing"

**Comment by balkce** [comment]
Yeah. But, like Loy says: it's 2015, damn it!

**Comment by LoyVanBeek** [comment]
We can ask the team to propose what they would use an internet connection for.
A separate, open challenge to show the applications for this can also work, and depending on the results, allow in in all challenges in 2017. 

As to the internet connection, if we have 4 TC member on site in 2016, 1 can spend the first ime on having an OK internet connection. Or better: have a dedicated RoboCup-venue IT dude on call.

**Comment by LoyVanBeek** [comment]
I had some correspondence about this with Komei, sparked by his rospeex service:

> - Choosing stand-alone software or cloud service is up to teams
> To promote high-level performance with less cost, TC/OC/EC allow teams to use cloud services.    The teams must obey the following conditions.
> 
> - Approval by TC
> If a team want to use a cloud service, the team must declare the purpose, service URL, and which test they are going to use. The declaration must be done N(=60?) days > before the competition. The list of the approved services are published K days before the competition. If a cloud service is not approved by TC, no team can use it.
> 
> - Requirements for cloud services
> The cloud service must be publicly available without any financial cost. The cloud service must be used for one of the following purposes: object classification, face > recognition, speech recognition/synthesis, natural language understanding, smart-home, cloud storage, ...
> (black list required?)
> 
> - Number of cloud services
> For avoiding too much load on TC/OC/EC, the number of the services which a team can declare is limited to M(=5?).
> 
> - No human-based cloud service
> The cloud services which involve human processing are prohibited, e.g., amazon mturk or remote control. If a team used such services, it will be considered as cheating.
> 
> - Use it at your own risk
> OCs guarantee neither network connection nor the availability of them. The team cannot complain about this policy even if the cloud service is found to be unavailable at > the venue. We warn that in past competitions the network connection status was very bad at the venue.
> 
> - Inspection and penalty
> To inspect that the service is used for non-cheating purpose, TCs can ask the team to submit the internet connection logs during tests. The team is responsible for > presenting the evidence by using e.g., wireshark logs. If the team cannot do it, the team is banned from the competition (see the fairplay policy section).
> 
> - Chair
> To instantiate the discussions and decisions, we provide a cloud service chairperson from tc members.

Some example services:
For example:
- [http://www.faceplusplus.com/](faceplusplus.com) for face recognition etc.
- [http://dbpedia.org/About](dbpedia​) provides knowledge​
- [https://developers.google.com/freebase/](google knowledge graph) also provides knowledge, as RDF triples/facts​
- [http://roboearth.org/](roboearth) to share knowledge between robot​s and computing power.
- [www.wit.ai](wit.ai) for speech recognition and NLP
- [http://robobrain.me/#/](robobrain)

**Comment by kyordhel** [comment]
Still not convinced about this, but assuming will be approved, I would change:

- Robots **MUST** have an alternate offline module/node
- The *N>60 days before the competition* with a *should be detailed in the TDP and show in qualification video sufficient performance*. This is to encourage planned solutions instead of last-minute fixes.
- Limit the cloud services to max 3
- No awards if team is not actively involved in developing the used cloud service (maybe your speech recognition was the best ever seen, but you didn't code it so the league will not recognize that scientific research as your own). 

Best!

**Comment by LoyVanBeek** [comment]
* Having an alternative is your own choice, if a bad internet connection renders your robot useless, thats your problem. 
* Building on someone else's research for your own benefit is what RoboCup and research in general is about. You still have to integrate it in your robot. Giving proper credit is crucial though.

**Comment by LoyVanBeek** [comment]
As decided in our meeting October 6th, external cloud services are allowed.

**Comment by LoyVanBeek** [comment]
Added a section on this:
https://github.com/RoboCupAtHome/RuleBook/blob/master/general_rules/ExternalComputing.tex
