### ISSUE TITLE
Standardize interfaces to promote knowledge and implementation transfer

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#129]
One goal of RoboCup@Home is to advance the state of the art. Standardizing interfaces so implementations can be swapped may enable teams to more easily try another team's implementation for something.
After each RoboCup, all implementation are open-sourced and teams can choose which they want to use and improve on. Rinse-repeat for next year. 

Of course, we as TC cannot define these interfaces for the teams to follow. The interfaces may also be changed and extended. We can ask teams for proposals. 

For example: 
- Object recognition is basically a function mapping images (2D but maybe also 3D) to labels (but maybe additional information?). 
- Speech recognition: audio in, text (but maybe with additional annotations) out.
- Path planning, ROS has an interface defined for this, but some teams may alter the interface
- etc...

**Comment by kyordhel** [comment]
I do believe this should come as team-team initiative, so TC should encourage cooperation among teams instead or proposing the use of interfaces. Also, since some teams use software which is right-protected (propietary or patent-protected) we cannot ask to open-source all. Plus, such a policy may discourage private-initiative participation (aka companies).

Whatever, I do believe OC may be requested for making mandatory the presence of (nicely documented) open-source software or hardware blueprints in order to achieve qualification. Along with this the presence of training data (3D object models, pointclouds, annotated audio files) can be made also mandatory or even awarded.

**Comment by LoyVanBeek** [comment]
I completely agree that we cannot push a standard on the teams and that standard should come from the teams themselves indeed. 
Further I expect that we will not be able to define a single interface at first, but that one of multiple may become a de-facto standard (like ROS itself could be considered now)

**Comment by kyordhel** [comment]
Related to #257

**Comment by johaq** [comment]
I think we can close this, right?
I think it's hard to design the rules in a way to force teams towards developing standards.
Maybe teams could host workshops with each other to develope some?
