### ISSUE TITLE
Indirect speech recognition should focus on sound source localization

### ISSUE THREAD

**Issue by reinzor** [RoboCupAtHome/RuleBook#143]
I think the goal of the indirect speech recognition challenge is sound source localization. The challenge should also focus on this then. IMO, the following procedure should take place:

- Person calls robot
- Robot drives or turn towards the person 
- Robot answers question (optional) 

The first two steps should be explicitly formulated.

**Comment by balkce** [comment]
Although I agree with you that Sound Source Localization (SSL) should be the focus in the 2nd part, the test is much more interesting if we give incentive to teams to do both (ASR and SSL) at the same time. However, if a team is not able to do good SSL, but has a VERY good microphone setup or a VERY good noise reduction system such that it is able to correctly understand a person even if that person is not in front of the robot, it would be unfair to not provide them points for that.

In any case, you should have a look at the last draft of the RuleBook, Section 5.5:

http://latex.aslushnikov.com/compile?git=git://github.com/RoboCupAtHome/RuleBook.git&target=Rulebook.tex

**Comment by reinzor** [comment]
I saw the latest draft. But I think SSL and ASR are two different things so
don't grade them together IMO. It is a little bit weird when you correctly
locate the source and you ask for a repetition, you get a penalty of 5 × -5
points. This is not really a motivator for teams to work on SSL.

-Rein

**Comment by balkce** [comment]
SSL and ASR may be two different things, but are parts of the same Robot Audition ideal: that the robot should be able to hear in the same manner that a human does. A human is able to localize and recognize at the same time, so, a complete Robot Audition system should be able to do that.

As for the points for the 2nd part of the test, if you are able to localize and recognize at the same time (meaning, NOT require a repetition of the question) you get 20 points per question. If you are able to localize but require a repetition (meaning, the robot localized and then recognized), you get 15 points. And if the robot is not able to localize and just able to recognize, you get 10 points (the same as in the 1st part).

Meaning, if you are able to localize, even if it isn't at the same time as recognizing, you're getting at least 50% more points in the 2nd part compared to if you were just only recognizing. And, if you're able to do both at the same time (not require a repetition), you're getting 100% more points. I'm not sure what more incentive would a team want.

**Comment by kyordhel** [comment]
RoboCup @Home focus interest in Robot-Human interaction, thus is straightforward to think about speech as it is the default interaction among human beings. All test are designed this way.

In consequence, it is much more important for the competition to encourage teams to have good Speech Recognition on their robots (hence, more points are scored for good ASR). On the other hand Sound Source Localization is desirable but is not evaluated in other tests and, even among humans, one can attend to short sentences while not looking at the speaker (i.e. not focusing attention on them), but often will look the speaker and ask to repeat  what has been told.

In previous years, robots were unable to perform a test because they got stuck fetching a command. This is discouraging for teams since they can't show other abilities. Based on the average performance of most robots, TC has decided to keep focus on ASR, and just suggesting to start working on SSL.

Finally, we don't mind if robots have good SSL or not (at least for now), but we **need robots be able to understand given commands**. Scoring is designed this way. Once we see most teams correctly recognizing all given commands at first attempt regardless the operator (me, as human, still have problems with it), we will make SSL mandatory, for instance, given the GPSR commands from another room.

**Comment by LoyVanBeek** [comment]
@balkce It may be handy to clear up that we want robots to do SSL and ASR at the same time.

**Comment by balkce** [comment]
If you think it's necessary, I can add a short sentence stating so in the introduction of the test.

**Comment by balkce** [comment]
Just to make sure, I've added more explanation to your change.
