### ISSUE TITLE
Scoresheet for GPSR unclear

### ISSUE THREAD

**Issue by svddries** [RoboCupAtHome/RuleBook#145]
"Performing the first task correctly" (and other similar sentences): the word "task" is unclear. To me, it sounds like the whole task which consists of 3 actions. Therefore, I would replace "task" with "action".

Furthermore, it now seems that if the robot executes the 3 tasks of Category I correctly, it gets 10 + 10 + 30 = 50 points (besides the points for recognizing the command). Shouldn't this be 10 + 10 + 10 = 30 points? (similar for the other categories)

Also, the total score can never be 250, since only one category can be done. I guess the maximum is therefore: 40 (correctly recognizing 1st attempt) + 80 (correctly executing all actions, Category III) = 120. Or am I missing something?

**Comment by kyordhel** [comment]
First: your guesses  are correct. A command is composed of 3 actions or tasks. We kept "task" in the scoresheet because was the word used in previous versions of the test. We should correct that one.

Second. You choose a category once and a command with three actions (tasks) is generated for that category. There is no way to score 250 points with category 1 and 2.

Assuming you choose Category 3, you will get:
- 40pt for understanding the command at the first attempt and using standard operator.
- 20pt for asking reasonable questions to obtain missing information
- 40pt for performing the first action (task) correctly
- 60pt for performing the second action (task) correctly
- 80pt for performing the third action (task) correctly
In total that sums 240, and the remaining 10 points will be granted if you provide the recorded data for the test (audio files of given command).

Notice that, while in all categories the robot may be asked to move an object from one location to another, Category I will request a known object, Category II an alike object and Category 3 may request a tray or a cloth which is times harder to identify and manipulate. Therefore, more points are granted for solving a task.

**Comment by LoyVanBeek** [comment]
We could make the scoresheets clearer by marking which groups of items are mutually exclusive etc.

**Comment by kyordhel** [comment]
Scoresheets must be straightforward to "check" accomplished goals. On the other hand, the test description should be clear enough so teams understand what is being evaluated and how the test will be performed. 

For me, the scoresheet is clear, simple and practical (maybe we should add a line to write down the given command); but this issue rises a yellow light on the test description. Test must be reviewed to ensure is easy to understand.

**Comment by LoyVanBeek** [comment]
+1 for writing down the given command. At the last worldcup, I wrote down the setup (command, number and 'config' of people in Speech Recog etc.) on the scoresheet. Some room for that would be handy indeed.
