### ISSUE TITLE
Custom Continue Rule not clear on scoring

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#149]
For the Custom Continue Rule, it is not clear what penalty is applied for custom ASR alternatives. 
A nicely designed alternatives should get a smaller penalty than a QR code, which really really is the last resort. This last bit is not explicitly stated, teams should be encouraged to create good interfaces to their robots.

**Comment by kyordhel** [comment]
Thats OK, we already discussed and agree on that. 

 Continue Rule input method and interfaces are evaluated by the TC during robot inspection and set the penalty, informing to the team when the input method is approved. 

Unlike previous years, alternative input method don't halve the score for the whole test, it reduces the scoring of the ASR part or any other task being bypassed. QR clamps to 0, other methods up to 50% of the total.

**Comment by LoyVanBeek** [comment]
I want to make clear to the teams that it can go up to 50% or higher if we judge so.

**Comment by kyordhel** [comment]
Wasn't it 100% clear in the General Rules section where the Continue Rule is explained? O.o

**Comment by kyordhel** [comment]
general_rules/Procedure.tex under Continue Rule subsection

Automatic Speech Recognition is preferred and any command given to the robot will given by voice first.

- **Default:** When the referee generates a command for the robot, it will be read out loud by the operator to the robot. **100%** of the points gained in the execution of the command will be awarded.
- **team member:** If this fails, a team member may speak the command to the robot if this was not the case already.  **75%** of the points gained in the execution of the command will be awarded, if not stated otherwise.
- **QR-code:** If this fails as well, a QR-code will be generated that encodes the command as plain text and shown to the robot, displayed on either a piece of paper or a computer screen. A penalty of wil be applied, the factor of which must be specified in the test's scoresheet. **25%** of the points gained in the execution of the command will be awarded, if not stated otherwise.

And later

    The default penalties for ASR alternative methods will be decided on by the TC, during the *Robot Inspection* test (see...). This rule is loosely defined on purpose: be creative. Consider who may use a service robot, why they might want/need such a robot and what this means for how they might operate a service robot.

I thought we left it open because bypassing ASR ussign gesture recognition is by far more complex than using a Keyboard or QR. Also (even if I'm against GUI) coding an intuitive GUI for operating the robot has its merits, including using the Android ASR on a smartphone and send the text to the robot.

**Comment by LoyVanBeek** [comment]
I want to encourage the teams to create a good interface and point out that maybe even 80% score is achievable if you do a proper UI in whatever way. Heck, if I give it to my grandmother and she can use it without any training or explanation, I'd give out a high score for that. 
It could even be that for some users, voice is not even preferred because of a speech impediment.
