### ISSUE TITLE
Different scoring mechanism for Open & Finals

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#181]
As @swachsmu proposed on E-Mail:
1. team proposes a set of sub-tasks that are shown in the open test (shortly before the test)
2. during or after the performance the referees rate the difficulty of each sub-task (1-10)
3. after the performance the referees rate the degree/percentage of success (0%-100%)
4. referees rate the overall relevance for applications / relevance for robocup / innovation
   (assuming a perfect performance, i.e. maximal score if everything works perfect)
5. Referee score is computed by normalizing partial scores (from step 2) to maximum total (from step 4).
   Then each partial score is summed up weighted by the success rate.

**Comment by LoyVanBeek** [comment]
Or simpler:

Just 3 columns for: 
1) Difficulty
2) Performance
3) Relevance/Innovation

1-10 each column

**Comment by semeyerz** [comment]
Yes we should update the scoring mechanism.
Defining sub-tasks may not be possible for some kind of demonstrations?!

Keeping it simple is always a good idea but the third point could be split into two points in my opinion.
Do you want to have the same sheets for open & finals?
I liked the idea that in the finals the external jury rated from a different point of view like story and so on and the internal jury focuses on scientific and league contribution.

**Comment by LoyVanBeek** [comment]
I fear this scoring mechanism will not favor more open-ended demonstrations or when multiple skills are shown in integration. 
+1 for splitting 3) into separate Relevance and separate Innovation.

**Comment by kyordhel** [comment]
For the finals, I would separate the scoresheets for the internal jury and the external jury. Externals may not have the background to know what is new (innovation) or difficult. On the other hand, the TC/EC are quite used to work with robots so what they conceive as useful for real life may not be that accurate. Performance should be easier to score and even we may provide scale. As for the overall demo, the less intervention required, the better. A Final/Open in which the robot is the protagonist and there is no human intervention (other than explaining technical details to the jury) should be the goal.

**Comment by LoyVanBeek** [comment]
@kyordhel Internal an External jury scoresheets are already split. 

We could add some guidelines to make it easier: 
- Is manual intervention required?
- Does the demo still work if I would e.g. move the object a little bit or are all positions/object types/commands hardcoded?

**Comment by kyordhel** [comment]
Really? I didn't noticed any difference during the European Open. 

What I am about to suggest is a very bad idea in my opinion, is only for the finals (external), and requires 1 scoresheet per team.

Scoresheet has a grading table in which:
- column headers have the evaluation subject
- row headers have the scoring
- each cell describes what does it mean (or represent) that score for the subject.

It is a very bad idea because the jury may pay more attention to the table than to the presentation, or not consider de table at all. 

We may provide a similar table on the back of the OpenChallenge scoresheet for reference.

**Comment by kyordhel** [comment]
This is my suggestion for some fields, scoring 0 to 5 instead of 0 to 10.

|   |      HRI      |   Autonomy    |  Difficulty   |
|---|---------------|---------------|---------------|
| 0 |Robot and human never interact                           |Robot doesn't solve a task                              |Speak, move                                                       |
| 1 |Human speaks to the robot                                |Robot requires constant fixing or aid                   |Single handed manipulation, people finding                        |
| 2 |Human might solve the task without the robot             |Robot requires fixing or aid                            |Following and guiding, detecting major changes                    |
| 3 |Task was easier to solve thanks to the robot             |Robot requires minimal aid                              |Door opening, two handed manipulation, several people recognition |
| 4 |Robot paid major help in solving the task                |Robot requires no aid but fails to solve the task       |Simple task planning: Cooking, wet-mop cleaning, laundry          |
| 5 |Task unsolvable without the robot, it behave almost human|Robot requires no aid and susccessfully solves the task |Complex task planning: Assembling IKEA furniture, changind diapers|

**Comment by LoyVanBeek** [comment]
Yes, something like this indeed. Of course, a good explanation by the team of why a shown task is difficult and deserves many points is possible.

**Comment by kyordhel** [comment]
It has been already discussed by the Execs and they want the Finals to remain untouched, as well as the Open Challenge which could be evaluated by TC instead of peers. As of this year and the next one, it seems there will be no more modifications on this issue.
