### ISSUE TITLE
Off-robot computer

### ISSUE THREAD

**Issue by gjc13** [RoboCupAtHome/RuleBook#183]
Is an off-robot computer allowed?
That means, the computer doesn't move with the robot and is located in the team arena. And the power is not supplied by the battery of the robot. The computer may be connected to the robot via a router on the robot or the arena wireless network.

**Comment by kyordhel** [comment]
This is not an issue and is explained in the rulebook. 

It is allowed but must be inspected during RIPS by TC. The external device (computer, cluster, data center, camera, whatever) must be also inside the arena during the test and out once the test is over. No team interaction with the device is allowed since is considered as part of the robot. 

Important. There is no warranty of working wifi during tests. If your robot depends on external device and the device is not available, TC/OC takes no responsibility. Using external devices is on your own risk

**Comment by LoyVanBeek** [comment]
Please do note that [section 3.6 of the rule book](https://github.com/RoboCupAtHome/RuleBook/blob/master/general_rules/ExternalComputing.tex) has some strict requirements on the external computing resource. 

Specifically: the availability of the resource to other teams. Since RoboCup@Home is all about collaborating to advance robotics and AI, all teams must have an equal opportunity to use the computing resource, before, during and the competition. 
Please do include the relevant information in the Team Description Paper.
