### ISSUE TITLE
Score sheet for Manipulation & Object recognition adds up to 240 points instead of 300

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#184]
- 5x10 for grabbing
- 5x10 for placing
- 5x10 for recognizing
- 20 for finding hidden/occluded object
- 20 for grabbing hidden/occluded object
- 50 for opening the door or drawer

Adds up to 240 or am I stupid? 

Potential fix:
15 points for grabbing, for placing and for recognizing, 35 for opening door or drawer (similar but slightly less than in navigation test). Then -7.5 for incorrectly recognizing.

**Comment by kyordhel** [comment]
I don't think anyone is stupid here. We made something wrong.

Section 3.7.4 states that tests in Stage 1 grant between 150 and 200 points with a mx of 1150 for the whole stage 1.
Section 3.7.4 states that tests in Stage 2 grant 250 points each.

IMO, no test in Stage 1 should grant more points than a State 2 test. The mess was made because initially there were differnt points for each object, something like:
- Object detection (up to 60pts)
  - +5 Each known object (min 1)
  - +10 Each alike object (min 1)
  - +15 Cloth (max 1)
  - +20 Hidden (max 1)
- Object grasping (up to 70pts)
  - +5 Normal object (min 1)
  - +10 heavy object (max 1)
  - +15 Cloth (max 1)
  - +20 object in top shelf (max 1)
  - +20 object in bottom shelf (max 1)
- Object placing (up to 25 pts)
- +5 Each object (max 5)

**Note that this scoring completely changes the test** but it was the initial intention to score different capabilities. This way is up to teams to choose their own scoring. There are plenty known and alike objects in the shelves, one in the top, one in the bottom, one that is heavy, one occluded, and a cloth. A team choosing only known light objects from middle shelves would score up to 75 pts while a team showing all manipulation and detection skills can get 150 point. Scoring is not linear.

If you ask me, I would change the test to force teams to grasp at different heights and weights. For me that's more important than the PDF report.

Also, opening drawer/door is a special bonus. We should remove it.

**Comment by kyordhel** [comment]
So, a quick fix I suggest, clamping to 150pts as stated in section 3.7.4 and with no negative scoring as agreed and stated in issue #163, is as follows (not fair, I'm not loving it, but may work):

Score is granted on successful execution or correct recognition.

- Object detection (up to 100pts)
  - +5 Each found/identified object
  - +5 Each recognized known object in report file (max 5, stacks with finding).
  - +10 Each recognized alike object in report file (max 5, stacks with finding).
  - +20 Finding occluded object (max 1)
  - +20 Recognizing occluded object (max 1, stacks with finding it).
- Object grasping (up to 25pts)
  - +5 Each object (max 5)
- Object placing (up to 25 pts)
  - +5 Each object (max 5)

The maximum amount of objects to be considered is 5. False positives and missrecognitions decrease counter by one. Only the first 5 objects in the report will be considered, if they are all false positives.

Examples:
- Report show 5 objects, all of them boxed but marked as unidentified. Score: 25pts.
- Report show 5 objects, 2 correctly labeled known, 1 correctly labeled alike, two non labeled. Score: 45pts
  - +25pts (Identify 5x5pts objects).
  - +10pts (Recognize 2x5pts known objects).
  - +10pts (Recognize 1x10pts alike objects).
- Report shows 4 objects, 1 wrongly labeled, 1 correctly labeled known, 2 correctly labeled alike. Score: 45pts.
  - +20pts (Identify 4x5pts objects).
  - +05pts (Recognize 1x5pts known objects).
  - +20pts (Recognize 2x10pts alike objects).

Tell me what do you think.

**Comment by LoyVanBeek** [comment]
I think adding 10 points somewhere so it adds up to 250 is sufficient. Keep it simple.

**Comment by kyordhel** [comment]
So... 250pts for taking objects and 250pts for solving Restaurant?

No way.

**Comment by LoyVanBeek** [comment]
Now it says 300... Restaurant is not that much more difficult. No team has ever completely done it but neither has a team ever finished all of the manipulation task. The scores are in balance.
