### ISSUE TITLE
Don't set minimum time for holding object

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#195]
Just say that the robot should get it out of the bookcase holding it in it hand. 
The 5 second holding makes no sense really, ideally the object is placed again within 5 seconds!

**Comment by kyordhel** [comment]
The 5 seconds rule is there not because 5 seconds make sense, but as a guideline to prevent robots taking and object and dropping it immediately. 

In former rulebooks the rule was *firm grip*, and that the robot *must not drop the object* but this happened a lot. What we want are two things:

- The placed objects stands still and stays in place.
- The grasped object remains in the manipulator until it is placed again.

**Comment by moriarty** [comment]
In RoboCup@Work we've also tried different policies to enforce that teams aren't simply lifting an object off the surface and then simply dropping it... The rule has been changed a few times and at one point also included timing but doesn't now... disputes over the definition of this rule actually would have made the difference between 1st and 2nd this year.

I just wanted to let you know the 2016@work rulebook had this:

`An object counts as grasped from a service area, when the object was moved outside of the
source service area. Outside means, that the vertical projection of the objects convex hull does
not touch the service area any more.` - section 2.4.4

Service area = shelf surface. It's awkward to read, but attempts to enforce that teams have firm grips that aren't just going up and back down.
We have no lasers or precision measurement to see if it's outside of the convex hull... which came up this year as an object was grasped but it came down to a vote from the judges if it was fully outside of the "projected convex hull" when the timer went off... after the timer the robot finished doing what it was suppose to- so they may amend the rule yet again.
