### ISSUE TITLE
Automate scoresheets

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#197]
Taking notes on a paper score sheets and then adding everything up by head is a hassle and takes too much time. 
Its a waste of time and paper. Digitally entering the scoresheets on a tablet or laptop is much nicer and allows automatic addition of the points.
If the teams upload their data logging to an FTP-server as well, that can be checked automatically as well.

**Comment by LoyVanBeek** [comment]
http://tex.stackexchange.com/questions/14842/creating-fillable-pdfs

**Comment by kyordhel** [comment]
**Teams uploading their recorded data to ftp.** Agree. However is a huge amount of data. Who will host that data? We may use HTTP instead and provide a (weak-password-protected) form that allow teams to upload their data up to 30 minutes after test, while also providing a nice report of which teams have uploaded data and which don't.

**Fillable PDF scoresheets.** I strongly disagree on this one. Nothing is easier than pen and paper and, since it will be I the one who will make the scores, I rather like to work with fail-safe technology. Instead I rather would like to have a web-app for scoring (check marking).

However, I don't see myself taking notes in a tablet or laptop, while in a sheet of paper is straight forward. Let's check with RoCKIn the automated scoring experience.

**Comment by LoyVanBeek** [comment]
I would also like the web-app for scoring and that was what I originally though. But it means keeping the rulebook and the web-app in sync which will really suck. The PDFs can still be printed but _also_ computer filled later. They can also be submitted to a simple server which can do the rest. 

We can even extend the LaTeX macros to do most of the work here. 

The data amount is OK-ish, I have 24GB sitting on my computer. I asked @dirkholz whether he could do something in this regard @google.

**Comment by LoyVanBeek** [comment]
To be clear, I don't want to automate the scoring itself, just the calculations. 
I'm fine with recording the scores on paper and then entering them into a digital form which takes care of the computing.

**Comment by kyordhel** [comment]
This issue is also addressed in #354. To avoid redundancy, I'll close this issue
