### ISSUE TITLE
Divide tests between the new leagues. 

### ISSUE THREAD

**Issue by balkce** [RoboCupAtHome/RuleBook#203]
We need to consider the new leagues and divide the tests accordingly. This does not imply separate tests (one test can be used for the three leagues). 

To start we should first define what each league want to test, and then assign the test that we have already to that set.

**Comment by LoyVanBeek** [comment]
To be clear: we have an Open Platform and 2 standard platforms: [Toyota's Human Support Robot (HSR) ](http://newsroom.toyota.co.jp/en/detail/8709541/)and [Softbank/Aldebaran's Pepper](https://www.ald.softbankrobotics.com/en/cool-robots/pepper). 

The 3 different types of platforms will each have a league with (mostly) shared tests and perhaps some unique to each league. Which those are: **?**

**Comment by swayshuai** [comment]
I heard that HSR isn't a ROS-based platform？

**Comment by hideakin21** [comment]
It IS a ROS-based platform.

**Comment by swayshuai** [comment]
Maybe we should think about how many attempts are allowed...   36 teams...   Each team 3 times...

We can reduce some tests' attempts such as speech recognition (or High Level HRI Test), because we test so many sentences.
We can also add more attempts in GPSR to reduce random bad luck, test comprehensively in manipulate objects, person recognition, planning, HRI...  We have enough time, because some robots don't attend the GPSR. And it always take less than 3 minutes to finish a task in GPSR.

**Comment by LoyVanBeek** [comment]
+1. It should at least. 
With the speech recognition, some teams have complained that the early teams had low noise when the ones scheduled around noon had very much noise.

**Comment by kyordhel** [comment]
Technically, the SSPL won't perform manipulation, so all tests focusing on manipulation need a workaround to use HRI instead of manipulation (e.g. the robot guides a person with visual impairment.

This far I see only 4 tests and OC will try to have no more than 14 teams in OP. For SPL no more than 12 are expected. Therefore, is feasible to make 3 runs of each Stage 1 test if they are no longer than 10 minutes and are pipelined as previous year. Otherwise, tests need to be adapted for Restart Rule.

On *Stage1*
- SpRAT and Person Recognition (now RoboGame) present no problem
- GPRS has been adapted to suffice this isue (change of grammars in generator
- I propose replace Help-me-carry with last year Follow & Guide. Specially since Trustees want Peppers chilling out all around the venue.
- Storing Groceries is the major concern here. A new HRI test is required.

On *Stage2*
Stage 2 is undoable for SSPL since 2 out of 3 mandatory tests are manipulation based. We need alternatives for STTCU (and maybe another cachy name) and workaroungd restaurant.

It's brainstorm time.

**Comment by LoyVanBeek** [comment]
I think Pepper can be useful in Help-me-carry, although maybe with some light objects. I'm fine with handing it an (light/empty) plastic/paper bag. The main part is navigation and Pepper is capable of doing that. 

I'm also fine with Pepper dropping out of Storing groceries, but it can still do the recognition part and tell what objects should go where. 
A robot becomes most useful when it can actually help me with physical stuff. For a lot of other things, a smartphone or something like Alexa/Echo type things are fine, which is not the point of this competition. 

TechUnited's Sergio even lacks arms currently but still did OK-ish in the Restaurant test.

**Comment by kyordhel** [comment]
What I understood from Pepper is that the arms are aesthetica. TThe main problem is not weight, but that the design does not allow the robot to hold most objects (it can hold a microphone, but will have problems with an apple or a 250ml milk). We may try to **make the robot to lift a plasting shopping bag with a bright handle** but that should be written on the rulebook.

Another mod as you suggest is that Pepper does not do the grocery storing (it cant) but picks up the Grocery Boy from the Walmart's Van, guide him to the house, and, as you said, still do the recognition part and tell what objects should go where. Small mods to the test in order to make it feel more natural and with a nice tale.

About Sergio, I remember a Tray was adapted for him. I'm not sure this can be an option for Pepper; and remember that many hostess never do manipulation, but instead take you to the table and manage stuff. 

**Trustees want SSPL be more about interaction with no manipulation.** That's why I am suggesting do changes.

**Comment by kyordhel** [comment]
After the inclussion of *Tour Guide* and *Cocktail Party* the rulebook is diverse enough.
