### ISSUE TITLE
Tasks in person recognition

### ISSUE THREAD

**Issue by swayshuai** [RoboCupAtHome/RuleBook#204]
So many teams did well in this test. So...   :) 

This test is established to test the robots' basic abilities in person recognition. But I don't think this task can cover all the problems in "person recognition at home". We can think about similar tasks about people in GPSR and find out the missing problems. And my target is that this task can improve robots performance in tasks about people in GPSR.

For example, last two years in person recognition, people stand as a crowd. However, In my home, members in my home won't stand as a crowd unless they want to take photos. People in the home are scattered. Some people sit on the sofa, some people stand besides the table.  To find out the operator, robots should patrol in the house, generate the scan position itself, look for the target.

Person Recognition Test's target is test the robots' abilities to find the operator, but not the face recognize algorithm to find the operator.It isn't a good  appearance that many teams treated person recognition as "test algorithm about face recognition in images", attached a huge SLR camera on their robots, and removed the camera just after they finished their tests in Person Recognition.

**Comment by fpolster** [comment]
I also think a more natural Person Recognition test would be nice. 
I like your idea of letting the robot search an area for the persons instead of detecting them in a group image. 

But instead of letting the robot patrol the whole house I would suggest to restrict the search space to one room. This would reduce the needed time and enables the test to be done parallel to other tests. 

As an addition to this idea the robot could be approached by a person and given a command. The robot should act differently if the command is given by the operator.

**Comment by LoyVanBeek** [comment]
Another idea is to have people stand around in little groups of ca. 3 people, chatting with each other.
The robot must introduce itself into the group and do several person recognition tasks for that group. 

Having the robot get into an existing group is an interesting social skill.

**Comment by swayshuai** [comment]
Once, I had some ideas about Person Recognition. But the challenge I had designed took too much time(about 7 minutes).

 Several Guests are scattered in a specific room of Home arena, while the robot patrols up and down inside the room, trying to remember any information about each guest (gender, age, gesture). Once the robot has gathered enough information about the Guests, one of the Guests leaves the arena, when a Stranger sneaks into the room. The task of the robot is to find out who is the Stranger.

**Comment by kyordhel** [comment]
You should checl former years' Cocktail Party and Who-is-Who, kinda same idea but in different envelop.

Main problem of Person Recognition is that people is all together within camera FOV and teams may bypass the test by using a Hi-Res camera and OpenCV. There is nothing new here, and performance is no better if people is all over the room (e.g. lying, sitting, etc) and the robot needs to find them (and into the darkness bind them).

Nonetheless, since this test is being merged with speech recognition, I'm closing this issue.
