### ISSUE TITLE
Missing definition of the term "challenge"

### ISSUE THREAD

**Issue by rokusottervanger** [RoboCupAtHome/RuleBook#233]
The word "challenge" is used throughout the rule book, but it is never defined.

**Comment by rokusottervanger** [comment]
Suggestion: 
A RoboCup @Home challenge (challenge, for short) is a collection of tasks that need to be performed by a robot. The robot should perform these tasks autonomously unless stated otherwise in the description of a specific challenge.

**Comment by kyordhel** [comment]
@rokusottervanger could you please provide specific references to the misuse of the English word «challenge» that would require definition?

In most cases the word challenge is part of a test name, namely
- Open Challenge (test)
- Demo Challenge (test) [deprecated]
- Technical Challenge (test) [deprecated]
The word «test» is not appended because a challenge (accordingly to Oxford definition of the term) is by nature some sort of test. The main difference is that in normal tests the robots must accomplis a well-defined set of task,s while the challenges are by far less restrictive and the scoring is ad-hoc. This is properly defined in Chapter 2. 

In consequence I see no need to redefine any term.

**Comment by rokusottervanger** [comment]
In some cases the word "challenge" is used in the meaning of "test"; for example in 3.2.1: "Robot must be prepared to perform any challenge in any arena [...]" or multiple times in 3.4, among which "During a challenge, specific data is to be gathered and stored on a USB stick." In these cases, I believe "test" would be a more suitable expression, as opposed to "challenge". The difference is that the word "challenge" is now specifically used in the sense of "A task or situation that tests someone's abilities" (Oxford dictionary) as opposed to "A call to someone to participate in a competitive situation or fight to decide who is superior in terms of ability or strength" (Oxford dictionary) or "A call to prove or justify something" (Oxford dictionary). Because of these different possible meanings, I think it would be useful to clarify the intended meaning (and/or be more consistent in the use of the word) and it may as well be defined specifically for RoboCup @Home then.

In names of test descriptions, the use of the word is not very relevant. As these are names, they may be whatever the inventor of the name likes.

**Comment by kyordhel** [comment]
@rokusottervanger Ok, I concede you this one (although it shouldn't cause any problem). That text has been there since the first rulebook, so I think an update won't harm.
