### ISSUE TITLE
Storing groceries classification

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#253]
For the classification of unknown objects, there are some levels of performance:

- Label all unknowns simply as "unknown": 5 points per unknown-labeled object (to match the negative score of labeling _everything_ as "unknown")
- Label pairs of unknown objects (e.g label each of the 2 apples as "typeA"): 15 points per object
- Label unknown object as correct category (e.g. label an apple as fruit): 20 points
- Label unknown object as correct class (e.g. label apple as apple): 20 points

**Comment by swachsmu** [comment]
By labelling unkown objects with class or category labels, we might get into trouble to distinguish them from recognition errors. If the robot has never seen a pear it might just call it apple which is a recognition error, but reasonable because they share many feature. Although category recognition might be the goal, I am not sure how to judge this. Perhaps we should stick to having common new labels for identical pairs of unkown objects.

**Comment by kyordhel** [comment]
The rulebook might state that there will be, for instance, 3 pairs of unknown objects (i.e. 2 of each for a total of 6).

Also, IMHO the rulebook is quite confusing with all this tricky words like «class», «category» and so on. I would go for a simpler: objects must be placed all together with those equal to them or of the same kind. Criteria can be specified in the report file. I would grant 5 point for placing the red cloth next to the coke and specifying the common shared property: red, but this is wrong since cloth is not a cloth. Other properties like: can, box, fruit, pasta, cereal, and so on are valid, but I don't expect that from teams. On the other hand, descriptors like food, square, feature36 are not valid since are either too general or meaningless in human communication (no sane people groups groceries by geometry or based in numeric features).

**Comment by kyordhel** [comment]
Another issue related to classification but not addressed in #254

Recognizing *alike* objects should grant more points since they are more challenging than *known* objects.

**Comment by LoyVanBeek** [comment]
Alike objects could get a little more points. However I have not heard teams complaining that one is harder to do than the other. 
It would make scoring more difficult and raising the bar for object recognition is OK with me.

I'd rather keep things as they are now.
