### ISSUE TITLE
Opening the door in the storing groceries task

### ISSUE THREAD

**Issue by swachsmu** [RoboCupAtHome/RuleBook#258]
I think it is not a good idea to have the complete shelf covered by a door. For the teams it is very risky to open it autonomously because they may loose all the points for placing and recognition of shelf objects. I would suggest to close only one half of the shelf by a door. Thus, the robot can work on the task without opening the door, first, and solve half of the task. Then, the robot can open the door, gain an extra time bonus, and is able to solve the complete task. The robot would NOT be allowed to ask a human to open the door for him.

A similar thing with time bonus could be done to distinguish team which just do object recognition from teams who a doing the grasping and placing. At the first time the robot has only 2min for visually inspecting the objects and to a first grasp. If the grasp was successful the robot would gain a time bonus for completing and doing more grasps (e.g. extra 2min).

**Comment by kyordhel** [comment]
@swachsmu I agree with your suggestion. Even we might remove one of the doors for safety reasons. In my understanding, the _cupboard_ must contain at least one [small] door with space for performing the test even if the door is closed, like the one in the picture below:

![image](https://cloud.githubusercontent.com/assets/8583949/25799014/ad530f0e-33e3-11e7-9a6c-ae983a585cfb.png)

However, this kind of shelf might not be accessible to all teams since many could not be able to reach the upper part. Therefore, I think the RuleBook should depict something more or less like this

![image](https://cloud.githubusercontent.com/assets/8583949/25799434/3a94831a-33e5-11e7-91e2-b564c1f78c20.png)

Or within our budget (we may not place the right door of this IKEA shelf):

![image](https://cloud.githubusercontent.com/assets/8583949/25799400/15fbf59c-33e5-11e7-818b-c31eebe42031.png)

About the 2 min limit for first grasping, I also give my up vote. Although it makes the test slightly harder to control, it also adds an implicit requirement of action planning. In order to get the extra time, teams will be forced to choose the easier-to-grasp object in sight, and not a random one.

**Comment by balkce** [comment]
@kyordhel pretty much explained all I have to say in the matter.

The last IKEA shelf without one of the doors in place seems ideal. In any case, my guess is that there won't be a lot of teams attempting to open the door.

The only issue I have is that the time addition will make it harder to evaluate, but as long we have enough judges and one of them taking care of only of the timing, I see no problem.

**Comment by LoyVanBeek** [comment]
I agree with the time clause Sven proposed. It takes some referee effort but indeed with the provision that at least 2 referees are needed. If two robots start at the same time in parallel, like we did at the German Open, 3 referees could manage 2 robots at once. 

I'm also in favor of e.g. having a door that covers e.g. only the left half of the cupboard, like @kyordhel proposed.
