### ISSUE TITLE
EEGPSR way too complex

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#260]
EEGPSR is not working.
The test is too complex and the ScoreSheet is too long, making hard for referees to score what the robot did.

We need a brainstorm on how to make it simpler.

**Comment by LoyVanBeek** [comment]
The simplest fix for the scoresheet is to not specify the commands in each category, but simply say "Category 6 is xxx points", regardless of the exact task. 

At the German Open, this task was do-able by the robots that attempted. The selected categories were mostly 8 (3 simple commands), some 5 (Missing information) and one or two 3's (People tracking/following). 

This task is mostly hard to set up: objects and people must be put at places matching commands. This setup takes time. 

I found that the hassle to set this up was now manageable, with 2 experienced referees. I had prepared commands to give every robot beforehand, printed. The hassle of last year with the QR-codes was gone, that was madness. 

Having half of the robots go through this will still be busy though.

**Comment by LoyVanBeek** [comment]
Point still is: this is what home service should do all the time. The other tasks should be able to be implemented in terms of EE-GPSR command giving.

**Comment by kyordhel** [comment]
My idea is:
Reduce the test to 3 categories like GPSR (easy, moderate, hard) and score by acomplished task like in former years. Is unfair since "set the table" is by far more complex than "take Mama to the dormitory (mama is lying of the ground)", but at least will be easy to score.

**Comment by LoyVanBeek** [comment]
Doing this now could piss of teams, I'm afraid. 

Grouping the current 8 will require to redistribute tasks. Cat 8 would be easy, Cat 7 (memory and awareness) is difficult. But then we know quite sure no team will attempt difficult. 
Not that I have seen cat 7 chosen, ever, so that won't make a difference.

**Comment by HideakiNagano21** [comment]
If the robot can not understand the command, the robot don't move at all and it is not much fun for the audience. This happens a lot.

How about the custom operator separating the command sentence in their own way for easily understanding?
Of course, it must get marks taken off.

**Comment by kyordhel** [comment]
@HideakiNagano21 It happened a lot that robot was perfectly able to **recognize** (ASR) the command, but **not to understand** it. At least, in Leipzig @LoyVanBeek and I realized that the problem is not speech recognition, but NLP. Whatever the operator is, if a robot seems unable to understand the command, most likely is because it can't execute it.

Now, letting the custom operator to *re-phrase* the command means no natural interaction since an specialist is required to operate the robot. It seems to me very unfriendly and counter-producing. If we follow that line, I would go for severely penalize this.

**Comment by LoyVanBeek** [comment]
For this purpose, we added the continue-rule, which I have seen one or two teams using last year. The QR codes are a complete disaster, but a nicely designed tablet UI etc. is allowed by the the continue-rule. 

At the German Open, both ToBI and Homer understood the commands perfectly, so it is definitely possible. Other teams have also been perfectly able in the past.

**Comment by fpolster** [comment]
Backing the realization from Leipzig, I can confirm in the majority of cases the NLP is the problem. 
I think the continue rule is good for passing failing speech recognition, but should not be used to avoid the NLP.

I believe the changes proposed by @kyordhel have to much impact to be introduced so late, but additional clarifications and changes to the scoring could be useful:

I prefer a scoring based on the categories rather than the abilities. 
Even if a team chooses three different categories e.g  cat3, cat8 and cat6, it is possible that every command includes a guide command. Point 6.6.3.6 states that an ability can only score once - so even if the team would perform perfectly it wouldn't get awarded with a great amount of points.
If the teams should do different categories, the rule could be changed so that a category can only score once.

My suggestion would be to change the scoring to a set number for the different categories and reward accomplished parts of a command. 
e.g. if the command is: "bring me the apple from the cupboard" and the robot gets an object from the cupboard to the operator which is not the apple. The robot could score 2/3 of the category points because it was able to get an object from the cupboard but was not able to recognize the apple. This would allow to adapt the scores to reflect the robots performance and would be much easier to score than the current score sheet.
While the teams have no chance to alter the difficulty of a command(with exception of the category), I think scoring the complexity of a command has no benefit and can be removed. 


Additionally I would welcome clarifications of the additions EEGPSR has in contrast to GPSR(command retrieval - execution). I remember that activity detection and telling what the robot did last could be done, but I am unable to find it in the rules(with exception of the scores). 
Should the robot proactively ask the operator if it should wait for an event?...

**Comment by LoyVanBeek** [comment]
@fpolster The scoring differentiation per skill and scoring each only once is there because we want robots to be General and be able to do various things instead of 1 thing over and over. I have to agree that combining this with a random generator sort of trumps that because it can very well generate 3 commands requesting the same skill. 

Conclusion:

- No big change and reshuffling of categories. 
- 1 score per category. If a command consists of eg. 3 subcommands and only first one is achieved: 1/3rd of points for a command of that category
- Operators should aim for a different type of command within the category for each robot, so no 3x guiding or 3x grasping if they would be in the same category. Some categories a narrower than others though. 
- We have to define points for each category:

1. ?
2. ?
3. ?
4. ?
5. ?
6. ?
7. ?
8. ?

**Comment by kyordhel** [comment]
@fpolster @LoyVanBeek Most probably that branch will be merged after Nagoya, so let's focus on fix exploits and make the ScoreSheet more understandable.

### Category-based scoring
The scoring can be turned out much more coarse (e.g. pick-n-place instead of grasp, place, etc), but not reduced to an average over a category since in Cat 1 opening a door (manipulation) is by fare more complex and time consuming than a Go-Get-It. In Cat 2, Bring the right-most object from X is harder than counting how many Y are in X or describing all objects in X. When there is category overlap this becomes even harder.

On the other hand, a team with lame performance at everything else but interacting with people should be allowed to get N (different) commands of that category (IV) like, for instance, people detection, gesture recognition, posture recognition, and (previously known) person recognition.

### Scoring
In theory, referees should write down the commands given and what the robot did. Scoring comes after the task/test.

### Exploits
Abilities can be scored only once, but only when the robot is commanded to. If I ask the robot to bring me a coke from the counter, the robot is not allowed to open the fridge's door, grasp an ice, wake up John in the couch, explain John it was commanded to bring me a coke, and then give me the coke. Specially for this test, **I don't like proactive robots.**

### Number of tries
It is not clearly specified that the maximum number of commands to be executed is 3, but a slight reference in **6.6.2.6 Timing**. We can either allow a robot to run as many commands as the time allows (Max 15 min per robot and 5 min per command, so average is still 3), or cap it to 3 explicitly. I would like to give the chance to quick robots to do more.

### Explaining what has been done.
To be honest, I cannot find it on the rulebook nor in the scoresheet. Maybe this should be removed from the generator.

**Comment by LoyVanBeek** [comment]
Regarding the number of commands to a robot: Some commands simply take more (driving) time than others, making things unfair. Also, I really don't want to keep track of which robot has spent how much time and if it has time to get another command. I'd rather cap to 3 commands explicitly, for fairness.

If we require teams to choose a single command category, then we can give each team a similar set of 3 commands within that category. 
Then some problems go away: 

- Different skills still yield different points but every team gets the chance to show the same skills
- We measure time on the same skills so time is more comparable.

**Comment by kyordhel** [comment]
Agreed capping the number of commands to 3. I would beg for 4 to make them hurry because of the Endurance part of the test. I mean that robots should be operational for as long as possible, and not quit when 3 commands are given. Although this situation may not happen.

As counter-argument, I'm assuming that all teams will run exactly the same commands for a given category (maybe with different objects). As the test is quite long, this might give time to some of them to tweak them. 

But following your line, then lets reduce the number of abilities being tested to *shrink* the scoresheet (e.g. remove button pressing, bottle opening, and stuff no team has ever shown).

**Comment by LoyVanBeek** [comment]
Shrinking the scoresheet is fine.

**Comment by fpolster** [comment]
Regarding the number of command vs time of all commands I am for a set number rather than a set overall time - because as already mentioned driving time needed per command varies a lot. Yet category eight seems to be designed to be hard to do because of the time needed - if the time is removed, it is the category with the biggest point potential, because a lot more skills are shown during one command. 


I am against letting the teams choose on a single category - this would effectively mean that seven categories are removed on a competition day. Alone the discussion on which category should be chosen could take a whole evening and afterwards all teams who did work on other categories are grumpy. 

While running the same command for all teams is more balanced, it is also less interesting. The judges would have to do the same thing over and over - the audience would see the same thing over and over and the teams could overfit their robots because they know what is coming. 


Shrinking the Score-sheet is a good idea - maybe put something like difficult task in each section for tasks which no team has ever shown(could include examples). 
While I think scoring the difficulty of skills is a good idea, it only is when there is the possibility to show them - maybe teams could define include flags(sadly more work for the judges) e.g.:

Team A chooses to include opening a bottle
Team B chooses to include opening a bottle and finding hidden objects
Team C chooses to include driving outside the arena and detecting unexpected events

When the command for team A would have been "get the coke from the desk to me" it could be "get the coke from the desk open it and give it to me". So if Team A thinks it can do it, they have the chance to show it.

**Comment by kyordhel** [comment]
Some remarks:
- The purpose of EEGPSR is show more advanced skills, Category VIII shouldn't be there.
  - Cat8 is there because is.... some sort of... backwards compatibility? Legacy mode?
- Same category neither means similar difficulty degree nor similar time. E.g. In Cat 1, serve breakfast vs opening a door.
   - In contrast, teams could be required to choose categories 2 hours before the test which will be pick by the referee in random order.
- Running the same command [set] is OK as long as there are variants and not all teams choose exactly the same categories.
  - All teams choosing Cat 1 will serve breakfast, although some serve Cereals + apple, others milk + banana
  - All teams choosing Cat 3 follow a person to the car, and then go back. Car is located in different location each time.
  - Cat 8 should be mastered so is ok if remains random.
- No examples in scoresheet. Just no.
- Something as ambiguous as "difficult task" to be discussed later on by the TC/referees will turn EEGPSR into some sort of OpenChallenge for the outrage of the teams.
  - It would have been OK if TC had received feedback from the team, but this far all contributions aim to lower the difficulty degree and not propose new stuff (often left for Open Challenge).
