### ISSUE TITLE
Clarifying "what's new"

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#267]
For newbies that participate in the competition, it is very hard to comprehend and track all the changes proposed here as pull requests / issues.
I'd like to propose to clarify "updating" process of this rule book, for example one major update in a year and one minor refinement in six months like Ubuntu OS.

Pros:
- We can aggregate all the changes on each update as "What's new" and all teams can easily track updates by reading the section instead of watching all the pull requests
-  This prevents unpreferable changes and clarify pending discussion for next update (e.g. ones that are too short period to the competition, ones that should have been discussed more)

Cons:
- Some members need to manage update procedure. (We have committee so I believe we can manage.)

Discussion is very welcome!

**Comment by kyordhel** [comment]
### Short answer
Official drafts and final versions have always been published in the @Home website and sent to the team leaders, just as they are distributed now. If you want for a *stable release*, you can look there, but if you really want to get into the rules an contribute with the creation of the rulebook, now you have the tools for that.

### The story so far
In former years, the rules were discussed only by TC members who wrote or updated the rulebook after reaching consensus. Such discussions were closed and teams had access to the rules every time a draft was released. The final version usually was released between one and two months before the competition. 

However, discussing the rules via forums, skype, and emails, not necessarily produce a written document, and many good ideas are lost in between. Therefore, the schema was changed to open discussions here, in GitHub, where all the league can contribute with questions, inquiries, suggestions, and pointing out holes exploitable holes. Even more, @Homers can now propose rules and send a pull request to be reviewed by the TC, who finally approves or discards the change, while other members of the community can comment on these changes. All this is good since @Home is a competition by peers to peers.

### What is missing
Sadly, not all TC is actively contributing, but on the other hand, people from the teams had helped a lot with the creation of the Rulebook. In addition to the rulebook, we would like to have:
- An updated wiki with all the TDPs, videos, scores, and awards.
- A GitHub page/wiki...
  - Explaining in detail the rules.
  - Defining roadmaps that help to take robots to domestic environments.
  - A documented historical of tests with videos of robots solving the tasks.
  - Downloadable data sets.
  - A What's new section highlighting the changes since the last official release

But all these require volunteers to help with it. TC members are also volunteers who devote several hours a week to the rulebook, but this far we haven't had time to come up with all the pending work and the ToDo list grows every day.

**Comment by LoyVanBeek** [comment]
@furushchev I definitely understand your pain. The rulebook is big and complex and it may require some getting used to. 
A high-level changelog in the rulebook would not hurt but I can't promise that we can put something in soon. 

I've also been thinking about a release process BTW:

1. deadline for change proposals
2. announcement of a selection of those
3. deadline for drafts with implementation
3. Time for community to comment on the drafts
4. deadline for final version.

**Comment by kyordhel** [comment]
@LoyVanBeek I totally agree, deadlines are required and necessary.

But lets be honest. TC are volunteers and what the TC members do is done on their own free time (or stealing some working hours). Even though we have tried to meet our own deadlines, there is no way to force a TC comply, even less to team members (they have many projects other than RoboCup). In contrast with Ubuntu developers, we are not supported by the donations of millions of people all around the world.

Despite that, in addition to the points you propose, I would add the following:
- EC releases a set of long-term goals and deadlines, such as:
  - Boarding public transport
  - Buying real stuff in a store with real money
  - Cooking a real omelette
  - Helping a human to assembly IKEA furniture
  - Placing all dishes in the dishwasher and clothes in the washing machine.
- EC releases milestones to be analyzed by the TC 
- TC modifies the rulebook to force robots approach the milestone
- TC & EC evaluate the performance of the robots.

**Comment by LoyVanBeek** [comment]
That indeed would be a better process than we have now: EC should set a roadmap like the ones proposed in a few issues. 

I would like to add that every change should come in as a Pull Request (I actually made this mandatory in the repo settings somewhere last week). If the deadline passes without the pull request being merged, then that means: too bad, this change did not make it even though it was proposed and accepted.

I certainly work on my free time and this year's rulebook writing has been frustrating for some of the reasons you mention. 
My code is done compiling, back to work.

**Comment by kyordhel** [comment]
@LoyVanBeek shall we delete branch after merging? What's the policy on that?

**Comment by LoyVanBeek** [comment]
Branches should be deleted after work on it is finished.
