### ISSUE TITLE
Performance limits of SPL

### ISSUE THREAD

**Issue by HideakiNagano21** [RoboCupAtHome/RuleBook#273]
This year is the first time for us to have standard platform league.
HSR & Pepper have some performance limits. Please see the detail following,

### HSR
- Max motion speed: 0.8 km/h. 
- Max step height: 5 mm. 
- Shoulder height: 1030 mm.
http://www.toyota-global.com/innovation/partner_robot/family_2.html

### Pepper
- Max motion speed: 2 to 3 km/h.
- Max step height: 15 mm.
- Top height: 1210 mm.
https://en.wikipedia.org/wiki/Pepper_(robot)#Specifications

I propose these information need to be mentioned in the rule book.
In addition, the all tasks need to be designed considering these limits as following,

- The walking operator should walk slower than the max motion speed.
- There should be no step higher than 5 mm on the floor.
- The grasping object on the shelf should be lower than the shoulder height.

**Comment by kyordhel** [comment]
I don't see any conflict between those limits and the current rules. Referees will place objects within the robot manipulation range (as usual), and operators will try to be friendly. Only problem would be the step height (it is always a problem) but this is of no competence of the Rulebook, but the LOC and the people in charge of setting up the arena. Yet, teams always come up with a solution. They are engineers after all, thus can be trusted. Nonetheless, I must say this information arrives quite late; as it should have been provided **before** tests were redesigned.

As side remark, this somehow enters in direct contradiction with #185 (Remove all exact numbers). Is quite annoying for the referees being chased by teams with strange measurement systems wanting to score because stuff were one millimeter or degree out of range.

You are welcome to make the PR and include that info in the section devoted for league specification.
