### ISSUE TITLE
SPR: Points for Questions

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#281]
**Speech and Person Recognition**
I think the separation into understanding and correctly answering a question is good. But what is the reason that it only exists for the 2nd part, the blind man's bluff game? I think it would make sense to have the same distribution of points in the riddle game for the questions.

**Comment by kyordhel** [comment]
The separation is a late patch introduced by @LoyVanBeek in #266. Now you point out at it, is an inconsistency. Robots should score always the same for understanding a question and for answering a question.

However, I think this test is poorly designed and unbalanced, so I don't want to increase the overall points for it. My suggestion is to adjust the score sheet as follows:
#### Riddle Game
- Understanding question: ``6x5``
- Correctly answered a question ``6x5``
#### Blind man's bluff game
Turned towards person asking the question ``6x5``

This makes sense since in the *Riddle game* the question is made once and the robot is looking towards the operator, while in the *Blind man's bluff game* the operator is behind the robot.

Nonetheless, this is still a patch. Only the questions about the crowd are allowed to have discrepancy between the given answer and the ground truth. If the robot is asked for the heaviest object or the largest room, there is no interpretation there, the robot answers wrong because didn't got the question. Therefore, only the questions about the crowd should be scored separately.

**Comment by johaq** [comment]
This change looks good to me. Regarding your last point: A robot can definitely understand a question about weight comparison and answer it incorrectly. In these cases awarding points for the correct answer rewards teams who have some sort of representation of knowledge about the objects and environment that goes beyond just deep learning them (or I guess teams who hard code the answer to every possible comparison).

**Comment by kyordhel** [comment]
I am not sure you can "deep learn" features of the objects in @Home beyond object recognition due to the amount of data available and, in such cases, nothing more complex than tuning a preexisting model. In any case, I would be too naive if I expect most teams have not hard-coded answers (don't call me [d]evil, call me old).

But I understand your point and will take the advise. Let's make sure the questions of generator does require some kind of Knowledge Base in order to answered.

**Comment by johaq** [comment]
I think that requiring a knowledge base and rewarding that with the points is a good thing.
If a team actually goes through the trouble of hard coding the answer to 35*34 comparisons of size and 35*34*6 category affiliations I guess they deserve the points too...

**Comment by balkce** [comment]
The number 6 has always been weird to me, reduce the questions in both phases to 5, and you can do the separation more cleanly without going over the 200 point threshold:

male/female count: 10

Riddle Game:
understand the question: 5x5
correctly answer the question: 5x5
answer all questions: 5

Blind man's bluff game
understand in first attempt: 5x10
understand in second attempt: 5x5
correctly answer: 5x5
turn towards person: 5x10
answer all questions: 10

I also switched around the points for "answer all questions", since the riddle one was 10 and the bluff game was 5; it should be the other way around since answering all the questions in the bluff game is much harder than in the riddle game. This gives out a maximum for 200 points, exactly.

If you don't agree with giving more "answer all questions" points in the bluff game than in the riddle game, I can agree to the compromise that both games are awarded the same 5 points for that part. This would leave 195 maximum points for the test. You can either leave it like that, which I'm fine with, or award them to "male/female count".

**Comment by kyordhel** [comment]
@balkce I like your amendment.
My only question would be: what about leaving both *answer all questions* in 5 and add a set crowd size (above male/female count) those remaining 5 points. This way teams can correctly state the crowd size even though the ratio is incorrect.

**Comment by balkce** [comment]
Do you mean something like:

correctly state crowd size: `5`
correctly state male/female ratio: `10`

If so, that seems fine to me.

Actually, great, since there isn't much points given to person recognition in this test, and it bleeping has "person recognition" in the bleeping title.

**Comment by johaq** [comment]
I think this is really good change (both to speech and crowd size)

**Comment by kyordhel** [comment]
Done.

**Comment by LoyVanBeek** [comment]
Great fast works guys, but the difference was there because hearing a question from someone behind the robot is more difficult than it being asked directly into the microphone. 

It indeed does seem inconsistent though
