### ISSUE TITLE
SSPL deviation from the "Standard"

### ISSUE THREAD

**Issue by warp1337** [RoboCupAtHome/RuleBook#290]
Dear all,

I was just browsing the rule book (real quick) for a **definition** of a SS(!)PL robot. I mean, the term standard inherently defines that no changes to the robot are/should be allowed, like adding or changing hardware, since this then cannot be considered "a standard" anymore. 

However, I have a specific question: let's assume one wants to implement visual servoing. In order to do this one could take a shortcut and place ar-markers (i.e. stickers) on the robots end-effectors. Is this considered a deviation from the standard? @komeisugiura, @LoyVanBeek

**Comment by LoyVanBeek** [comment]
That is an interesting case, I can't truly judge this, @komeisugiura hopefully can.

My preference is towards a no, but not sure yet.

**Comment by warp1337** [comment]
Thxs Loy. We'll see.

**Comment by komeisugiura** [comment]
We should not accept such an AR-marker. It introduces differences in hardware, which is not based on the standard platform's spirit.

Btw, introducing markers on walls or objects were prohibited in @Home long time ago, which I think is written in the rulebook.

**Comment by warp1337** [comment]
Yes, agree. I read that markers _on walls or obejcts_ are forbidden, thanks for the confirmation again. I was just wondering, thus asking 👍 .

However, to make it clear to everyone, maybe we can include something like:

"In the SPL, changes to the robot hardware are not allowed in order to keep the 'standard' an actual standard. This includes changes to its outward appearance as well. Thus, e.g., ar-markers, stickers or any kind of artificial landmarks on the robot are forbidden."

Again, thank you for clarification.

**Comment by kyordhel** [comment]
@warp1337 
I'm confirming @komeisugiura's statement. Using artificial markers is strictly forbidden since 2009 (Section 3.2.3: External devices). If memory fails me not, having artificial marks in the robot would make it fail the inspection, have its participation in a test denied, or test termination followed by team disqualification from that test.

Maybe is a non-written rule (I saw it in previous rulebook but I can't find it anymore), but OpenCV/QR codes and other types of artificial patterns in robots, walls, floors, furniture, people, etc, have been always considered forbidden and as cheating. In contrast, there is no rule against having one red hand an one green hand in your robot as long as it goes with the robot's amazing fashion style, and not as an evident marker.

**Comment by warp1337** [comment]
Thank y'all. Marking this closed.
