### ISSUE TITLE
[SATTU] Understanding what is missing

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#294]
In "Set a table and clean it up" task, a robot has to place all "missing" objects required for the meal. (ref: https://github.com/RoboCupAtHome/RuleBook/blob/master/tests/SetATableTidyUp.tex#L32 )
My question is that how a robot recognize some objects are "missing"?
To recognize what is missing, he has to know the situation where is completely prepared for meal.
Is there any information provided before the test?

**Comment by furushchev** [comment]
BTW, reference at this line ( https://github.com/RoboCupAtHome/RuleBook/blob/master/tests/SetATableTidyUp.tex#L68 ) is missing (compiled to `??`).
Where should this part be referred to?

![screenshot from 2017-05-24 22 47 02](https://cloud.githubusercontent.com/assets/1901008/26406490/5c05c522-40d3-11e7-93c9-95aebd43efc5.png)

**Comment by kyordhel** [comment]
Ok, let's not over-specify the test. I'm calling upon the Rule Expected Robot’s Behavior in Section 3.8.4. 
What would do you do to address the problem. You will have a delicious steak with some fries for dinner, but in the table there is only the carpet, dish, and a spoon. What is missing?

The ```??``` problem was fixed in d1f1c33 which is pending to merge in #296
