### ISSUE TITLE
[SATTU] Question about task variation

### ISSUE THREAD

**Issue by ytbilly3636** [RoboCupAtHome/RuleBook#298]
I have some questions about the task variation in Set a table and clean it up.

In the example of 6.4.4.7, options are only foods like cereal and milk, sandwiches, ... etc.
My first question is that can the team designate not only foods but also cutlery and other appliances as options?
For example, will following options be allowed?
_option1: cereal, milk, spoon, bowl, napkin and dish.
option2: cereal, orange juice, cup, spoon, napkin and dish._

My second question is that will serving objects less than 6 be regarded as end of serving?
For example, assuming that the robot serves cookie. When we eat cookies, we do not usually use cutlery. Thus he judges that only milk, cup and dish are needed and serves them. And then he says "That's all."
After the situation, will operator change the positions of 2 objects and request the robot to clean up the table?

I would be grateful if you could answer my questions.

**Comment by kyordhel** [comment]
1. The answer is no. Typically you **don't** specify cutlery when specifying food; either you say what is going to be served or which utensils set. The exception is when you have extraordinary situations, like a family member that rather likes spoon/chopsticks over a fork, but fo ease we are not having these situations (yet).

2. Options will be handled differently. If you are requested for cookies and milk (something very unlikely), you may address the problem in several ways after placing the glass/cup/mug, dish, and napkin:
- Pour the milk in the glass/cup/mug (I would count that at least for 2 objects, or even outstanding performance).
- Place 3 cookies on the plate (outstanding if you get them from the box).
- Place the box of milk and the box of cookies (scoring only for 5 objects).
- Place the box of milk, the box of cookies, and a fork, because Jimmy eats cookies with a fork.

**Comment by LoyVanBeek** [comment]
@ytbilly3636 are your questions fully answered?

**Comment by ytbilly3636** [comment]
@kyordhel @LoyVanBeek Thank you for your answer and your confirmation. My questions are almost solved.

I would like to confirm whether the robot can continue the task even if the robot serves less than 6 objects or not. 

Regards

**Comment by kyordhel** [comment]
As long as the robot clearly announce what is it doing, I'm fine with that.

Regarding your specific question, robot may say something like:

> _I have finished setting the table. Please say «robot, clean the table» when you want me to start cleaning _

In that very moment, the first part of the test is considered as completed, and referees will cooperate with the robot so it can finish the test regardless how many objects it has placed on the table.
