### ISSUE TITLE
Question about Speech and Person Recognition 

### ISSUE THREAD

**Issue by MasatakaHisano** [RoboCupAtHome/RuleBook#300]
A question about rule book(Last Build Date:May 24, 2017 Time:979)
I have some question about "Speech and Person Recognition".

About p62 5.4.3 Task
・When "Wainting and turn", how long can robot watch the crowd to find the crowd?

About p94 A.1.4 Object Questions
・In this chapter question No.9, this example has concrete information.
However, we can answer this question with "Yes" or "No".
So if robot answers like this question with "Yes" or "No", can we get score?

**Comment by kyordhel** [comment]
### Timing:
1. Robot waits 10 seconds before turning and start searching.
2. The robot must take a reasonable amount of time to analyze the crowd (e.g. group picture time). Although there is no hard timing imposed, this operation should take no longer than 30 seconds (See *Inoperative Robots* in 6.1.3 paragraph 8)

### Anaphora resolution 
Relating Appendix A Section 4, Example 9: *Do they belong to the same category?*. Yes, the robot can answer yes or no, but this will be considered as not answering the question since a simple *yes* or *no* has 50% chances of success and does not demonstrate neither that the robot understood the question, nor the question was answered. The robot must make clear it has *understood* the question.

**Comment by balkce** [comment]
It's important for the robot to answer the question in a manner that makes it clear it understood the question. A "yes" or "no" answer is in my opinion not clear.

An answer such as "Yes, the shampoo, soap, the sponge and cloth all belong to the category of cleaning stuff.", or "No, the shampoo and soap belong to the cleaning stuff category, while the sponge and cloth belong to the utensils category."

Like mentioned in other issues, anaphoric questions are difficult to resolve, but in this way it is clear to everybody (judges and attendants alike) that the robot understood the question and the context it implies.
