### ISSUE TITLE
Q: Object distance and placing in Storing Groceries

### ISSUE THREAD

**Issue by YoshiyaAratani** [RoboCupAtHome/RuleBook#301]
Hello there.

We have some questions in storing groceries.

1. Are these objects put on close like Figure 5.4?(If these objects are put on like this, we think it's different from general rule.)

2. We want to ask about “Successfully placing an object anywhere else” in the storing groceries score sheet.
Can we get its score when robot put on Unknown objects only?
Can we get its scores with “Successfully placing an object near to another of the same class” scores  when robot put on known objects or alike objects?

Regards.

**Comment by kyordhel** [comment]
I'm not sure to understand your questions, so I'm rephrasing.

**Q1:** Will the objects in the cupboard be placed as close one to each other as Figure 5.4 depicts?
**A1:** Probably. Existing objects will be together, close enough to look like a group, but leaving enough space for placing objects close to them (e.g. in the back of the shelf, so new objects can be placed in front, or with enough space in one side). Remember that the robot does not need to grasp the objects in the cupboard.

**Q2:** How *Successfully placing an object anywhere else* is scored?
**A2:** The cupboard has all kind of objects (known, alike, and unknown) grouped by likeliness and category. The robot must inspect the cupboard and the groceries in the nearby table, then move the objects in the table to the cupboard, placing them as closest as possible to the objects of the same category or sharing common properties. If the grasped object is different and unrelated from the other objects in the cupboard, it must be placed in a free space (anywhere else).

For sake of an example, lets say the cupboard has:
- One coke and a bottle of milk (beverages),
- one apple and one banana (food), and
- one pair of *res extensa*.
On the table there is a pear, a beer, some snacks, and two bottles of pills. It is expected that the robot place the pear with the apple and the banana, and the beer with the milk and the coke. However, the bottles of pills present a different challenge. The robot has two options:
1. place the pill bottles next to the *res extensa*
2. place the first pill bottle in a free space in the cupboard, and the second pill botle next to the first one.
Choosing option 1 scores as *Successfully placing an object anywhere else* since the bottles of pills are not similar to whatever *res extensa* is. However, choosing option 2 grants full scoring (*Successfully placing an object near to another of the same class*) since the robot has started a new category for unknown objects sharing a common property: being bottles.

**Comment by YoshiyaAratani** [comment]
Thanks to kyordhel.

>Q1.
Our robot can recognize objects correctly when you put objects depending on general rule.
In Figure 5.4, it looks not depending on general rule. Will objects be put on like this Figure?

>Q2.
Our question is does the “Successfully placing an object anywhere else” score overlap? 

and new Q3.
In storing groceries score sheet, how can get 320 point?
Please tell me how to calculate it.

Regards.
Hibikino-Musashi@Home team Yoshiya Aratani

**Comment by kyordhel** [comment]
@LoyVanBeek you have more experience than me decrypting that scoresheet.

**Comment by kyordhel** [comment]
@YoshiyaAratani Please open a new issue for each different question [following this guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Questions)
