### ISSUE TITLE
Questions about “Set a table and clean it up!”

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#309]
I have some questions about this test:
1.- In 6.4.3, the section Part I.2 
In the task description of the Part I (Setting up the table) the subsection  2 “Setting the table” states that the robot must place all objects required for the meal. Is it mandatory for the robot to grasp and place all the six objects before proceeding with the subsection 3 “Serving the meal”? Or is it possible for the robot only grasp and place some objects (for example only the easy-to-grasp objects) and proceed with the subsection 3 “Serving the meal”? Is it possible for a robot to skip directly the subsection 2 and proceed to serving the meal? 

2.- Suppose that a team provides as custom food a box of cereal and a bottle of milk. 
Where will the box of cereal and the bottle of milk be at the start of the test? In the table or in the food rack? If they are placed in the food rack, are they considered part of the six objects to grasp and place of subsection 2? 
Can the team provide also the bowl where the cereal will be served? If the answer is yes, where will the bowl be at the start of the test? In the table or in the cupboard? If it is placed in the cupboard, is it part of the six objects to grasp and place of subsection 2?
Must the robot open the box of cereal and the bottle of milk? Or is it allowed to provide open objects (for example, a bottle of milk without cap or an opened box cereal?

**Comment by LoyVanBeek** [comment]
Also, see https://github.com/RoboCupAtHome/RuleBook/issues/298

**Comment by kyordhel** [comment]
### 1
Duplicated. It is explained in #298 as @LoyVanBeek just pointed out.

### 2
#### 2.1 Custom objects
**Teams can't provide custom objects for setting the table**, they just provide a custom meal (what the robot can actually serve). You may say: robot can serve cereal and cookies, and the referee will ask for cereal and cookies but nothing stops them for asking also for an apple. You may also say that the robot can prepare a sandwich, so the referee will ask for a sandwich. In contrast, teams are allowed to **provide a custom bowl**, as well as cooking utensils (e.g. special knife for spreading the butter on the bread, which is not the knife that will be placed on the table).

#### 2.2 Custom bowl location
Rule *Object (category) locations* in 3.2.5 states that each category will have a predefined placement. This includes the bowl (container). As you will be providing a custom bowl, it will be used instead of the official bowl and having the same default location.

#### 2.3 Number of objects to move
The robot needs to inspect the table before moving objects. If the bowl is already there, it doesn't count as an object. If the bowl is not there, it does count. There won't be objects in the table that need to be set in the table.

#### 2.4 Opening boxes/bottles
Is Ok if the cereal box or bottle of milk is already open. It is also Ok if the robot uses a jar for doing it (they would count as custom containers, but not as moved objects).

**Comment by kyordhel** [comment]
Since there was no more feedback in 9 days, I consider this question as answered.
