### ISSUE TITLE
Finalization of Speech and Person Recognition test

### ISSUE THREAD

**Issue by mtlazaro** [RoboCupAtHome/RuleBook#310]
Hi,

we have some question about the finalization of the task "Speech and Person Recognition".
The rulebook says "The robot leaves the room through the designated door", however no points are awarded for this navigation task. 
Furthermore, it says "This test may also be held outside the arena" so in that case there will be no doors.
How to finalize this task is incoherent in our opinion, especially since the focus is speech understanding and not navigation.

**Comment by LoyVanBeek** [comment]
Navigation is such a basic task that no points are awarded in this task for that. No penalty or whatever is given if the robot is not able to do it, it is mostly an inconvenience to the next team coming up.

**Comment by kyordhel** [comment]
Is not incongruent, but maybe nor properly explained. The point is there because, in case that the test is held in the arena (most likely), the robot **must leave autonomously**. It gives a terrible impression to the audience to see robots being dragged or pushed outside, so this requirement is only there to make the test more appealing.

However, if the test is not held in the arena (something possible but undesirable), there is no audience, so no need for appealing behavior.
