### ISSUE TITLE
Storing groceries: predifined location, finding the table, and difference between category and class

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#313]
Hello,

I have the following questions about the Storing Groceries task:

1. Why is it required to announce the startup location for robots two hours before the execution of this task? It would be more natural that the referee indicates a random position in front of the cupboard as has been done in previous occasions. The current conditions favor robots that can handle opening a door in an open loop. This should be prevented by:
- Having an initial random position
- Specifying the door's handle in a bounding box within the recognition report. So it can be certain that the robot saw the handle in order to grasp it and open the door.
2. It is unclear in item 3, in section **5.5.4 Task**, whether the position of the table is known in advance or whether the robot must find the table dynamically. This should be clarify.
3. What is the difference between class and category? Is a category the mother of a class as suggested by the last two examples of the _Recognizing unknown objects_ action of the section **5.5.9 Score sheet**?

Regards,
Noe

**Comment by kyordhel** [comment]
I see here 3 issues.

### Startup location
For several reasons
- Because teams need to know if the test will be held in the arena or not.
- Because teams need to know in which room would be held.
- Because teams need to know which shelf will be used for training.
The exact location is not provided, and the robot needs to move between the start position, the table and the cupboard. If a robot can open the door using open loop, they deserve the points because they opened the door, although in my experience, is impossible in @Home to solve the door problem using ope loop.

### Table-Cupboard layout ambiguity
The position of the table is not necessarily known in advance. Common sense is used. If a table is naturally close to the cupboard, that table will be used. If the default arena layout has no table close to the cupboard, a table must be placer nearby. In the second case and when the test is not held inside the arena, the robot must look for the table. Rulebook is unclear because robots need to adapt to their environment to solve a task.

### _Mother of a class_
Objects are grouped in Categories and each category has a default location, this information is given and is part of the robot knowledge. Class, kind, type, likeliness, etc., are words to define that a group of objects share common properties but does not necessarily belong to the same category.
- Apple, pear, banana may belong to the _Fruit_ category.
- Paprika, noodles, mayo, and bread may belong to the _Food_ category.
- Coke, milk, and beer may belong to the _Beverages_ category.

We consider that:

- Red and a green apples are both of the same type: alike Apple objects.
- Red and a green paprika are both of the same type: alike Paprika objects.
- Red apple and red paprika are not of the same type, nor they belong to the same category.
- Apple is not _Food_, but _Fruit_. They belong to different categories.
- Apple, paprika, and coke may belong to the custom class Red.
- Mayo and milk may belong to the custom class White, but not to the class box.
- Coke and beer may belong to the custom class Can, although they both belong to _Beverages_.

All this issues are easily solved if instead of thinking how to score, one advocates to the problem of arranging the groceries in a shelf. This is something people can do even with products they have never seen before in their lifes.

**Comment by tkelestemur** [comment]
Regarding to start position of the robot: Can we assume that robot is in a distance where it can place objects into shelf? I'm asking because it is not certain that if robot needs to recognize and localize the shelf like table.

**Comment by LoyVanBeek** [comment]
Most likely, the robot must move a little bit to perform a grab or place from either the table of shelf. 
We'll announce beforehand where the robots and table will be placed, roughly.
What we will certainly not do is mark to the centimeter where each robot is going to be put. It will be roughly the same for every robot and their manipulation reach varies so moving to an optimal pose is likely to be required.

**Comment by nohernan** [comment]
Thanks for your reply @kyordhel I'd like to point out that in this year’s Mexican @Home competition a team presented a demo in which a robot was sent to a previously defined position in front of a table with a drawer, opened the drawer and placed an object within it successfully, as far as we know an open loop was used to perform such a demo. Also, in last year’s robocup@Home competition in Leipzig, a team showed a similar demo in which a robot was sent to a position in front of a door, opened it, and proceeded to the next room where it also opened a drawer and placed an object successfully within it, this team didn’t show evidence that the robot saw the handles of both the door and the drawer. Getting the robot to a designated position is difficult but it can be done, at least in @Home scenarios. In general, manipulation by an open loop is possible once the robot is in a predefined position in front of a door or drawer if the environment is fixed, just as in the production lines that use this strategy.

Also, as you say in relation to the Table-Cupboard layout ambiguity, the robocup@Home competition encourages robots to adapt to the environment to solve a task, fostering unnatural scenarios with the purpose of exploiting particular abilities of the robot in order to score points should be avoided. However, regarding the opening of a door by a robot, your remark that points should be awarded even if the robot uses an open loop is against this spirit. When opening a door/drawer, robots should give clear evidence that they see the handle used during this action.

**Comment by kyordhel** [comment]
Whether a robot uses closed-loop, open-loop, or fruit-loop to open a door matters not as long as it does it autonomously. I've lost track of how many doors I've opened in my life without looking at the handle/knob, because is irrelevant. The test requires the robot to open a door to place groceries inside, we want the door to be open and the groceries properly arranged the same we will want the milk inside the fridge regardless how the robot opened and closed the door.

As I can't find any question pending to be solved here, I am closing this issue, trusting that team will understand that in @Home we want useful robots doing practical stuff.
