### ISSUE TITLE
Q: Are there any difference between OPL and DSPL in Speech and Person Recognition?

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#329]
We can see the following context at 5. Blind man's bluff game in 5.4.3 Task;

P62[DSPL] The game will end when the  10th question has been made, following a “similar” distribution of questions as in the riddle game.

P63[OPL・SSPL] The game will end when the 5th question has been made, following the “same” distribution of questions as in the riddle game.

The two sentences use different words: "same" and "similar".
Are there any difference between OPL and DSPL?

**Comment by kyordhel** [comment]
Please follow the [guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Questions)

**Comment by kyordhel** [comment]
While leagues answer 5 questions in the riddle game, this is not the case in the Blind man's bluff game.  In the one hand, OPL and SSPL robots are required to answer **5** questions using *360°* sound source localization. On the other hand DSPL robots are required to answer **10** questions using *150°* sound source localization. Since DSPL is answering twice as much questions, the distribution is not the ***same***, but ***similar***.

Domestic Standard Platform Robots (Toyota HSR) can't perform 360° sound source localization according with audio experts. Therefore, the test was modified to balance the scoring among the leagues.
