### ISSUE TITLE
Q:  What are considered "pairs" of unknown objects in SG? 

### ISSUE THREAD

**Issue by Michiemi** [RoboCupAtHome/RuleBook#331]
Which pairings are allowed and can one object have multiple pairs?

Pairing based on class:
Example:
Papaya_Fruit paired with Papaya_Fruit

Pairing based on category:
Example:
Apple_Fruit paired with Papaya_Fruit

Pairing based on the similarity of the features:
Example:
![pairing](https://user-images.githubusercontent.com/29573004/27373257-e47da146-5667-11e7-88f9-63bdc1f36d97.jpg)

**Comment by kyordhel** [comment]
First two are correct. It is up to the robot to decide which pairing to apply to give consistency to the results in order to provide a human-like arrangement.

The third, based on features, is quite tricky and needs to be justified.
- **Color pairing:** *wrong*, as the objects does not have the same color (plus, humans don't sort groceries regarding color as they do with clothes).
- **Size:** *wrong*, for humans consider size when stacking but not when categorizing.
- **Affordance:** *right*, for both objects are (liquid) containers
- **Inferred function:** *right*, since both are kitchen appliances (you would need to specify what function).

**Comment by Michiemi** [comment]
Thank you for the quick response.

In specifying the functions, how specific should the labels be?
Example:
Object A is a Fruit but labelled as Food or Edible instead.

**Comment by kyordhel** [comment]
The important thing, unles @LoyVanBeek, @swachsmu, and @balkce have something different to say, is that the report must be human-readable in an easy and straightforward way.

You may label things with short labels (in bold) and later provide further details, for instance:
- Group 1
  - **```apple 1```**```       ( Fruit   : Edible )```
  - **```apple 2```**```       ( Fruit   : Edible )```
  - **```pear 1```**```        ( Fruit   : Edible )```
  - **``` unknown 4```**```    ( Fruit   : Edible )```
- Group 2
  - **```paprika 1```**```     ( Food    : Edible )```
  - **```frosties 1```**```    ( Food    : Edible, Pourable, Box )```
  - **```chocoflakes 1```**``` ( Food    : Edible, Pourable, Box )```
- Group 3:
  - **```unknown 1```**```     ( Unknown : Bottle )```
  - **```unknown 2```**```     ( Unknown : Bottle )```
- Group 4:
  - **```unknown 3```**```     ( Unknown : Box )```

**Comment by LoyVanBeek** [comment]
First of all, the pairing should make sense. This test is focused on manipulation and object recognition, I don't care so much about the ontology of those objects. 
Lots of things are edible (if you chew hard enough :smiley: ). As for categories, I'd say to stick to the categories assigned by the referees (Each object belongs to a category and each category has a default placement location in other tests.)
