### ISSUE TITLE
Q: [Restaurant] Asking a barman after noticing a call

### ISSUE THREAD

**Issue by kochigami** [RoboCupAtHome/RuleBook#333]
Can a robot ask the barman whether it may go to take an order each time when detecting a client's calling?

In the rulebook p. 80 (6. 3 Restaurant/ 6.3.3 Task/ 2. Calling), it is said that "In case both robots notice the same call, the Professional Barman will tell one of the robots to take the order. "
My question is different in that a robot does not wait for the order from the barman.
In addition, it asks for a permission every time it detects the call.
That is because avoiding a mistake and keeping safety.

example:
situation: client is calling.
robot: "I found a client calling. The client is right side from me. Barman, could I go and take the order?"
barman: "Yes."
=> robot goes to take the order.
barman: "No."
=> robot waits.

**Comment by kyordhel** [comment]
I would find annoying that my robot requests my permission before proceeding to take an order (I would pack it and send it back to the factory). @LoyVanBeek what do you think?

**Comment by balkce** [comment]
I know I'm not in this discussion, but I had a five minute break. My two cents:

Considering that there are going be two robots picking up orders, isn't this a possibility of what the rulebook is expecting from the robot?

"In case both robots notice the same call", how would the barman know? Common sense dictates that he will know because the robots told him so. Ala: "barman, I see a user".
"Barman will tell one of the robots to take order." The organic second step of the preceding one, which I find compatible with this part, is that robot asks for permission: "barman, I see a user" -> "do you want me to take the order?"

Another way that the barman would know that the robot noticed a call is that it took the initiative and started approaching the user to take the order without any permission. However, I would find it odd to have the barman chase the robot to tell it to stop if the other robot also took the initiative.

PS. I struggled really hard to not type "batman" instead of "barman" in this entire post =P

**Comment by LoyVanBeek** [comment]
The idea is indeed to have the robot ask when it sees a call, every time it does so (assuming it not te be annoying through because it asks every 0.5 seconds). 

The example sketched is indeed what I have in mind. 

PS. I'd love to do this 10 robots in a row and ***all*** going to the person at once. Mayhem!

**Comment by kochigami** [comment]
@kyordhel @balkce @LoyVanBeek 

Thank you very much for your comments.
These really helped me, and made me laugh ;)
