### ISSUE TITLE
Q: [Restaurant] Definition of infering a bar side

### ISSUE THREAD

**Issue by kochigami** [RoboCupAtHome/RuleBook#334]
If a robot asks a barman whether the bar side which a robot inferred is correct or not, can we still get  five point? 

In p. 83 (6. 3 Restaurant/ 6.3.6 Score Sheet), it is said that "Infer on which side the bar is" is five point.
In p. 80 (6.3 Restaurant/ 6.3.3 Task/ 1. Start), we can see "The location of the tables is not taught to the robot via some training phase".  
I think it is important for a robot to know the correct direction of a bar in the situation that a robot does not have a map for the first time.

example:
situation: Robot searches for a bar kitchen. It finds a bar on right side.
robot: "I found bar is right side from me. Barman, is it correct?"
barman: "Yes."
robot: "OK. Bar is right side."

barman: "No."
robot: "OK. Bar is left side."

**Comment by kyordhel** [comment]
This is an incorrect approach since the bar might be in front of the robot, or not be at all nearby. Left and right are not the only possibilities.

Regarding Barman-robot interaction, all HRI are allowed as long as they are natural (team won't be allowed to instruct the barman). The following dummy scenario is possible:
- **R:** ```Barman, is the bar the table on my right?```
- **B:** *No.*
- **R:** ```Could you point please to the bar so I can find it?```
- **B:** (Points at the bar) 
- **R:** (Navigates towards the bar) ```Barman, is the bar in front of me?```
- **B:** *Yes, it is.*

**Comment by kochigami** [comment]
@kyordhel
Thank you very much for your quick reply.
This example really helped me.
