### ISSUE TITLE
Q: [Restaurant] Bypassing navigation failure at restaurant

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#335]
In restaurant task, since (almost) real environment are used (walking pedestrians along side robots, map is not given, many objects are located, robots can collide each other and so on), it's much harder to navigate in such an environment than other tasks.
If robots lose their way and they recognize that they lose, can they ask people around to help them with navigating to a goal?
Or it means the end of test?

Thank you very much in advance!

**Comment by kyordhel** [comment]
Robots are allowed to communicate and request help from people in their surroundings at any time, and people (most likely) will be willing to help. If a robot has lost track, it may well ask for assistance (although that's something never happened in the past).

Remember that the robot has 30 seconds to actively do something (spinning around trying to localize itself is not considering as doing something), reason for which the referees tend to finish the task at most 30 seconds after the robot lost track of its position, because often robots crash on something rather than localize themselves.

**Comment by furushchev** [comment]
@kyordhel Thank you for very rapid response! OK, that sounds very natural and reasonable.
