### ISSUE TITLE
Q: Can a robot has it own object tray? label: "General Rules"

### ISSUE THREAD

**Issue by fandrade9** [RoboCupAtHome/RuleBook#336]
I would like to know if a robot can have it own object tray as a part of his main structure.  The idea is to move multiple objects at the same time in a single navigation action (e.g. from the rack to the table).

Thanks
btw: I could't find how to add labels

**Comment by LoyVanBeek** [comment]
Yes, this is totally possible. 
For example, see https://youtu.be/3jmsFmXzyzk?t=2m2s

Please do show us the custom thing to us in Robot Inspection though. 

BTW: you can add labels with the button on the right side. If you don't see them, perhaps it's a rights issue and I can maybe only do it because I'm admin. I added a label for you

**Comment by fandrade9** [comment]
Thank you!
