### ISSUE TITLE
N robots parallel storing groceries. 

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#347]
At the back wall of the arena, have ca. 5 shelves and tables and all robots starting at the same time. 
When done, robot closes the door and the time stops. 

Fastest robot can have a speed-bonus. 

This does need a lot of referees though, though the reports help. 

For the audience, I think this can be more engaging, as there is bound to be more action at any time.

**Comment by moriarty** [comment]
I would like to see more tasks with multiple robots in the arena- especially with the increasing number of teams.

One concern, is that this is not a situation which is going to occur in a home- mutliple robots competing for space- But in a home, a robot should be accomplishing tasks while humans walk around and do whatever they're doing... so in that sense the other robots represent humans.

Now- This would require very strong navigation for all teams involved, which we want to see. But I suspect that if there would be a collision, then we would have arrive at a situation where teams may blame each other at who was at fault and who gets points vs who receives penalty etc... So that needs to be addressed in the rules.

If there is a robot robot collision- then both teams get penalty? both teams get e-stop, and if teams want to perform well and they think they have the best navigation, then it is in their interest to share this navigation solution so that other teams do not crash into them... :smile:

**Comment by kyordhel** [comment]
Fortunately, it seems to me that the number of teams won't increase next year. Qualification will be harder than ever.

I think this is feasible for Stage 2, having one robot serving breakfast while other is doing the bed, and so on. Another achievable thing is that teams that don't make it to Stage 2 can continue repeating tests to score more and change the final ranking. An award can be granted to the best 1st stage team

**Comment by swachsmu** [comment]
I agree to Loy. Especially for the first stage, I would like to see more robots in the arena. This will be much more fun for the audience and has more character of a competition.
Storing groceries is a good example where it works without interferring robots. If we have more robots we also could give them more time to do something. I would like a scheme where a robot is out if it does nothing useful (trying to grasp something, but slightly missing the object would still be useful, but just looking at objects without doing anything for more that 2min would not be useful.) Then the audience would also notice which team is probably winning the try because this team is staying for the longest time.

**Comment by swachsmu** [comment]
Here is a second example, where we could have two robots in parallel in the arena. Two robots are starting at different entrance doors (opposite side of arena). Both robots start exploring the arena and do something useful (according to the task). As long as they do some scoring, they are allowed to stay (up to some maximum time). If a robot does not score for time X it has to exit the arena. A new team is allowed to start, while the first team is still finishing its task.
Thus, there is always happening something in the arena. If a robot stays longer the audience sees that the robot is doing well. If there was some problem during a try, it would be possible that the team lineups again and continues testing.

**Comment by kyordhel** [comment]
I agree with multiple shelves with robots each (we did it for OPL) but I don't agree on robots entering the arena in manipulation test. It requires more doors (more than two in a house is unnatural) and might spoil the test if the robot fails entering the arena, a recurrent problem in the past.

**Comment by swachsmu** [comment]
Just to clarify. The scheme with new robots entering the apartment is not intended specifically for the storing groceries test. It is just an idea for a general scheme that might apply to other tests, but has the same effect of having multiple robots in the apartment.

**Comment by balkce** [comment]
We could always use the same door to exit and enter if need be, and use the
official entrance for one set of teams and the official exit (as also an
entrance) for the other.

The start might be a bit awkward since teams should not be standing in the
door to setup, but we could always make the setup area inside the arena
while the first robot is doing stuff. I'm completely fine in the robot be
moved manually to the test area inside the arena.

**Comment by kyordhel** [comment]
No major changes to the rulebook means robots will still start in place. Therefore, the test can run in parallel.
