### ISSUE TITLE
4th "Area" for things

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#348]
This is probably a stretch.

But with 3 arenas this year, and one restaurant area which was unfortunately disclosed before hand... but, it would be nice to have a 4th, "Area". Not an arena, but of similar size, where if the Restaurant is not possible to leave the venue, then at least its more space to re arrange...

For a test like: restaurant or #347 then we could really set up an area without interrupting the other leagues, and without allowing the teams to map or hard code anything. The main issue would just be: a large area with floor that teams don't complain about, no walls, and spare furniture.

**Comment by kyordhel** [comment]
That strongly depends on the venue and LOC. A 4th arena was discouraged by Trustees and 2017's LOC as the arenas were sub-utilized during the competition (see #351). What we need is either redesign the test to make robots use the whole arena, or pipeline tests.

Remember that, due to mapping, having a 4th testing area is pointless if it doesn't look like the arena, with the exception of manipulation and speech recognition. Other than that, teams can test wherever they want within the team area, something that has been done in former years.

**Comment by swachsmu** [comment]
I agree that this cannot be decided without a discussion on the local options that we have. I head from Tijn that in Montreal it might be possible to equip a real restaurant near the site with a WiFi. But this needs to be discussed with the new LOC. In Nagoya, it was great to have the same arena layout for each league, so that we could use only one arena for finals. Additionally, we have the requirement of finding or re-arranging an additional place for doing tests without a pre-recorded map. However, I think some additional space in the team area would be nice, so that the teams can do some testing near their own table.
The external place that the teams do not now might always have some issues for teams regarding the floor, some glas or mirror walls, bad light, what ever. That is just part of testing in the real world.

**Comment by kyordhel** [comment]
Let's address this for 2019.

**Comment by kyordhel** [comment]
We got a 4th arena for Montreal. Hence, I close this.
