### ISSUE TITLE
New Person recognition test: Collect my team

### ISSUE THREAD

**Issue by swachsmu** [RoboCupAtHome/RuleBook#352]
Here is a suggestion for a new person recognition test. It is called "Collect my team". There is a number of persons (e,g, 6 persons) who are distributed in the different rooms of the arena (may be sitting or standing or whatever). The robot has the task to search for people, learn their name, learn how to describe them, and ask them if they want to join the robot's team. The location of first person found by the robot defines the place where all team mates gather. Thus, the robot says to the second person found, something like: "Hey, Caleb! You want to be my team mate? Please look for Loy in near the kitchen table and wait for me there. He is the nice looking guy in the black and orange shirt." In order to find a person the robot may also enter the room and ask: "Is anybody there?" and Caleb might answer "I am here!!!" So that he is easily found by sound localization. If the robot has collected, e.g. 3 persons, it is going back to the location of the first person and takes a look if all team mates are there. If someone is missing, the robots states: "Oh, I see everybody is here, except Dirk. Here might have to do some more important stuff."

This test could even be extended to going outside the area and getting more team mates. And it would be possible that two robots in parallel are searching for team mates. The audience could directly see which robot has collected more team mates.

**Comment by kyordhel** [comment]
Just to clarify, we would remove all person recognition from the speech test (something that makes sense, because the current one feels like a patch), right?

I like this test, although the rulebook shouldn't change much this year (still not sure how much is too much). In fact, @swachsmu, I think two robots at the same time is the best because then the robot needs to keep record of who rejected the invitation and also deal with rejections. 

This is also compliant with the idea of non-linear, non-scripted tests in which the robot has assigned a set of goals instead of a serie of goals.

**Comment by balkce** [comment]
I like this. It's complete chaos, and the robot needs to make sense of it
all. At the end, I don't care how it does it, if it has obtained a minimum
of team members.

**Comment by LoyVanBeek** [comment]
Thnx @swachsmu :-)
Seems like a perfect task for a Pepper at work in an office environment, to gather people for a meeting. 

Can we explain this task in terms of GPSR commands?

**Comment by kyordhel** [comment]
@airglow, @awesomebytes, @HideakiNagano21, @justinhart, @mnegretev, and rest of TC: your thoughts, comments and proposals, please. We also need a volunteer to write the test.

**Comment by johaq** [comment]
Closed. No more test changes for this year.
