### ISSUE TITLE
Release of Score sheets

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#355]
It would be nice to analyse the change of performance over the last years. For that we would like access to the detailed scores of the past events.

Can the TCs release the (anonymised) scores. Or processed data?

---

In the ongoing open discussion about the rule book changes for the next event, some team members are wondering if the performance is going down over the last couple of years?

As the rule book changes over the years it is not possible to compare total scores of the individual skills of the robots e.g. object recognition rates, impact of restarts etc.

The data would surely help making informed decisions.

**Comment by LoyVanBeek** [comment]
It would indeed, but unfortunately, the scoresheets are currently entered on paper (I know, this sounds ridiculous but is handy for quick additional notes as well). 

Digitizing them is quite the job and I don't have the physical scoresheet now as I'm back home.

This is another +1 for digital scoresheets.

**Comment by kyordhel** [comment]
### Open Scoresheets
Regarding previous score sheets, those are kept secure by the EC, not by the TC. TC has no access to any scoresheet after the competition. In my experience, analysing them is almost useless since there are plenty zeroes and the score sheet does not tell you whether robot failed to start, never tried at all, failed while attempting, succeeded cleanly, or successes with a cynical (yet valid) hardcode. 


### Automating score sheets.
This requires a significant amount of work. The OC will accept volunteers to develop a web app for scoring the next Rulebook (if suitable) once the final version has been published and only if this is published 2 months before the competition. 

As side note, after refereeing OPL alone in a couple of tests, I'm pretty sure I won't do that in any app/interface. There are many notes to take during the tests, and nothing outperforms the efficiency of pen and paper for this purpose.

**Comment by kyordhel** [comment]
@LeroyR Now I can properly answer your question.

Measuring the performance by checking the scoresheets is not a good strategy. Points are meaningless outside their context, and scoring more in a more challenging rulebook does not necessarily means that performance has increased, but that maybe rules had gaps and were exploited. Therefore, a quantitative-only evaluation would be very tricky.

Let's go with a qualitative one. Please take a look to the media section in the official website:

https://sites.google.com/a/robocupathome.org/robocup-home/media

I advise you to see the videos of the winner team chronologically (start with 2011). After watching those videos, you will have a much richer experience on how the performance has changed over the years.

**Comment by LoyVanBeek** [comment]
Specifically: scores can mostly only compare scores of the same year. Some stuff is getting easier for the robots, thus they yield less points. Doing more difficult tasks gives you more points.
