### ISSUE TITLE
[DSPL] Official Standard Laptop for Toyota HSR (Ethernet wired)

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#366]
Deadline: **Sunday, October 29th, 2017**

To the DSPL community:

In response to your demands for a better juice extractor for the sensors of the HSR, the Executive Committe has decided to authorize the use of a **standard laptop** connected to the Toyota HSR via Ethernet cable, and located in the *TOYOTA HSR Backpack* provided by TOYOTA for this purpose.

The EC thinks it must be the DSPL community who provide the technical specifications of such laptop, as well as at least two commercial options. Requirements are as follows:

- Available worldwide
- Budget friendly
- Dimensions:
    - Maximum height: 430mm
    - Maximum width: 430mm
    - Maximum thickness: 48mm
    - Maximum weight: 5.0kg
- Software
    - All its components must be Linux compatible.
    - Same ROS version as the HSR 
- Laptop must fit in the backpack.

Other than that, there are no limits. You choose the rope, we hang you with it.

The EC will choose one of the proposed laptops as a Official Standard Laptop for teams to use during the competition. During the Robot Inspection, the OSL will also be inspected. No additional hardware will be allowed, including, but not limited to: battery, RAM, hard drives, SSD drives, USB devices, wireless cards, adapters, antennas, etc. Random checks might be done by the TC/OC/Referees at any time during the competition.

We are looking forward to read your proposals in this issue or in the OC mailing list.

**Comment by tkelestemur** [comment]
It is great to hear this! Our major problems in Japan 2017 were because of the lack of computational power on the HSR. 

As Team Northeastern, we propose System76  Oryx Pro as the OSL. It is a Linux oriented brand and comes with Ubuntu installed. Some features:

- Thin aluminum alloy design
- NVIDIA GeForce GTX 10-Series GPUs
- 15″ or 17″ matte display
- HiDPI and IPS display options
- Up to 64 GB of memory
- Affordable

For more information : https://system76.com/laptops/oryx

Only disadvantage is battery life, but given the computational power on the laptop that is understandable.

**Comment by justinhart** [comment]
I can get behind this. This is reasonably-priced and quite nice.

**Comment by moriarty** [comment]
Popular choices here in Germany are Tuxedo Computers, and Schenker.

https://www.tuxedocomputers.com/index.php
https://www.mysn.de

They were the official hardware sponsor for RoboCup 2016 in Leipzig, for the simulation leagues.

**Comment by kyordhel** [comment]
Maybe I didn't made myself clear, so here some clarifications.

### We need technical specifications
Within a reasonable price. Something you will actually use and keeps reliable for at least two years, and also affordable for anyone. If you don't need more than 8G RAM, or you don't need Cuda, don't ask for it (external devices via wireless and cloud services will still be allowed).

We don't need to know whether certain laptop can be upgraded up to 2TB SSD, Intel Xeon E3-1575, 64GB RAM, and nVidia Quadro M5000M 8GB for just €7560.- like the Lenovo P70 because, to be fair, not all teams will be able to afford it. What we need is the list of minimum requirements for the core software (lightweight version in case of no wireless) to run smoothly in your robot. Something like: Intel i5 2GHz+, SSD 128G, 8GB RAM, with preferrably nVidia GTX 860M. Candidate: Dell Inspiron 15 7566.

Keep in mind that **all participating teams will be required to purchase this laptop**.

### Available worldwide
Maybe I must have stressed the point that the candidate computers need to be **available worldwide**, including, but not limited to:
- Australia
- Brazil
- Canada
- Chile
- China
- Europe
- Japan
- Korea
- Mexico
- USA

## Why?
Because EC will review your options (they are not going to research availability, pricing, etc) and choose two that will be made official. If you are not careful with the price, specs, and availability, you might be jeopardizing and probably spoiling your participation at the competition.

**Comment by SJ-YI** [comment]
I strongly suggest Clevo barebone laptops, which is available worldwide with various brand names. **Actually the system76, Tuxedo and Schenker _ARE_ Clevo laptops, just with different brand names**. (Check here: https://en.wikipedia.org/wiki/Clevo )  

Personally I've been using P770ZM model (17 inch screen, i7-4790K 4.2Ghz Desktop CPU and 980m GPU) during DARPA Robotics Challenge and had no issues so far. Another bonus is that unlike most laptops it does not use Optimus GPU switching technology, which makes linux setup exactly the same as desktop machines. 


For upcoming RoboCup, I have two recommendations:

-**15 inch version (Clevo P750TM1-G)**: 15 inch screen, 390*265*35mm, 3.5kg, CPU choice from **i5-8400 to i7-8700K**, GPU choice of **NVidia 1060/1070**, price starts from $1600 and is around **$2100 for i7-8700K /16GB Ram / GTX 1070 / 960 evo 250GB SSD** 
Link: https://www.avadirect.com/Clevo-P750TM1-G-15-6-Core-i7-NVIDIA-GeForce-GTX-1070-G-SYNC-Graphics-Gaming-Laptop/Configure/11560230

-**17 inch version (Clevo P775TM-G)**: 17 inch screen, 418*282*38mm, 3.9kg, CPU choice from **i5-8400 to i7-8700K**, GPU choice of **NVidia 1060/1070/1080**. price starts from  $1700 and is around **$2600 for i7-8700K / 16GB Ram / GTX 1080 / 960 evo 250GB SSD**
Link: https://www.avadirect.com/Clevo-P775TM1-G-17-3-Core-i7-NVIDIA-GeForce-GTX-1080-G-SYNC-Graphics-Gaming-Laptop/Configure/11561114


Personally we plan to use CUDA for the competition, and I think the suggested laptop (especially 17 inch one) is powerful enough to replace external server.

**Comment by kyordhel** [comment]
To ease comparison, please start specifying the list of minimum requirements of your system as follows:

- Processor [type] speed, number of cores [, and caché]
- Minimum RAM [and speed]
- GPU type, number of cores, and VRAM
- Required storage
- Required bandwidth

Then, please specify your recommendations.

**Comment by justinhart** [comment]
I accidentally sent this to TC & EC but not the RoboCup@Home List.

Go for the top-of-the-line Intel laptop CPU that isn't a Xeon since Xeon
machines will raise our budget significantly.
Do the same with Nvidia, and rule out the very expensive lines of GPUs, so,
only GeForce GPUs. Similarly, we rule out SLI.

Look up the benchmarks at cpubenchmark.net. The top of the line Core i7s
right now are i7-7920HQ. Those are expensive since they are the top mobile
CPUs right now (around $5000), so get the one that is in second place, Core
i7-7820HK.
If we apply the same logic to the GPU, we save about $300 by going for a
GeForce 1070 rather than a GeForce 1080.

Dell has global distribution from what I can tell, and sell Alienware
gaming laptops.

These might be good suggestions:

Alienware 17 with i7-7820HK & GeForce 1080 @ $2199.99
http://www.dell.com/en-us/shop/dell-laptops/alienware-
17/spd/alienware-17-laptop/dkcwkblf003destiny

We could push down the specs a bit and save the teams about $470.

Alienware 15 with i7-7700HQ & GeForce 1070 @ $1729.99
http://www.dell.com/en-us/shop/dell-laptops/alienware-
15/spd/alienware-15-laptop/dkcwkblf044s

Not addressed here, RAM, Storage, or network bandwidth.

Intel Core i7-7700HQ and GeForce 1070 should be available in many
affordable solutions.

**Comment by YutaroISHIDA** [comment]
I strongly recommend the following PC for HSR based on our experiences.
 
**DELL Alienware 15
CPU: Core-i7 7820HK, 4.4GHz, 4cores, 8threads
RAM: DDR4 32GB
GPU: NVIDIA GeForce 1080, 8GB
Storage: SSD 1TB
Price: $3,124**
 
**We have the knowledge/know-hows of backpack system for HSR because we built a custom one for domestic competition in Japan.**
Reference: http://www.brain.kyutech.ac.jp/~hma/data/Hibikino-Musashi@Home%20SPL_TDP.pdf
 
We mounted a laptop PC which has no GPUs on the custom backpack system.
In this case, the processing speed of deep neural networks (DNNs) was very slow, ex. it took 4 second per one inference with the GoogleNet.
In addition, I want to use the DNNs library with the CUDA 7.0 or later such as Open Pose.
It can't run on the NVIDIA TX1 on the HSR. 
For this reason, I suggest the NVIDIA GeForce 1080.
 
The capacity of the RAM is one of the important factor to run the ROS system comfortably.
Especially, the Rviz needs big capacity of the RAM.
 
The @Home rule strongly recommended data collection.
I need large storage to save big rosbag for making @Home official dataset.
 
Finally, I note about the weight/size of backpack.
If you mount the heavy items in rear of the HSR, sometime the original API for base control is not work.
In order to avoid this problem, I suggest the Alienware 15 model than 17 model.

**Comment by kyordhel** [comment]
Question @YutaroISHIDA:
For how long can you run DNN processing in the laptop to drain the battery?

**Comment by SJ-YI** [comment]
The Clevo laptops I have suggested can use **i7-8700K HEXACORE DESKTOP CPU** which should be roughly 1.6-2 times faster than current fastest mobile i7 CPUs. They are much cheaper than i7-7820HK or i7-7920HQ too. So if we use them with power supply, they are arguably the most powerful and quite cost effective (even compared to desktops) laptops out there.

However, the big question mark here is the **CPU/GPU performance with battery power**. To my knowledge, most powerful gaming laptops **significantly lower the CPU and GPU clock when unplugged**, for some models as low as to 1/3. In that case, getting very powerful laptop can be totally pointless if they can only use a fraction of its power on battery. 

Another question mark is whether the laptop has **Optimus GPU switching** feature. It makes linux setup considerably harder (I tried everything out there including bumblebee and gave up years ago), so laptops without Optimus is preferable. Fortunately, new laptops with G-SYNC technology do not have optimus. 

So my point here is that **we cannot determine the laptop by spec list alone.** We need to make sure the laptop has no GPU setup issue (Optimus related) and has reasonable performance on battery. 

I just checked the review of Alienware 15 here ( https://www.notebookcheck.net/Alienware-15-R3-Notebook-Review.196584.0.html ) and it seems the CPU clock (3.6Mhz to 2.7Mhz) and GPU clock (1582Mhz to 1151Mhz) gets **roughly 25-30% performance hit** on battery power, which seems to be quite acceptable for me. And it has G-SYNC screen option too, which guarantees that we don't have to handle the annoying Optimus. 

Dell should have a very good distribution chain globally, so I too recommend Alienware 15 with G-SYNC screen and GTX 1070 GPU. It seems it is $1,729 at US dell homepage (i7-7700HQ, GTX 1070, 16GB RAM, 128GB SSD+1TB HDD, FHD screen with G-SYNC)

**Comment by maximest-pierre** [comment]
I know I am from an OPL team but the Dell one seems pretty easy to order. We should also look at the business class laptop some of them already has Ubuntu pre-install (No windows tax). I recently ordered a Dell precision 5520 with Ubuntu preinstalled and the Nvidia GPU already work out of the box. 

The Clevo laptops are also hard to buy in Canada and extremely expensive (Custom taxes).

**Comment by kyordhel** [comment]
@tkelestemur The battery must last at least 45 minutes.
@YutaroISHIDA: How long lasts the battery with your DNN running?
@SJ-YI No cables. The backpack is not intended to replace an external server.
@maximest-pierre here you have LOC super powers. If LOC says Clevo is hard to get in Canada, thats a strong No-Go for EC/TC.

Regarding the **minimum spec list**, the TC and EC must know what are team's **real** requirements to convince Toyota/Softbank of upgrading the robots. I'm afraid that no company is willing to embed a Clevo laptop nor add a high-end GPU (that would overheat the robot and drain the battery too fast).

**Comment by YutaroISHIDA** [comment]
Answer @kyordhel 

**Alienware 15**
Running time with DNNs (Example from Openpose): about 1 hour
Charging time: about 3 hour

**HSR**
Running time: about 1 hour
Charging time: about 3 hour

They have very similar running/charging time.
The management of charging is same as using only HSR.
It's comfortable.

**Comment by okadahiroyuki** [comment]
>I know I am from an OPL team but the Dell one seems pretty easy to order. 
>The Clevo laptops are also hard to buy in Canada and extremely expensive (Custom taxes).
The situation is the same in Japan.
Dell's PC is easily available, but Clevo's PC is very expensive and hard to get it.

I and team eR@sers strongly suggest  as a candidate.
>DELL Alienware 15
>CPU: Core-i7 7820HK, 4.4GHz, 4cores, 8threads
>RAM: DDR4 32GB
>GPU: NVIDIA GeForce 1080, 8GB
>Storage: SSD 1TB
Bandwidth: IEEE 802.11ac
Price: $3,124

**Comment by SJ-YI** [comment]
@YutaroISHIDA  @okadahiroyuki 

If you have the Alienware 15 with 1080 GPU, can you please check the CPU and GPU clock speed under battery power? If 1080 version does not have noticeable performance advantage over 1070, we had better get 1070 version instead (which is much cheaper)

**Comment by okadahiroyuki** [comment]
To the DSPL community:
When will you decide?

**Comment by kyordhel** [comment]
@okadahiroyuki deadline was past October 29th.

Sadly the community response (about 5 of 12 old teams + 9 candidates) has been weak. Making compulsory purchase of a laptop of at least $2000 USD without the commitment of the majority of the DSPL participants would be unwise. Therefore, we can not proceed to authorize the use of any backpack laptop.

So far, the OC and EC have no more interest in promoting the use of a backpack for both SPL due to the lack of response. Whether we will decline Toyota's offer of providing the laptop mounting for the HSR, I know not.

Should the DSPL community still be interested in having a backpack laptop, this must be promoted, organized, and requested by you. A representative can contact the OC in behalf of the DSPL community providing information about the chosen laptop and proof of commitment of most teams to purchase the official laptop with the given specs (and no other one) in case they qualify.
