### ISSUE TITLE
Splitting *Setting a Table and Clean Up*

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#379]
This issue addresses a discussion started by @balkce and @airglow in #369 and #370.

### The idea in a nutshell is:
- Remove the Clean-up part from the *Setting a Table and Clean Up* test (Stage 2)
- Replace the *Storing Groceries* test with either:
  - Filling the Dishwasher (#369)
  - Dishwasher Master (#370)

### Background
At the date of this issue, no team has reached the Clean-up part of the *Setting a Table and Clean Up* test, meaning that the test should be split in order to give teams the means to master the task. In addition, there is an external proposal of having robots filling and operating the dishwasher, reason for which two new tests planned for inclusion in the near future. In this scenario, it would make sense to remove the clan-up part from the *Setting a Table* test while integrating one of the proposed tests that involve cleaning up with some modifications (See #369 and #370).

However, there are some considerations to take into account, for which this decision cannot be taken lightly, as described below.

### Considerations
1. **No-changes policy:** It was decided that this year the changes in the rulebook would be reduced to a minimum, discarding all major changes to allow teams to excel in the execution of the 2016 tests.

2. **Time:** At this point in time, there are 4 tests in Stage 2 and the schedule is tight. Including another test would require about 3 additional hours for testing, which might not be logistically feasible. Please consider that the time allocated for Stage 2 tests cannot be reduced.

3. **Balance between stages:** Adding a new test to Stage 2 (or splitting an existing one) would make a total of 5 tests in contrast with Stage 1 which has only 4. This by all means is not good for new competitors. 

3. **Balance between leagues:** Adding an extra manipulation test requiring a high degree of precision would place the Social Standard Platform League in disadvantage respect to the other leagues.

5. **No previous experience:** Although some tests in the past attempted to address the required skills to deal with a dishwasher, no test directly addressed the manipulation of objects in narrow spaces, positioning of objects in 3D spaces, or manipulation of small/heavy objects (cutlery or pans) as a compulsory skill. Adding a Stage 2 test with no precedent might not be the best of ideas.

### Proposed solutions
There is an scenario that might help to solve the problem, as depicted below:
- Remove the Clean-up part from the *Setting a Table and Clean Up* test, keeping it as Stage2 test.
- Replace the *Storing Groceries* test with Filling the Dishwasher (PR #369) as Stage 1 test.
This scenario addresses considerations 2-5, so the negative impact is minimized. However, it violates the no-changes policy and, as @balkce remarks in #369, story-wise it doesn't make sense to clean first and serve later, so both test should be in the same stage.

Related issues: #361 and #364

**Comment by tkelestemur** [comment]
I don't think replacing Storing Groceries task is a good idea. When you look at the tasks in the challenge, there is a diversity in terms of the requirements of the tasks and the Storing Groceries task is imposing one of the most important aspects of service robots, household object manipulation. Although the proposed replacement is also a manipulation task, I think there should be one task where the robot is required to recognize and manipulate a variety of objects. 

I am speaking for the DSPL so this may not be true for other leagues but there was not much success last year for Storing Groceries last year that is why Storing Groceries should be kept as teams have seen what they can improve last year and they will do better next year.

**Comment by kyordhel** [comment]
@tkelestemur your comment raises some questions:

- How filling a dishwasher does not target "household object manipulation"? Aren't kitchenware, and tableware household objects?
- In the Filling the Dishwasher test, how the robot is **not** "required to recognize and manipulate a variety of objects"? In any case categorization would be missing, but the robot is still required to recognize a dish and place it in the rack, recognize a spoon and place it in the basked, and so on.

In fact, I make use of the dishwasher more often than I arrange groceries in a shelf, which might not be the case for many, but placing tableware in a rack is, at least, as important as storing groceries. Now, if your point is that a Toyota HSR can neither manipulate dishes/pans nor operate a dishwasher, therefore DSPL should stick with *Storing Groceries*, then your comment might not be clear enough.

Regarding the terrible performance in Storing Groceries, that's a strong reason to replace the test.

**Comment by tkelestemur** [comment]
@kyordhel 
* Kitchenware and tableware objects are a subset of household objects. I think it would be better if the robot is tasked to grasp objects like apples to bread, not just cups and plates. 
* I agree that same sort of pipeline will be used for Dishwasher test but as I mentioned above, the robot will be manipulating a subset of the household objects which I think is not a good idea for generalization of the grasping pipelines. The algorithms that we deploy on the robot should be general enough that they can recognize, manipulate as many as possible objects. 

The fact that, teams perform badly for Storing Groceries is an indication that they will perform poorer for Dishwasher task because kitchenware objects are harder to grasp (grasping a plate is much harder than a coke can) and placing them in Dishwasher is a lot harder than placing them on a shelf. On the other hand, teams spend time on Storing Groceries task will need to start again by taking different approaches. This could be a good thing if we performed well for the Storing Groceries task.

**Comment by LoyVanBeek** [comment]
I agree with @tkelestemur on this one, although I'd love to see the dishwasher too. 
My choice would be to leave Storing Groceries as is until average performance is good enough. Only a few teams score points at all; most teams barely score in this test, so increasing difficulty would be unwise in my opinion.

**Comment by kyordhel** [comment]
@tkelestemur @LoyVanBeek Teams did it terrible in Storing Groceries mostly because of the uneven distribution of points (more for PDF than for live action), but that's an issue to be solved somewhere else, so let's not elaborate more about it here.

Being that said, shall I assume that your votes are for keeping the rulebook as is and include no dishwasher till, maybe, 2019?

@balkce, @iocchi, @airglow, @moriarty, @justinhart any thoughts, specially considering P&G award?

**Comment by balkce** [comment]
If there is an opposition to what has been proposed, let me propose a compromise: leave Storing Groceries as is, and just change Setting the Table and Clean Up to just do the clean up part and use that as the dishwasher test.

Even though both tests will end up doing very similar things (grabbing objects from a table and storing them somewhere else), one can be considered as a harder version of the other. And one is in Stage 1 and another Stage 2. If you squint, it kind of makes sense.

And about its challenges, yes, it's hard, and so was following a person around a crowded place 5 years ago. Teams didn't do well in object manipulation last year, true, and that's why it makes sense to leave Storing Groceries as is (just fix the point distribution, please). But the dishwasher test is in Stage 2, and I think it's time to push the veteran teams to handle difficult objects.

Now, seeing that this is the first year of this test, I think we can start this year with a standard layout of the dishes in the table, provide a standard layout of the dishwasher, etc. Meaning, make the test as simple as it can be, given the current capabilities of the robots, such that if you're able to recognize/manipulate a coke, you should be able to recognize/manipulate an eating utensil (maybe use plastic, highly-texturized, bulgy forks and/or spoons) as well as cups. And, obviously, give more points for the type of objects that we know are hard to recognize/manipulate (standard utensils, plates, etc). This also paints a clear roadmap with which in later years we can make this test harder by stripping layers of standardization.

**Comment by kyordhel** [comment]
Agreed to follow @balkce's proposal also to meet P&G request.
