### ISSUE TITLE
Ambiguity between Additional rules and remarks and Score sheet in Help-me-carry

### ISSUE THREAD

**Issue by fibonatic** [RoboCupAtHome/RuleBook#387]
In 5.3.6. in item 3. it is stated that: "the robot must clearly state it has detected the bag has been placed." But this is not clearly reflected in the score sheet, which only states: "Put up hand, closing it right after the bag is inserted". 

Can one interpret "closing it right after the bag is inserted" as "clearly state", or does the robot have to give verbal confirmation?

**Comment by kyordhel** [comment]
It is much simpler to the referee when the robot clearly states things (e.g. speaking). We expect that the robot somehow detect the bag is within grasp (e.g. weight/pressure detection, object recognition in gripper, etc), and not passively wait e.g. 5 seconds and close the gripper saying that it found/felt something. 

To me, as person, I often wait for the other person to close their hand and request me to release the bag (e.g. I'm holding it tight), or even pulling, so I can be sure the bag wont fall and the eggs shatter. Those are clear signals.

The rule of thumb is: make the interaction feel natural.

**Comment by fibonatic** [comment]
So this should be added to the score sheet, or maybe just make a general statement that in order to get the points in any challenge the robot should communicate any relevant decisions made during that challenge?

**Comment by kyordhel** [comment]
Indeed, communicating all relevant decisions is a tacit rule being followed. The reason why the rule is not written in the rulebook, is because the criteria for choosing *relevant* decisions widely varies among teams, and often robots provide too much information and confuse referees.

Clearly, most test require their scoring to be re-structured, but no major changes will be performed for 2018. So far, I think this issue gets solved by following 3.9.4 Expected Robot's Behavior (page 38 in 2017's Rulebook).
