### ISSUE TITLE
Reporting object recognition in Storing Groceries

### ISSUE THREAD

**Issue by esucar** [RoboCupAtHome/RuleBook#415]
In this test there are points given for recognizing objects, but it is not specified how to report this, in particular in the recognition report it specifies "the list of moved objects" (version Jan. 11, 2018), which could be interpeted as only reporting the moved objects. If points are awarded for each recognized object, this should be made explicit in the report.

**Comment by kyordhel** [comment]
For 2018, scoring in Storing Groceries is per-moved-object. All moved objects score a lot and in incremental fashion when properly arranged in categories (aka grouping, clustering, categorizing, etc). Otherwise, they contribute very little to scoring.

This is because is impossible to group objects by likeliness without proper object recognition, so this ability is still scored and a lot. We want to promote integration of a fast and accurate manipulation and object recognition, and not only reporting of recognized objects

**Comment by kyordhel** [comment]
That's correct. Recognized objects which are not moved won't score.

TC might, however, grant partial scoring in some cases. An example is when a robot fails to grasp an object but still completes the movement to *place it* in a correct location. Such cases should be agreed beforehand.
