### ISSUE TITLE
Predefine table position in Storing Groceries

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#419]
In the current Storing Groceries task, the position of the table is defined as only "within 2 meters of the starting position". 

Given the focus of this task (manipulation and object **recognition**),  I think the table position is too vague. (The focus is not to find furniture)

In the Stage 2 Restaurant task, the table position is even more defined (left or right). 
Given the already limited time in this challenge, I'd say: predefine the table position to left or right of the robot. 
Maybe even go as far as to define which table will be used.

**Comment by airglow** [comment]
I also agree on that. Also I'm not moving my furniture around every 5 mins :) This is kind of forcing teams to fail on an elementary skill. 
An idea on that:

Integrate a category (handover objects instead of finding them by autonomously but place them) (results in lowest score), picking it from a table of the default arena (higher score), picking from a table that needs to be found by itself (even higher score). Teams can choose the difficulty by themself like in GPSR. Get it from a drawer (highest score) ... 
This will also make it more interesting for the audience. This will result in a tradeoff between attracting people and not bore and awarding teams that actually try to achieve harder tasks.

**Comment by LoyVanBeek** [comment]
Choosing difficulty would be nice too but makes scoring harder to keep track of.

I know it's not universally liked, but scoring could be more encouraging if it also gave small points for recognize/grasp/place but **big** points for doing the whole thing. Doing all 3 parts but the whole action incorrect (recognize wrong, grasp wrong thing, place wrong thing) will give some points but much less than the whole command correctly. 

Separate topic though

**Comment by kyordhel** [comment]
I agree with the general idea but strongly disagree with specifying in the rulebook where the table is located. The rulebook vagueness is, in my opinion, something we must preserve, but the vagueness must also be removed for the competition.

To deal with this problem, I think the best is to write in OC tasks to announce which table(s) will be used and where will be placed at least one day before the test (we don't know the arena layout, nor the furniture before the competition). Also, the distance can be agreed during the TeamLeader meeting, but keeping it flexible ~2m (a Tiago's and a Ker-O-Bot's arm require much more space than others). So I think the table should be far enough so the team only needs to turn but not drive neither backwards nor forward.

**Comment by LoyVanBeek** [comment]
Agreed. In previous GermanOpens, the map indicated the position where the table was going to be roughly. 
The map is meant for humans, so there is not accuracy to be relied on, but you know at least what table to check for where, to determine an exact position.

**Comment by kyordhel** [comment]
Let's not forget that this test can take place outside the arena, so specifying a position doesn't make sense. We can, however, pre-announce where the test will take place and whether the table will be left or right from the robot. Finding a large flat surface above ground level shouldn't be problematic for most robots.

**Comment by LoyVanBeek** [comment]
A very very simple PR is read for review

**Comment by kyordhel** [comment]
PR reviewed. Minor changes requested.
