### ISSUE TITLE
Penalty for inoperative robots should be discussed

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#425]
As the penalty for inoperative robots(3.10.2.1) does not get applied anymore, a removal of this rule should be discussed.
I think this rule makes sense as it prevents to bore the audience and waste the time of referees.
Maybe there should be something like a yellow and red card as in soccer?

**Comment by kyordhel** [comment]
I disagree in that the rule is not applied any more. Unfortunately, I had to apply it in Nagoya 2017. It is up to the referee to decide when a robot turns inoperative. This is direct red card, no need for yellow one.

**Comment by semeyerz** [comment]
So maybe it was just an exception for the GermanOpen?

Otherwise this rule might lead new teams to opt out from a task(-> 0pts), when they are not sure that their robot will perform, to not risk getting the penalty.
Teams that already know that the rule will not be applied take the risk and get rewards for that.
This will then lead to unfair treatment of teams that comply to the rules!

I think it is important that the whole TC agrees on that topic and handles it the same way for all teams.

The yellow card could help here as it would be easier to show for the TC than directly giving a huge penalty of 50 points.

**Comment by airglow** [comment]
Even at German Open we ordered teams to cancel their round if the robot did not show an intention to go on after roughly a minute. This happened multiple times for the Help Me Carry, GPSR, EE-GPSR and Restaurant task. Mostly the reason seemed to be the inability of reaching a navigation goal. I. e. when a person was found behind a table.

**Comment by semeyerz** [comment]
@airglow, just to clarify, did you just ask them to abort or did you give them -50 points?
I could not attend the GPSR so I am not sure for all of the tasks and some of the -50s could be hidden behind the three tries rule.

**Comment by johaq** [comment]
3.10.1.3 states that you get a penalty of 150 points for not not canceling and then not showing up.
3.10.2.1 states that the penalty is for not solving any of the partial tasks.

From what I gathered here maybe change the penalty in 3.10.1.3 to 50 points and remove or change the wording of 3.10.2.1

**Comment by semeyerz** [comment]
As there seems to be some confusion on the penalties here the repetition of the current state in the rulebook:
* Not showing up to test without announcement 1h before test: **-150**
* Doing nothing in test for 2 minutes: **-50**

In my opinion that makes a lot of sense as it makes it easier for the referees and also the following teams. And I think the second rule is in place to prevent teams that forgot to announce that they will not participate to just place their robot in the arena without doing anything to get out of the -150.

The current state as applied by TC?:
* **-50** for not showing up at/before test
* **abort test** after some time without action

My suggestion:
* **-50** for not showing up at/before test
* **-50** after 1 Minute without action

This way no action without announcement always results in a 50 points penalty.
@RoboCupAtHome/technical-commmittee fine with that?

**Comment by kyordhel** [comment]
I'm completely against penalizing teams for inaction. Many things can go wrong and, if the robot is removed within the first two minutes, is OK for me. Scoring zero is bad enough for the team. In any case, I would set a 50pts penalty for teams trying to farm points (e.g. fetching 3 commands in GPSR but arguing robot can't execute the task, or any obvious exploit). However, this has been addressed by the EC in the past and they didn't want to penalize teams in the overall score (which makes sense to me).

Increasing the penalty from 50 to 150 when you have a very tight schedule sounds reasonable. However, I think for Montreal, 50pts penalty is fine since we don't have more teams than slots.

Since this rule may affect teams performance in overall score for uncontrolled aspects such as HW issues or Network issues (critical for SPL), I would ask EC.

@iocchi @balkce @komeisugiura @dragonjack @swachsmu @dirkholz Any comments?

**Comment by balkce** [comment]
Not showing up penalty: -50 points seems fine and enough incentive for teams to announce if they're not going to participate.

For inaction: I don't see a reason to penalize this. Not receiving any points is penalty enough. As for German Open 2018, several robots were removed from the arena after 1 min of inaction. Usually, these robots don't end up earning much (if any) points. Thus, I don't see how "This will then lead to unfair treatment of teams that comply to the rules", since a team that does the test and a team that is taken out for 1 min of inaction both abide by the rules, and earn the points they deserve. If anything, this penalty will only make the scheduling easier (less teams will participate in tests), but that's a benefit to the TC, not to the fairness of the competition.

**Comment by awesomebytes** [comment]
I'm against penalizing for inaction. Things go wrong in unforeseeable ways.
Scoring 0 hurts enough.
