### ISSUE TITLE
Open Challenge scoring and interruption

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#427]
The current version of the rule book states that teams are only able to score in the open challenge if they scored in other stage 2 tests and that the robots have to move after one minute.

I would argue to remove this rule as the open challenge is a good chance to show ongoing research which can be a single feature or component that does not even require the robot to move or talk.

On the other hand if the team does not have to show anything the general "Penalty for inoperative robots" should be applied.

**Comment by kyordhel** [comment]
Strongly disagree. Robotics requires interaction with the environment. Since @Home foundation, the Open Demonstrations (Open Challenge and Demo Challenge) always required participation in any other of the standard tests, mostly because, if your robot can't perform anything else than an open demonstration, then is not ready for RoboCup @Home and shouldm't have qualified.

Moreover, whatever feature you are planning to demonstrate, if it won't trigger robot movement, I am afraid then that feature is of no relevance for robotics. I am not saying that the research is not valuable, just of no relevance in domestic service robotics and even less for the competition. Such research would be more suitable for a conference or journal instead (e.g. RoboCup Symposium), but in @Home we want to see action.

**Comment by argenos** [comment]
We agree with this but from a different perspective. From what we saw in German Open, even the teams who scored in the second stage had problems with showing moving robots reliably. New teams have a really challenging time performing well in the first stages (let alone in the second one), but could likely show some of their robot's skills - that would never be included in the scripted tasks - from their work during the open challenge, whenever they make it to the second stage.

As the league currently is, the well-established teams can score in the open challenge even with technical difficulties and without moving robots, while the new ones would have a harder time simply getting the chance. Just our two cents.

**Comment by warp1337** [comment]
From my point of view, showing somewhat technical aspects of a system without moving, is okay. BUT, as autonomous navigation *is* essential for service/domestic robots, the scoring should be reduced to a certain degree if the robot does not move. So, instead of removing the mobile part / give penalties, we could add a note to the score sheet that, e.g., states that the robots mobility has to be considered when giving points? 

With this, I guess the situation for senior teams remains the same and gives new teams the opportunity to also show some of their skills. 

Lastly, as a reality check, I believe that no team will make it to the open challenge without reliable navigation skills.

**Comment by LoyVanBeek** [comment]
Last year in the Finals, team AUPAIR showed that their robot could describe a situation by looking at it. If I recall correctly, the robot did not move but just looked at a scene and talked for a bit. It would have not been more impressive when the robot moved an arm or navigated to another room per se, I knew they could do that already and indeed they would have not made it to Open challenge if they couldn't. 

The demonstrated skill was really cool and I think relevant for @Home (e.g when I would be blind, have a robot describe to me what the environment is). 

There was no need to move the robot for that. I agree the demo would have been stronger and more convincing if this was shown as part of a full demo with navigating to a new room it hadn't seen before.
But that is a personal thing, to make _me_ more convinced and other jury members might judge otherwise. 

Yes, I like to see action, its easier to convince me with that, but if you can convince me otherwise, good for you.

**Comment by tkelestemur** [comment]
Teams participating in RoboCup@Home have different specialties. Some are better at planning and control some are better on more cognitive capabilities (HR verbal communication, human activity prediction/anticipation etc) so I don't agree that we should limit Open Challenge to moving or not moving type of categories. 

However, to me, a robot should Sense -> Think -> **ACT**. I see the value of @LoyVanBeek's example but for me it is not a robotics research demonstration as it's not solving a robotic problem instead solving a computer vision problem. (Don't know the details tho). So I am assuming when the juries are scoring this task, they would think a robot interacting with the world the part of the *2.2. Difficulty level of the demonstrated task*.

**Comment by kyordhel** [comment]
I must remark here the difference between moving and *navigating*. To me (and I think also to the spirit of @Home) moving is essential for all demos in the competition, while navigating is not. By *moving* it should be understood navigating, manipulating, gesticulating, pointing, and, within certain contexts, even talking. In that sense, I think AUPAIR's demo was pretty much adequate for the competition.

Being that said, I stress that moving is a must in the Open Challenge, and all research that doesn't trigger any robot movement would find better place in a conference or journal.

**Comment by semeyerz** [comment]
Looks like everyone agrees, that the open challenge is about action and not about giving a scientific talk.
Thus the remaining questions are:

1. How do we enforce action? Do we really want to stop after 1 Minute?
I know that it is up to the TCs but I would like to have it written down to prevent discussions during the competition and to have the same rules applied between all three @home leagues.
And is it zero points after that 1 Minute or -50? At the GermanOpen I did not see many robots doing anything during the Open Challenge and still having the Q&A and receiving a lot of points.
Is that as intended or was that just an exception for the GermanOpen?

2. Do we want to link the points for open challenge to other Stage 2 tasks?
I do not really like coupling the points between tests. Coupling makes it really hard to compare the performances between teams in that specific test.

3. Why are points for autonomy not in the table anymore?
I think those points really pushed teams to have self explaining demos were the robot autonomously presents its features.

**Comment by LoyVanBeek** [comment]
> Do we want to link the points for open challenge to other Stage 2 tasks?
> I do not really like coupling the points between tests. Coupling makes it really hard to compare the performances between teams in that specific test.

The point for this is that you can gain a relatively large amount of points by just doing well in open, out of proportion much.

**Comment by warp1337** [comment]
Thanks for the summary @semeyerz. Here are my 2 cents.

Concerning 1):
I strongly discourage stopping after 1 minute, because we all know that something might go wrong in the beginning, e.g, connection problems, some sensor breaks down, etc. I have seen diverse demos that initially started with a complete breakdown of the robot, but after a restart, the demo was completed successfully. I also discourage a '-50 points' penalty, because the teams put lots of effort into those OC demos (we must assume that). I guess 0 points is 'punishment enough'. However, I think that it is 'ok' to **stop the demo after 50%** of the time given if the robot does nothing at all.

Concerning 2):
I partially back @LoyVanBeek point, because I would also like to see some action in other tasks than the OC. If you perform well in other tasks, but screw up (for whatever reason) the OC, you will have the disadvantage over other teams that 'just' put their bet on the OC. With respect to comparability, there is of course the 'pure' OC scoring, removing the stage 2 point weight.

Concerning 3):
I totally agree with you, there should be an autonomy section. 


Lastly, "open challenge is about action and not about giving a scientific talk" +1 again, totally. The only issue that arises is the definition of "action and autonomy". 

To give an example: one team might focus on object manipulation, e.g., fetch and carry objects within the arena which usually attracts the attention of the audience and is understood by everyone. Another team however, like AUPAIR last year, had the robot explaining the semantic relations of objects and persons in an arbitrary image. I don't dare to assess the scientific value of either one of these demos, but from my point of view, both a valuable for the robotics (@home) community. The difference is, one robot is actively altering its environment, the other's not. So, in this case the 'action' is "physical interaction" vs. "semantic reasoning and computer vision". It is extremely hard to judge whether there is real autonomy in both demos ...So is the definition of action.

**Comment by kyordhel** [comment]
No -50. That penalty is for not showing up (hence wasting Organizing Committee's and referees' time). If the robot doesn't move, no score and out. I don't see why f-up teams if the robot malfunctions. 50% of the time sounds reasonable but I would set it o 3 min max.

**Comment by semeyerz** [comment]
Not showing up is -150 right now.
But let us keep the discussion on penalties in #425

**Comment by semeyerz** [comment]
As #425 is settled, the discussion on penalties is settled here as well.

Questionable remains whether 6.2.4.4 
> [...] normalized score multipled by the highest score achieved in Stage 2
will be applied in Montreal?

**Comment by kyordhel** [comment]
@semeyerz 

> [...] normalized score multipled by the highest score achieved in Stage 2

This change will apply for Montreal. I think it is in the draft version already.
