### ISSUE TITLE
Q: [SSPL] Will Pepper manipulate objects in Montreal 2018?

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#434]
I just want to confirm that Pepper will not be expected to manipulate or carry objects?  Or are there certain objects it may be asked to manipulate?

**Comment by kyordhel** [comment]
TC can't confirm that. We expect that all robots from all leagues try to actively solve the commanded task or test. The rulebook already offers enough alternatives to bypass all manipulation-related tasks using HRI.

**Comment by AMR-** [comment]
Does that mean that, for example, in GPSR, when Pepper is asked to retrieve an object from a room, that we can assume there will be a person in the room whom Pepper can ask for assistance? (Since Pepper is not meant to manipulate objects.)

**Comment by kyordhel** [comment]
You can neither assume that. There might be people in that room as well as nobody. If there seems to be someone there, you were either lucky or that *person* is a false positive. It might also happen that there is someone nearby in another room, or that the robot requests the operator to follow it in order to provide assistance (operator might refuse of course).

> Since Pepper is not meant to manipulate objects

Last time I checked, Pepper still had two arms, and my aunt asked me if it can play the piano, so I wouldn't state that. Is very unlikely that the referee requests a Pepper to move a bottle of beer, but both a box of tea [[1]](https://www.youtube.com/watch?v=o22hN7YmVd4) and a modified tray [[2]](https://youtu.be/Uk5mZjkEsIg?t=4m0s) seems quite doable.

**Comment by AMR-** [comment]
While it is technically possible for Pepper to grasp objects, Pepper is not optimized for it.  It's not a platform for manipulation research.    It has a single actuator for opening and closing fingers.  It has no hand strength.  It cannot grasp objects of arbitrary size, but only objects within a specific diameter range.  It can pickup lightweight objects carefully.

Since this is not it's intended use, it takes more engineering work to make it pick something up than it would with a robot with a simple arm intended for that purpose.  We might ask if the great amount of work put towards this effort could be better spent on AI and HRI aspects of the robot inherent in the main parts of the SSPL tests.

**Comment by warp1337** [comment]
There people actively researching bi-manual grasping with the pepper robot.

**Comment by justinhart** [comment]
I think that this question really needs to be answered by the SSPL as a whole. It's possible that some other team has been working very hard on making sure that Pepper can perform the grasping actions that have been asked.

**Comment by iocchi** [comment]
Dear all, 
I am sure a similar discussion was done in Nagoya and even before it. When we decided to start the Social Standard Platform League, we clearly stated that the focus of research and competition is on social interaction and not on manipulation. We even replaced an entire task since last year to focus Pepper development more on social interaction and to remove "manipulation" difficulties. Although it may be possible to do research in manipulation with Pepper, I do not see why SSPL teams should do it in the framework of RoboCup@Home 2018, where the only possibility to try this ability (so to get score) in the normal tests is a possible command coming by chance from GPSR. I am pretty sure that SSPL teams are not working on manipulation and, as already discussed, manipulation can be bypassed with proper forms of social HRI. 
If I am not wrong, we already discussed last year that during GPSR, in case of manipulation tasks ("bring me a coke") Pepper was allowed to ask for help to humans around (i.e., reach the location where the coke is, clearly recognize the object, move the arm/hand in the direction of the object, then ask a person to place the object in its hand/arm or do a similar action that replaces the grasping phase, etc.). 
If we all agree on this line, can we please clarify it in the rulebook?
Thank you.

**Comment by warp1337** [comment]
> I do not see why SSPL teams should do it in the framework of RoboCup@Home 2018
 Why? We are working on that...

However, I agree that manipulation is not the _focus_ of the SSPL, on the other hand I would not discourage teams to do research in that direction.

**Comment by iocchi** [comment]
Let's make a concrete example: GPSR command is "bring me a coke"
Team A. the robot does nothing.
Team B. the robot says "I understood you want me to bring you a coke, but I cannot grasp objects, so I'll skip this command."
Team C. the robot goes to the kicthen, finds a coke, reaches the location where the coke is, clearly shows to have recognized the object, moves the arm in the direction of the object, asks a person to place the object in its hand (with a proper object it could even hold it), goes back to the person and raises the arm (possibly holding the object).
How much score would these three teams get?

**Comment by iocchi** [comment]
> 

> 
>     I do not see why SSPL teams should do it in the framework of RoboCup@Home 2018
> 
> Why? We are working on that...and we already put lots of effort into it.
> 

I meant why do it in the framework of RoboCup@Home 2018 SSPL, since in the current rules there are no points for manipulation in SSPL. If teams are interested, we can discuss this in Montreal and introduce proper tasks for Pepper manipulation.

**Comment by kyordhel** [comment]
### GPSR / EEGPSR
In these tests, several commands are retrieved. A robot can simply skip the command by asking for another one.

Although in GPRS a robot can work in up to 3 commands, there is no way a robot can actually solve 3 commands in 5 minutes unless it has human-like abilities and speed. I don't think a referee gives a Manipulation command to a Pepper that already refused one. This test is safe and no over-specification is needed.

In EEGPSR, the robot can work in up to 3 commands, however there is no hard limit in the number of commands the robot may receive. Therefore, again, a robot might opt to drop a command and ask for a second one in which it can work. Command retrieval and task execution are scores separately.

### Continue Rule and requesting human assistance 
As stated before, we can't give for granted there will be always someone available to help the robot in a manipulation task right in the spot, the robot needs to use social skills to find a helper.

Now, GPSR commands (there are no other Manipulation-related tests in SSPL) are not Manipulation tasks *per se*. We have two cases:
1. If a robot uses a Continue Rule **as is** assuming someone at the spot will perform the manipulation for it, then either partial or no point might be granted by the referee (TC shall discuss the case).
2. If the robot uses social skills to execute the command bypassing manipulation, the task is solved and full points are granted.

### Proportional points for partial manipulation
We can't specify in the rulebook what a *partial manipulation* is because we don't know that. The rule is just anticipating the case in which teams come with brilliant new ideas we couldn't consider preemptively.

**Comment by kyordhel** [comment]
REplying to @iocchi's questions:

> Team A. the robot does nothing.
Zero points (command retrieval is scored apart)

> Team B. the robot says "I understood you want me to bring you a coke, but I cannot grasp objects, so I'll skip this command."
Zero points (command retrieval is scored apart), but immediately I would provide another command for the robot to start working with.

> Team C. the robot goes to the kicthen, finds a coke, reaches the location where the coke is, clearly shows to have recognized the object, moves the arm in the direction of the object, asks a person to place the object in its hand (with a proper object it could even hold it), goes back to the person and raises the arm (possibly holding the object).

Here, it pretty much depends on the execution of the task and how the person was found. To me, the command is made up of 3 parts, so I might grant up to 2/3 of the available points for the command execution. This is assuming the robot finds the place and the object, calls for assistance and the human needs to go there and follow robot's instructions. However if...
- The robot more or less reaches the position, fuzzily points at the object, and then commands the human assistant to come to me; I think no more than 1/3 of the points, if any.
- The robot asks the human helper to follow it and actually tracks the human to my position and supervises the delivery (e.g. telling it noticed I received the coke), then it would get full score.
- The robot finds another person in the arena and socially bribes them to give the coke to me using natural language dialog, I would give full score and even grant outstanding performance.

**Comment by warp1337** [comment]
@iocchi @kyordhel I also like the eval approach of C, so we should include this example in the rulebook.

**Comment by kyordhel** [comment]
I think we have plenty of space in the appendix for it (for sake of clarity, I wouldn't modify the test).

**Comment by warp1337** [comment]
What about using a tray in Restaurant?

**Comment by kyordhel** [comment]
Rulebook specifies you can use a adapted tray for transporting objects. In the same way, you may (socially) request the barman/guests to take/place objects in the tray for you.
