### ISSUE TITLE
Poster-session and open-challenge dependency

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#44]
Participating in the open challenge now requires a poster to be presented in the poster session.
There is no scoring for the posters themselves. 
This can result in bad posters of course.

**Comment by kyordhel** [comment]
We have no score for posters since Einhoven 2013 (perhaps even since before, can't remember, was when RIPS was split).

Presenting the poster is a "must-to" as it is requirement for participation as it is Robot Inspection. In theory we are a scientifi comunity, so all teams should present a good poster.
