### ISSUE TITLE
Q: About bypassing automatic speech recognition in continue rule

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#455]
Dear everyone

Last year, we can bypass speech recognition by using QR code in GPSR or EEGPSR. Can I do that in this year again?  Also, how about other tasks?

**Comment by kyordhel** [comment]
### 3.9.1. Bypassing Automatic Speech Recognition
Giving commands to the robot is essential in many tests. To foster natural human-robot interaction, speech has been chosen as the primary way to command a robot; but Automatic Speech
Recognition (ASR) is not infallible.

Because active robots are preferred over robots that are passive due to failing ASR, teams are allowed to provide means to bypass ASR via an Alternative method for HRI (see Section 3.9.1).

#### Procedure
Automatic Speech Recognition is preferred and any command given to the robot will given by
voice first.

1. Default Operator: The command for the robot is spoken out loud and clear by the human operator. This grants 100% of the available points for understanding the command. The default operator may repeat the command up to three times.
2. Custom Operator: When the robot renders unable to understand the default operator, the team leader can choose a custom operator can give the command exactly as instructed by the referee. Unless stated otherwise, only 75% of the points are granted. A custom operator may repeat the command up to three times.
3. Alternative Input Method: When the robot renders unable to understand the command given by a custom operator , it is allowed to use any alternative method or interface (see Section 3.9.1) previously approved by the TC during the Robot Inspection (see Section 4.4). No points are scored this way.

#### Alternative input methods for HRI
Alternative methods for HRI offer a way for a robot to start or complete a task. Any reasonable
method may be used, with the following criteria:

- Intuitive to use and self-explanatory: a manual should not be needed. Teams are not allowed to explain how to interface with the robot.
- Effortless use: Must be as easy to use as uttering a command.
- Is smart and preemptive: The interface adapts to the user input, displaying only the
options that make sense or that the robot can actually perform.
- Exploits the best of the device being used (eg. touch screen, display area, speakers, etc.) Preferably, the alternative HRI must be also adapted to the user. Consider localization (with English as the default), but also potential users of service robots at their home. For example: elderly people and people with physical disabilities.

Award: The best alternative is awarded the Best Human-Robot Interface award (Section 1.7.2).

**Comment by kyordhel** [comment]
The [EE]GPSR command generator supports the generation of QR codes for the test, although I think it would be better if your team designs a nice User Interface as section 3.9.1. states.

For GPSR and EEGPSR, I wouldn't have any problem allowing the use of QR codes to bypass ASR. This, however, can't be allowed in other tests.

**Comment by LoyVanBeek** [comment]
There is of course the [vixbox](https://github.com/LoyVanBeek/vizbox/) that you can run on your robot. The webserver accepts a HTTP-POST that publishes the text on a ROS topic. 

The UI should be polished to have an input field on the main page though.

**Comment by yuma116** [comment]
I understood that QR code is available. Thank you.

I can not understand how to receive commands using VizBox. 
I found the following code.
https://github.com/LoyVanBeek/vizbox/blob/master/rosbackend.py#L58-60
```
    def accept_command(self, command_text):
        self.cmd_pub.publish(command_text)
```

But, I could not find a code calling `accept_command`.
Please let me know how to send commands using VizBox.

**Comment by LoyVanBeek** [comment]
Ouch, that was some missing documentation. I [added](https://github.com/LoyVanBeek/vizbox/commit/6d61a4b308d1462a5105374a4ee3ca182ed221f8) some docs.

**Comment by yuma116** [comment]
I have read the VizBox document. Thank you!
