### ISSUE TITLE
Q: Is it relevant to parse the Command Generator's XML to answer questions?

### ISSUE THREAD

**Issue by LudwigJoffroy** [RoboCupAtHome/RuleBook#486]
Hello everyone.

In the appendix B "GPSR in detail" and C "E2 GPSR in detail", it is written :
"The official [EE]GPSR Command Generator and the official grammars will be made available two months before the competition. However, teams must be aware that the categories, objects and other data is provided for testing purposes only."

My question is: is it a relevant approach to parse the XML files (like this one https://github.com/kyordhel/GPSRCmdGen/blob/master/CommonFiles/Objects.xml) to answer questions like "What is the category of the apple?". Does the warning in the rule book mean that there will be no XML provided before the competition? Can the real questions be different from the generated ones?

Thank you.

**Comment by johaq** [comment]
At the competition the referees will provide a list of relevant information ie objects. You can have a look in the repos of past competitions (https://github.com/RoboCupAtHome/Montreal2018) for examples.
As you can see the format might be different to what is given in the file you mentioned. In Montreal objects were given first as pdf. Usually an xml file is also provided in the format you mentioned (check out the Montreal2018 branch in the command generator) but that happens when the referees find time so if you want to adapt to the new objects as soon as possible you should be able to deal with different formats.

**Comment by LudwigJoffroy** [comment]
Thank you for your answer!
