### ISSUE TITLE
Finalize Restructured Tasks

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#489]
Obviously #488 blocks this issue. This is just a placeholder.
Once the drafts are completed I expect there will be feedback.

**Comment by RemiFabre** [comment]
Hi,
The current restructuration of the rules seems to be quite impactful. By reading what is available on the github issues, it seems that the manipulation skill will be much more important than it was before. The whole House Holder scenario seems manipulation centric and the Party Host scenario seems to have quite a bit of it too.
Is this an impression (given by the titles of the tasks) or is there a will to do way more manipulation? 
My concern is that manipulation-based tasks are probably the most failed ones currently, will there be an adaptation of the continue rules to allow robots to show their other skills?

Are you guys open to ideas from non-TC members during the restructuration? We might be missing the point sometimes since we were not in the discussions and are quite new, but we’re willing to give a hand if we can.

**Comment by moriarty** [comment]
Yes. Non TC are allowed and encouraged to provide feedback and input and can even go ahead an open PRs

**Comment by moriarty** [comment]
But in general, the rules changes coming up in 2019 are a simplification and restructuring, all of the components which were previously required to compete and do well in RoboCup at home are still present in the new restructured RuleBook.

Manipulation has always been a requirement in the past. There has always been continue rules which allow teams to skip parts but the continue rule was not intended for a permanent solution to avoid part of the task indefinitely.

We’re moving to a more streamlined RuleBook- so their will be less tests, so it may seem as though Manipulation has become more important when it has infact always been a challenging aspect of RoboCup@Home, and regarding failed ones: with less tests we are moving to more rerunning.

**Comment by LoyVanBeek** [comment]
@RemiFabre As for manipulation: I think that the ability to act in the real world, e.g. manipulate objects, is the main differentiator between service robots (like in @Home) and devices like Alex,a Google Home and what-have-you. Those will never bring me my drink or clean my toilet.

**Comment by kyordhel** [comment]
@RemiFabre 

I agree with @LoyVanBeek in that a domestic service robot is pretty much useless if it can't interact with people. I mean, I really don't need a butler and despite all this Cocktail Party enthusiasm, I rather would like to check personally with my guests everything is fine.

Now, there are a couple of **major** changes to note:
1. Manipulation is not enforced. If you figure out how to solve a task bypassing it and using 100% HRI, you score.
2. There is no predefined set of goals in logic order. This opens opportunity for quite some reasoning.

Further, I must stress that I pushed some examples. More tasks are required to balance the rulebook, including (but not limiting to)
- Find people outside and invite them into the party
- Help granny cross the street
- Help granny find her glasses
- Read out loud a recipe to granny
- Help granny to reach the bed/toilet acting as robo-cane
- Guide the technician to the utility room
- Find children in a party and guide them to the playroom
- Use a duster on the decorations
- Use a duster on the kids
- Clean the toilet
- Walk the dog
- Take out the garbage
- Wipe windows (or linux)
- Clean/scrub spots from the table

You're welcome to help with some test creation.

**Comment by kyordhel** [comment]
@moriarty Can we consider this as solved? What's pending on the ToDo list
