### ISSUE TITLE
Question regarding Manipulation and Object recognition test

### ISSUE THREAD

**Issue by LoreChile** [RoboCupAtHome/RuleBook#49]
About the bookcase, we would like to know if the bookcase will be leaning against a wall. If not, will the bookcase have an open or closed back?

When starting this test, will the robot be in front of the bookcase or can be in any position from the bookcase (ex. at the side)?

**Comment by LoyVanBeek** [comment]
- The bookcase will be placed against a wall and cannot be looked through. 
- The test does not focus on navigation. Therefore, the robot will be placed in front of the bookcase, but will most likely have to do some minor maneuvering to get a pose from which it can reach/grasp an item. I can also imagine that a robot needs to reposition itself between grasp-actions.

**Comment by kyordhel** [comment]
About the bookcase.

We do not know the bookcase beforehand since it is provided by local organization, and this includes the dimensions and if it is back-open or back-closed. Most probably it will be against a wall, and, since walls are short (120 cm tall at most) and to avoid problems, we will provide some cover behind. For instance, if we get this shelf:

![elevate-walnut-68-bookcase](https://cloud.githubusercontent.com/assets/8583949/7157402/bd7c344e-e36f-11e4-89e8-8e6a5de57230.jpg)

Then we will try to hang a blanket behind it to avoid interference. while performing object detection.

About the robot distance. The RuleBook says (section 5.2.3 subsection 1)

*One of the bookcases of the apartment is used for this test. The robot will start at a random distance between 1.0m and 1.5m from the bookcase.*

This means that the distance from the robot (closest corner) to the bookcase (closest corner) must be between 100 cm and 150 cm. The orientation is not specified so the robot may be placed with any orientation but FACING TO THE BOOKSHELF.

Think about this as a part of a test on which the robot needs to fetch an object from a shelf and just got close to it. In order to grasp, the robot needs to identify the self, get close to it, align, and recognize the objects in it. For some robots (or if the shelf is too wide) the robot may need to walk a couple of steps backwards, and get close again in a different point.

Hope this answer your questions

**Comment by LoreChile** [comment]
Thank you very much, these responses clarify our doubts.
