### ISSUE TITLE
Clean Up [restructured][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#492]
## Main Goal

There are no items, clutter or garbage where it doesn't belong

## Setup

There are items where they don't belong.

For example: Toys on the floor, Homework on the diner table, clothing on the bedroom floor, take-out boxes on the kitchen counter.

**Comment by kyordhel** [comment]
@johaq Some comments:
1. *Clean up* test is tradition since 2009! We shouldn't change it!
2. We have the "leaving the arena" bonus to promote a quick execution (extra points if you're fast) and to avoid people entering the arena to pick up the robot, which is logistically a nightmare.
3. Just make sure:
  - Main goal: ~500pts
  - Bonus goals: ~500pts
  - Sum: *exactly 1000pts*
4. Agreed. Consider those numbers are to keep fairness and to help OC setting up the task, so maybe setting a range would be better.
5. Decoration is out of robot's reach. Unknown objects are _garbage_. Robot must be smart enough to deal with it. It wasn't a problem in 2009, shouldn't be a problem today.
6. Thanks

**Comment by johaq** [comment]
1. Fair enough. I'll change it back.
2. Ok. I'd say bonus for quick execution is you get to more objects. I can add it back but I would give it less points. If we add it back I'd also think we should clarify that the points are only available if the robot successfully carried away x objects. Otherwise we get teams going inside the arena, stating I cannot grasp, leaving the arena, and then wanting the bonus points.
3. I was not aware that was the standard.
4. I like the flexibility so the referees can decide at the competition how they want to handle things and maybe up the ante over the years without needing to change numbers in the rulebook.
5. Ok, I think the description should then clearly state that these objects are garbage i.e. candy wrappers.

I'll update my pull request accordingly tomorrow.

**Comment by johaq** [comment]
4. "Hey this year this task is new, lets go for 4 known and only one unknown for every team." - "Last year went well, lets put more unknowns and alike." 
I think referees can just quickly discuss this at each competition to have it fair and consistent for each team.

**Comment by johaq** [comment]
I updated my pull request. Thanks for the feedback!

**Comment by kyordhel** [comment]
Bump. Check #517
