### ISSUE TITLE
Receptionist [restructure][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#495]
## Main Goal

All guests have been guided to the living room and their outerwear has been taken care of.

## Setup

Guests are outside of the entrance, they arrive individually or in groups, some might have outerwear which shouldn't be worn inside the house.

## OC Preparation

There should be some storage near the entrance: coat rack, umbrella bin, shoe rack _etc._

**Comment by RemiFabre** [comment]
In the current version of the draft it says : 
"Sitting the female guest next to a male guest (100pts)"
=> To avoid randomly giving points to robots that managed this without doing it on purpose, robots should clearly state who is close to the pointed sitting location. Something like "You can sit here, next to Eric". Since this is harder, maybe we could increase the bonus points for doing it?

**Comment by kyordhel** [comment]
Nope. I don’t think so.

This feature might be removed to prevent enrage politically correctness inquisition, but if it stays:

1. It is there to make clear to the referees that the robot correctly guessed the gender of a person. 
2. We must keep the test as simple as possible.

**Comment by justinhart** [comment]
I still think that this test doesn't really address HRI and really needs
some re-working to be a concrete HRI thing.

**Comment by kyordhel** [comment]
It might be the case @justinhart, but thinking it needs reworking won't get the reworking done. We need proposals ASAP.

You can nominate someone if you wish.

**Comment by justinhart** [comment]
Yeah, but I still don't really see these as HRI tasks. Finding the guest is
sort of a face recognition thing, right? That seems like computer vision,
and requesting the operator could be a simple as blurting out "I need an
operator," right?

How about something like this. If we modified the "Farewell" task like
follows, this would incorporate some of what I view as HRI elements. Maybe
something similar could be injected into Receptionist.

1) Guests must wave, look-at, or otherwise non-verbally indicate to the
robot that they are ready to leave.

2) If the guest engages in conversation with another guest, the robot must
wait for the conversation to end. If it lasts for more than 1 minute, the
robot should ask if the guest is ready to go and go help another guest if
they are not. If not, the robot should resume helping the guest to leave.

**Comment by syedaraza** [comment]
I agree there is more room to improve HRI.

I think it should be the robot's choice how to find someone for the help in opening the door. For example, the robot can go to the living room and say if someone can help me in opening the door then please raise your hand or the robot goes to each guest one by one ask if they can help in opening the door. I don't think facial recognition would be a must in this case.

In any scenario, finding a guest to help open the door would be more difficult then simply asking the operator to open the door.

**Comment by kyordhel** [comment]
@syedaraza 
Unless very specific cases in which the robot **must** default to a set of 2~4 options, let's not pollute the rulebook with endless lists of discounts for every crazy idea teams may come up. Second, in tests we try to avoid percentages because they are confusing, so lets write the number of deducted points.

Deus Ex Machina reductions will be applied ad-hoc by the TC in most cases, specially when including certain amount of [shallow] HRI. I agree with you in that the robot must come out with a solution, ranging from using a tool, ask the operator to unlock the door by pushing the handle and completing the operation by itself, or have the operator open the door and then inform the robot this has been done with a QR code or a start button. Score reduction won't be the same, and never more than the proportional contribution of the subtask to achieve the goal. 

Technically, we are allowing anything.


@justinhart 
Hold on your horses, man! The idea behind Deus Ex Machina is to make the test times easier by having a human assisting a robot with part of the task, hence reducing obtained score. We don't want to add a new dimension of complexity here (at least not now).

I agree this is at most shallow HRI, since the robot blindly asks for help. This is OK and we reduce scoring proportionally. We cannot expect robots to engage in a full dialog with a human while incorporating full sensorimotor integration to bypass manipulation. Remember that in @Home we _traditionally_ consider as HRI any task involving a human, regardless on how trivial or naive it is. From this perspective, face recognition is HRI =/

For more complex interactions, let's design tests and set the interaction as main goal.

**Comment by awesomebytes** [comment]
We agreed on the meeting to just make it as gender neutral as possible. We need to remove references to female first.

**Comment by syedaraza** [comment]
A scoresheet PR is here https://github.com/RoboCupAtHome/RuleBook/pull/541#issue-250291447

**Comment by syedaraza** [comment]
I agree it can be problematic to some people.

How about this, 
robot offers all the empty seats in the room to the guest?

It will be a challenge specially when on some seats there is some stuff placed like a bag, a book, etc. which indicates the seat is pre-occupied.

**Comment by syedaraza** [comment]
Priority seating sounds interesting too.

I was wondering how hard or easy it will be to find an elderly person in the competitions and keep him/her engaged during the tests. And he/she should be over ~60 otherwise priority seating does not justify. 

Or the person should use a support to walk like a seat walker or a walking stick then it may qualify for a priority seating.

If offering all the empty seats sounds fine then I will try to write it as clearly and simply as possible and do a PR.

**Comment by kyordhel** [comment]
Look old is enough IMO. We really don’t care about the age of the person.
I’ve seen people in their 80’s who look stronger than I, and people in
their 50’s who look twice as old.

I wouldn’t advise someone with cane in Stage I.
Gender/age/ethnicity/pose/style you can DNN-train, a cane can be confused
with an umbrella and that’s a false positive we don’t want. A trolley would
be nice but they are expensive.

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee Can we consider the Receptionist task as complete?

Can we close the issue?

**Comment by LoyVanBeek** [comment]
What could be clarified is how John is known to the robot beforehand. 
@moriarty ?
