### ISSUE TITLE
Question regarding person recognition test

### ISSUE THREAD

**Issue by LoreChile** [RoboCupAtHome/RuleBook#50]
Regarding the crowd size, can you explain more about the "area of 5 meters (diameter)"?
How far will be the audience from the robot compared to the distance between the robot and the crowd?

**Comment by LoyVanBeek** [comment]
The audience will be outside the arena. We as TC must make sure the distance is large enough, within reason. 

The additional rules and remarks also state the following:
> 2. Disturbances from outside: If a person from the audience (severely) interferes with
the robot in a way that makes it impossible to solve the task, the team may repeat the
test immediately.

Of course we hope that this won't be needed.

**Comment by kyordhel** [comment]
Perhaps my ugly draw may help.

![crowd](https://cloud.githubusercontent.com/assets/8583949/7157697/4031c794-e372-11e4-8c6f-12040a7aff0b.png)

  - The 5m distance is mandatory as it is specified in the rulebook.
  - The 1.5m distance is a "reasonable distance" which may be greater or smaller regarding on the crew and the environment.

It may also be walls or furniture arround (if there is a wall, the distance won't be considered, since people outside the room can not belong to the crowd). Notice also that the test will be scored by the TC considering the robot's point of view.

**Comment by LoreChile** [comment]
Thanks!
