### ISSUE TITLE
Extra WiFi receiver for HSR

### ISSUE THREAD

**Issue by maximest-pierre** [RoboCupAtHome/RuleBook#502]
Originaly ask by @MatthijsBurgh

as stated in the whatsapp conversation the HSR documentation suggest a second WiFi receiver

**Comment by MatthijsBurgh** [comment]
As suggested in the HSR documentation, section 6.2.2.5.6 (I don't want to publicly copy a part of the documentation), an external WiFi adapter could be used in case of instability and/or limited bandwidth.

The following devices are suggested:
- NEC Aterm W500P PA-W500P-B (Available for use only in Japan), https://121ware.com/product/atermstation/product/warpstar/w500p/
- TP-Link TL-WR902AC, http://www.tp-link.com/en/products/details/cat-9_TL-WR902AC.html

We have been having issues with the bandwidth. So I would like to ask to allow the suggested devices (or a superset). I don't know if any WiFi adapters have been used on previous tournaments. But I suggest to make some rules about it.

**Comment by kyordhel** [comment]
Unless you can prove the NEC and TP-Link have the same performance, all teams must use the same standard hardware.

**HOWEVER** you have the Backpack laptop already. Why not use it's wireless adapter?

**Comment by MatthijsBurgh** [comment]
But why would the WiFi adapter be standardized, as there are no requirements in the WiFi adapter of the laptop. So creating rules that limit the performance of a WiFi adapter could be bypassed easily by using the WiFi adapter of the laptop.

Therefore I think we shouldn't create strict rules about ( the performance of) the WiFi adapter. Just determine if teams are allowed to use a different WiFi connection than the build-in adapter.

**Comment by kyordhel** [comment]
Yet again. Why do anyone need a wireless adapter if you have the one of the laptop already? Makes no sense to me.

Whatever.

I don't want teams ranting: *X is better than Y so we have network problems, hashtag-unfair*. That's all I care about. I'll let the DSPL community decide. You have 2 weeks to reach consensus (either one adapter, a set of adapter, or not care at all).

**Comment by MatthijsBurgh** [comment]
I am not sure, but routing all the network traffic by the laptop could maybe be give some issues in Ubuntu.

About teams ranting that their network problems are caused by the WiFi adapter of other teams. That argument can also be used if WiFi adapters of the laptops are used.

I will try to contact some teams and get some consensus.

**Comment by YutaroISHIDA** [comment]
If a team use extra WiFi receiver, the team can't connect HSR and Official Standard Laptop with wired connection.  Because, the extra WiFi receiver uses Ethernet port on HSR.  

We, "Hibikino", don't want using the extra WiFi receiver, thinking that communication between HSR and the laptop should have a stable high bandwidth.

**Comment by argenos** [comment]
I'd just like to point out that not all teams are using the laptop in the backpack (until the specifications for the Alienware are updated, we're using ours as an external device), so not every team will be able to use the WiFi adapter in the laptop.

**Comment by justinhart** [comment]
There is no plan to update the laptop this year.

**Comment by argenos** [comment]
We are aware! Just wanted to bring this to the attention since the wifi adapter **of the laptop** is being discussed here.

**Comment by justinhart** [comment]
I see. You're holding out until a higher spec is available, and need a wifi
solution in the gap.

**Comment by kyordhel** [comment]
@argenos @MatthijsBurgh @YutaroISHIDA @justinhart

So far there are no plans in the TC to make any update of the Official Standard Laptop or authorize a newer model. Furthermore, when considering that most teams are struggling to get funding for Sydney, this is very unlikely to happen.

The authorization of new models, as well as the use of network infrastructure, is a decision that must be taken unanimously by all members of the DSPL community (all teams with running contract, participating in Sydney or not). Therefore, I strongly suggest to arrange a meeting and discuss the issue. If the whole league agrees, the TC will most likely implement the change, but if there is a single team holding back, this is a no-go for all.

**Comment by MatthijsBurgh** [comment]
I would like to (re-)start this discussion. Because of the issues we experienced at the German Open.

At the German Open, the network was very stable. We never experienced any issues with the laptop we use to start our challenges. However the connection between the network and the HSR was very bad. Ping times were more than 500 ms. This made it very difficult to even enter a command to start a challenge.

Forwarding Wi-Fi from the laptop to the HSR is not working in our case. We were prepared at did bring a external router, the TP-Link TL-WR902AC. It solved all our problems.

As we allow any laptop, we allow any Wi-Fi adapter as long as it is build in into the laptop. Therefore I don't see any reason to not allow any external Wi-Fi adapter.

P.S. I want to highlight that we have HSR 35. This is an older version. HSR>50 are slightly upgraded. I don't know the specific differences between the versions, but it could be that Wi-Fi performance is upgraded. Maybe Toyota can clarify the differences.

**Comment by LarsJanssenTUe** [comment]
Ping @justinhart @moriarty @johaq @awesomebytes @kyordhel

**Comment by johaq** [comment]
Similar to the audio issue. I would not allow something that is not in the rulebook.
Personally, I have no objection to what @MatthijsBurgh is proposing and I think most TC members feel the same. So make a pull request to give other DSPL teams an opportunity to chime in or protest.
