### ISSUE TITLE
I Want This (HRI task) [restructure][draft]

### ISSUE THREAD

**Issue by awesomebytes** [RoboCupAtHome/RuleBook#512]
As discussed in the meeting from 14/01/19:

This is a proposal for a new test which contains more focus on HRI (as we dropped Tour guide). It will contain human robot interaction in the shape of pointing to stuff both for the human to point at something and also the robot to point at something.

**Comment by justinhart** [comment]
Yep. Pushing this in a couple hours. Had a late night last night.

**Comment by jvitale** [comment]
Hi Justin,

Thanks for the first draft. I read it and I have a few minor suggestions to start with:

> A guest at the party speaks English, but with only a limited vocabulary. They want a drink, an hors d'oeuvre, and a set of utensils, but do not know the words to describe them. As such, they will ask the robot for one through gesturing, and will ask for recommendations made by the robot through gestures. They will also discuss a picture on the wall, which the robot will determine by analyzing their gaze.

I would use the word "appetizer" instead of hors d'oeuvre.. it's probably more easy to understand for everybody.

> \item \textbf{Surfaces:} The test area must have 3 surfaces with items arranged an equal distance apart on them.

I would edit with: "... 3 surfaces, each one displaying items **of similar size** arranged by maintaining an equal distance between them."

> \item \textbf{Pictures:} Three pictures should be hung along the broadest wall of the arena. They should be 2 feet apart.

Every reference to "feet" should be also provided in meters.

>  \item \textbf{Picking drinks:} The person that is being helped will stand on the mark, look and point at one of the drinks, and say \textit{That one!}. The robot must then say, \textit{Do you mean the one to the [left, middle, right]?} If correct, the robot gets 100 points.

When the robot (or human) has to confirm the item, it should be clearly specified from which perspective is left or right. If we want to avoid this problem we should let the robot recognize the pointed object, or provide its unique description. We can also think about giving extra bonus points if the robot is able to describe the object by mean of vision.

> \item \textbf{No clarification through dialog:} The purpose of this test is to test the gesture generation and understanding abilities. Therefore, no dialog should be used to clarify, as this would be easy to program and defeat the purpose of the test.

I would make it more general: "Communication only through gestures" ... "Therefore, no dialog, tablet or any other form of communication apart from gestures can be used to clarify ....". This will prevent people to find other means to bypass pointing interpretation.

As we discussed last week, the task may need a review in terms of the story and flow, but the general idea I think it is fine.

**Comment by awesomebytes** [comment]
Linking to the Pull request: https://github.com/RoboCupAtHome/RuleBook/pull/528

@jvitale I'd encourage the comments that refer to specific bits of the description of the test to be done in the pull request as it creates a conversation in-place which is easier to follow (and there are some comments already there).

**Comment by kyordhel** [comment]
@jvitale I'm adding you as contributor so you can officially review Justin's work in the PR.

As @awesomebytes suggested, In the future, please comment on the pull request to prevent your contributions from being taken out of context or lost.

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee Can we considered this task as complete?

Can we close the issue?
