### ISSUE TITLE
Q: is vizbox mandatory ?

### ISSUE THREAD

**Issue by jbhorel** [RoboCupAtHome/RuleBook#564]
Hello,

I have just read the last version of 2019 rulebook and the section on VizBox, it is said that *"all robots are expected to run the VizBox"*. I read the issues #467 and #389 and can't find any definitive answer, so I'd like to know the current state of the discussion, is it mandatory and what is used to display it ?

Thanks in advance,

jbhorel

**Comment by kyordhel** [comment]
@LoyVanBeek bump

**Comment by LoyVanBeek** [comment]
Here's the thing: something can only be mandatory if it is enforced. 
I cannot decide on that as I'm not (anymore) an official on the league: is a team not allowed to compete without vizbox? Get a penalty for not using? 

It does require some hassle on the OC as well to set up a screen etc.

**Comment by jbhorel** [comment]
OK, I see. Thanks for your answer.

**Comment by kyordhel** [comment]
TC is currently discussing how to encourage the use of Vizbox.

Due to technical issues (aka network), we are not comfortable with enforcing its use, but it has clear advantages. Not only let you watch real time in an official way what's going on, but also helps the audience to understand how challenging is the task from a scientific level.

**Comment by jbhorel** [comment]
Thank you, my question is answered so I'm closing the issue.
