### ISSUE TITLE
Q: Expected behaviour when pressing the emergency button

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#565]
Hi,

The RuleBook says "When the emergency stop button is pressed, the robot and all its parts
must stop moving immediately".

With our robot, pressing the emergency stop button cuts the power to everything but the internal PC. This is a very reliable and fast behavior since there is no software on the loop but the arm and head fall to the ground (at a speed that shouldn't be dangerous for humans). Is that okay?

**Comment by kyordhel** [comment]
# Yes, it's OK.

The main reason why pneumatic/hydraulic actuators are banned in @Home is because they are too strong and they don't lose strength when you cut power. An *Emergency Stop* button should stop the whole robot movement, preferably by cutting power to all actuators. It's a *stop*, not a *freeze*. Besides, psychologically is safer to see an aggressor (human or mechanical) to dismay instead of getting frozen.

As a matter of fact, we rather like power cuts over software breaks because if software fails, the robot continues moving and the emergency button is useless. We have had this situation several times in the past, and it must not occur again.

**Comment by RemiFabre** [comment]
I agree. We should change the sentence in the RuleBook then. As it currently stands, the expected behavior seems to be a _freeze_. How about:
"When the emergency stop button is pressed, the robot should immediately fall into a state where it can't actively move anymore, this is typically achieved by cutting the power to all actuators."

If this is ok, I can PR it.

**Comment by maximest-pierre** [comment]
You can propose this change to the rulebook. I would remove the part about cutting the power to all actuators since its dependent on the robot or the actuator.

**Comment by kyordhel** [comment]
> the robot should

Should? Should is way too mild. No less than **must**.

> immediately fall into a state where it can't actively move anymore

Way too baroque. Safety rules must not be prone to misinterpretation. Specially in this one, we must be sharp and clear.

**Comment by RemiFabre** [comment]
What about this:
"When the emergency stop button is pressed, all the actuators of the robot must immediately stop applying any torque or force."

**Comment by kyordhel** [comment]
I'm not sure that's entirely possible for SSPL/DSPL and other comecial robots.

That rule has been there since the very first rulebook, so I'd keep it the way it is and appeal to the common sense of the referees.

**Comment by moriarty** [comment]
They should also not quickly fall to the ground and cause damage that way.

I think the way it is written in the RuleBook is fine. 

From your description, your robot should be fine, because the robots head and arm will drop, but not at a speed or weight which will cause any damage to a person, the environment or the robot itself.

As a counter example:
The Kuka YouBot arm (from RoboCup@Work), has two options for e-stop, the default, cuts power to the motors and the arm which is very small but also very heavy for its size- will quickly fall to the ground. It has in RoboCup broken the arm itself, sensors mounted to the arm, the environment (3D printed tiles for precision placement) and many grippers... and if you or the TC try to grab it, it can give a nasty little pinch if you put your finger in the wrong place... This type of e-stop would not be allowed. I’m @Home, if you have a small lightweight arm which doesn’t drop fast and doesn’t cause damage, then it should be fine.

For the arm I just described, there is an option to wire a second e-stop, one which enters gravity compensation mode... something not available in the default driver, which will not apply additional torque, and hold the motor where it is.

The Kuka LWR, on the Care-o-Bot 3, is an industrial arm, on that arm, the e-stop locks the motors in place with breaks, it is safely certified and it will stop exactly where it is no matter how fast it’s moving. On an arm that size and weight, a e-stop which allowed the arm to fall to the ground quickly, or did not react in time would not be allowed.

The Fetch, also has a similar arm in size to the care-o-bot, but when the e-stop is pressed the arm gear ratios are such that it will stop and then fall slowly under it’s own weight, slow enough that someone can get catch it, but not fast enough to cause any damage. There is gravity compensation mode, which is by default enabled all the time when not using the arm, but it was decided the safest thing for the e-stop to do is let the arm slowly fall.

Ideally, the robot should stop where it is. But in reality it depends on the robot what is the safest thing to do.

It sounds like your robot is fine.

I don’t think the rule needs to be changed because I’d rather teams contact the TC/EC for clarification on this issue.

If we say arms are allowed to fall, then this isn’t always the safest thing to do.

**Comment by moriarty** [comment]
@RemiFabre it looks like you have the Tiago:

https://robotics.catie.fr ? In which case I’m sure your e-stop will be fine.

@maximest-pierre your Teams first time at RoboCup, in 2016 was a good example of why we test E-Stops as part of the robot inspection 😆

**Comment by LoyVanBeek** [comment]
At TechUnited, AFAIK we short the power in the arm actuators which makes the arms very slowly drop (@MatthijsBurgh @jlunenburg care to explain how this works exactly?). If you exert any force, you can slowly push them if needed. 
The wheels are cut from power but the encoders still work. Means we can push the robots around. 
The e-stop effectively works as a pause-button, because the robot can continue where it left of.

**Comment by RemiFabre** [comment]
Guys, thank you for the thorough answers.

The UR arms also have brakes that are normally closed. Also, the braking force is tuned so that it can stop the arm from moving but that a human can force through it if need be. I think this is a good design but quite expensive to reproduce.

Yes we have a TIAGo, we've been working on a zero gravity arm: https://youtu.be/4auVU5Ifvpw

Maybe one day that will be the safest behavior, but for now I'd rather have the reliability of cutting the power :)

**Comment by MatthijsBurgh** [comment]
> At TechUnited, AFAIK we short the power in the arm actuators which makes the arms very slowly drop (@MatthijsBurgh @jlunenburg care to explain how this works exactly?). If you exert any force, you can slowly push them if needed.
> The wheels are cut from power but the encoders still work. Means we can push the robots around.
> The e-stop effectively works as a pause-button, because the robot can continue where it left of.

The control boards have two separate power inputs, one for the logic and one for the actuators. When the emergency button is pressed the power for the actuators is cut off. (Also all controllers are stopped, etc. So it doesn't do crazy things when the emergency button is released. Then the controllers are restarted)

**Comment by kyordhel** [comment]
@RemiFabre  if your question has been answered/solved, please close the issue.
