### ISSUE TITLE
Questions about Receptionist

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#569]
In the Receptionist task, it appears that guests arrive one-at-a-time (implied by the additional rules and remarks, e.g., "Every time a new guest arrives, people in the living room exchange places"). However, the oldest person is to be seated on the sofa. Do we assume that both guests actually arrive at the same time so that their relative ages can be assessed immediately (otherwise, how can you tell if the first guest is the oldest?)

Also, is it permitted to determine relative age using polite dialog rather than visual features?

**Comment by johaq** [comment]
People do arrive one at a time. I don't see the problem with order since the robot is allowed to rearrange seating. So you could i.e. ask the first guest to sit somewhere else if the second is older etc.
I would not give points for determining age through dialog because bonus goals are supposed to test bonus abilities, here age detection, not the robot's speech abilities which are already being tested plenty.

**Comment by benatuts** [comment]
The introduction says that the just-arrived guest should be offered an unoccupied seat.

**Comment by johaq** [comment]
If you ask a person to sit somewhere else their previous place is unoccupied.
