### ISSUE TITLE
Q: how to provide data?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#571]
Some tests (e.g., EGPSR and Find My Disk) award points for supplying data. How is this supposed to be provided? Is there a deadline (e.g., by end of test, by end of day, before end of stage)? How is it provided if the network is down?

**Comment by moriarty** [comment]
1. Ideally end of the test, possibly end of that test block. Not end of day or end of stage because scores are done after each test block.
2. USB Stick. Bring your own, or go buy one.
3. If network is down, plug your robot into a Ethernet cable after the test.

**Comment by johaq** [comment]
In the past the referees were going around to the teams and collecting usb sticks. This is not going to be the case anymore since providing data is "only" for bonus points and therefore up to the team if they wanna go for those.
I think bringing an usb stick to the referees until the end of the test block is best (a little after to give a chance to the last team in the block). Please note to clearly label your usb stick so we can assign the scores correctly and return the usb stick. Unlabeled usb sticks will not be scored.

**Comment by kyordhel** [comment]
@benatuts  if your question has been answered/solved, please close the issue.

**Comment by kyordhel** [comment]
Expired
