### ISSUE TITLE
Q: Contradiction in 3.8.3?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#572]
In 3.8.3 Bypassing Automatic Speech Recognition, there is a 30% penalty for when an "alternative HRI interface" is used to instruct the robot (the 5th item). However, in the next paragraph, there is an award for using "Alternative interfaces for HRI".

This seems contradictory... to be penalizing and rewarding what appears to be the same thing.

**Comment by moriarty** [comment]
We could just have a penalty.

**Comment by johaq** [comment]
I think the wording for the award might be misleading because it is so similar to the penalty. The penalty is applied because we want teams to focus on SPEECH recognition and processing. A button press on tablet should not award the same points. That said we want to encourage teams to work on alternatives. Say a robot has trouble understanding one person or it is very loud on location (looking at you soccer). The robot can then offer an alternative. This will give less points but is still good for the team because the task can continue. We want to award teams to work on natural and intuitive alternatives but we also do not want teams to just forego speech processing entirely.

**Comment by kyordhel** [comment]
@benatuts  if your question has been answered/solved, please close the issue.

**Comment by kyordhel** [comment]
Expired
