### ISSUE TITLE
Q: what are the "operator's requirements"?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#573]
I'm unclear how "Find My Disk" works from the operators point of view...

I think what it is saying is that before the test, the operator is shown two disks. The operator is then "blindfolded" and the disks are returned to the case, and the robot has to help the operator find those same two disks again?

Is that correct?

If so, I would suggest rephrasing the main goal be guiding the operator to locating the correct disk, rather than providing a description --- the goal is to find the disk (through dialogue and description), rather than providing descriptions _per se_.

Also, I would note that the example of the robot asking the operator "what's the cover color?" is perhaps a little bit strange given that the operator is considered to be visually impaired.

In: "The robot can request the operator to pick up a disk and show the cover or back-cover". This is ambiguous. Does the operator have the ability to distinguish between front and back or does the robot need to be able to tell the difference?

**Comment by johaq** [comment]
Your first description sounds correct to me. 
I think the main goal is fine because it reiterates what the robot was doing i.e. "I found cover that is... this matches your description, right?"

I'm by no means an expert but from what I know a blind person can still be aware that a disk they own has a specific color on the cover. But please do correct me if this indeed unreasonable to ask a blind person.

For anything you think is ambiguous or could be made clearer, please feel free to open a pull request with your suggested changes and we can discuss them there.

**Comment by kyordhel** [comment]
@benatuts  if your question has been answered/solved, please close the issue.

**Comment by kyordhel** [comment]
Expired
