### ISSUE TITLE
Q: Where is the umbrella in the Farewell test?

### ISSUE THREAD

**Issue by hugoleon18** [RoboCupAtHome/RuleBook#592]
I have doubts with the Farewell Test

At the beginning of the test who has the umbrella? or where can we find the umbrella to give it to the guests?
I understand that the taxi driver has his own umbrella and is different from the one used by the guests.

**Comment by johaq** [comment]
I would put the umbrella next to the coat rack.
We should consider adding this for clarification if we want it to be fixed.

**Comment by kyordhel** [comment]
What I've seen normally in most houses, offices, and shops, is some sort of rack or bucket next to the door. Always near to the entrance/exit to prevent leaking on the floor, and often near to the coat rack.

Probably we will use the trash bins due to limited budget; but I'd say that if is not standing like a cane (most probable), it will be hanging next to the coats (less probable). Worst case, the robot can go *DeM* and request a handover.

**Comment by hugoleon18** [comment]
Thank you for the answers @johaq and @kyordhel 

So, once the robot gets the umbrella, it must be given to the visitor or the robot must carry the umbrella with it.? I think it would be difficult for the robot to navigate with the umbrella opened in his hand and even leave the arena with it.

I think that the part of the umbrella is left over from the main purpose of the task. It takes time and no points are awarded for taking the umbrella.

**Comment by kyordhel** [comment]
It’s raining outside. What would you do?

The robot must do the same anygood host would.

**Comment by hugoleon18** [comment]
I am totally agree with the idea of The robot must do the same any host would. 
Thank you for your answer @kyordhel .
Now it is more clear for me the way to solve the test. 
I will close the issue
