### ISSUE TITLE
Q: What is the maximum reward in Enhanced General Purpose Service Robot test?

### ISSUE THREAD

**Issue by carlosquinterop** [RoboCupAtHome/RuleBook#596]
In 6.2 **Enhanced General Purpose Service Robot** test, the robot is expected to execute 3 commands at 500pts each but the maximum reward is 1200pts. Is this a mistake?

**Comment by maximest-pierre** [comment]
These are probably errors. I think the **EGPSR** should be 1500 (3 commands * 500 as per scoresheet). For the 6.9 **Where is This** i think its supposed to be 3 (3 people * 100 as per scoresheet). @kyordhel You wrote part of these test care to chime in.

**Comment by kyordhel** [comment]
Here there are two questions. Please edit and split in two issues. I'm addressing here EGPSR only

# TL;DR; EGPSR max score is 2500pts. Main Goal awards 1500pts.

Under main goal, there is a typo. It should say 1500 instead of 1200. However **this is still wrong**.

### Further changes
Expecting that a robot can solve three all commands is unrealistic, so I think the main goal should say:

> Execute at least one of the 3 commands requested by the operator.

Otherwise is three or nothing. I'm opening a PR to fix this.

**Comment by maximest-pierre** [comment]
@carlosquinterop A patch has been merge to address these errors. :tada:

**Comment by carlosquinterop** [comment]
Thank you! I've just created another issue for the **Where is This?** test

**Comment by kyordhel** [comment]
Expired
