### ISSUE TITLE
Q: How will tests be scored?

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#604]
Could you please provide clarification on the scoring for each stage? For Stage 1 it says that "Overall scoring is calculated as the sum of the maximum score obtained in each ability." 

Is an 'ability' a 'task' e.g. 'Serve the breakfast'? Or is it 'Housekeeper'/'Party Host'?

What is the maximum score for Stage 1?

**Comment by kyordhel** [comment]
We definitively need to correct that line. Instead of ability it should say *task*.

So, according with Table 3.1, in Stage I you can run up to 6 tests: 3 in Housekeeper + 3 in Party Host. Let's say that during the competition you get 6 testing slots, meaning that you can run each test once. Since you're neither too bold nor overconfident you go with the following tasks:

| Slot | Scenario |        Task        |   Score   |
|:----:|:--------:|:------------------:|:---------:|
|  1   |    HK    |  Clean up          |  500 pts  |
|  2   |    HK    |  Serve Breakfast   |  150 pts  |
|  3   |    PH    |  Serving Drinks    |  700 pts  |
|  4   |    PH    |  Serving Drinks    |  100 pts  |
|  4+  |    PH    |  Receptionist      |  250 pts  |
|  5   |    HK    |  Serve Breakfast   |  800 pts  |
|  6   |    HK    |  GPSR              |  300 pts  |

You chose 5/6 possible tasks. Since you did it lamentable (from your perspective) in Serve Breakfast, you decided to repeat it later, with excellent results. However, since you did almost perfect in Serving Drinks and wanted to max score, you repeated the task but the robot failed and barely do anything (it happens).  Fortunately (or is it?), all teams were jiunxed in that second round of Party Host so there was time for a repetition in which you decided to try Receptionist.

### How do we score then?
Since we are taking the maximum score **per task**, we could strike out low scores and rewrite the former table as follows:

|        Task        |    Score    |
|:------------------:|:-----------:|
|  Clean up          |   500 pts   |
|  Serving Drinks    |   700 pts   |
|  Receptionist      |   250 pts   |
|  Serve Breakfast   |   800 pts   |
|  GPSR              |   300 pts   |
|  **Sum:**        |**2550 pts** |

So you would score _2550 pts_ for Stage I. The maximum score considering a maximum allowance of 6 tests is 6500 points since each task grants 1000pts but GPSR which grants 1500, so that's your best case scenario. Please consider that the rulebook is designed to push robots to the limit, so obtaining a maximum score would require perfect execution in a single try and opting in for all bonuses, which is very unlikely to happen.
