### ISSUE TITLE
Q: GPSR Bonus Scoring

### ISSUE THREAD

**Issue by cduss** [RoboCupAtHome/RuleBook#606]
Hi,

In 5.5  General Purpose Service Robot [Housekeeper] bonus rewards can be scored if the robot understand commands by naive operator and provide logs for it.
Well, what if we can understand the command, find a way to rephrase it so that it is clear to everyone that the robot understood perfectly what he was asked to do but simply states something like "I cannot perform such task without further development" ?

In a word, is bonus scoring for understanding and logging naive operator interaction tied to actually executing the command or would it be granted for a kindly explained inability to execute the understood task ?

Thanks
Cduss

**Comment by johaq** [comment]
You can only score bonus points if you successfully complete the main task.

Section 3.6.3:

> To score in a test, a team must successfully accomplish the main objective of the task;  bonuses are not considered otherwise.

**Comment by cduss** [comment]
Ok

Thanks

**Comment by kyordhel** [comment]
Although the issue is closed, I'll add a remark here.

In GPSR you score per command. You need to execute the task to get the data recording bonus points, so if the robot skips one command, no bonus can be scored because of the transcript. This decision was taken to prevent point farming.

However, your transcripts will be used to design the generator of 2020, so you can still deliver recording data for the sake of science
