### ISSUE TITLE
Q: How should audio transcripts be provided?

### ISSUE THREAD

**Issue by LarsJanssenTUe** [RoboCupAtHome/RuleBook#617]
So for the GPSR challenge bonus points can be awarded for "provide audio recording and transcript". There is however no specification whatsoever of what should minimally be in the recording and the transcript. Of course I can sort of guess what is desired, but I would like to have a clear definition.

p.s. there is a difference in the definition of the points for each command given by the naive operator, 50 points in the under the caption "Bonus rewards" and 100 points in the score sheet. I assume the score sheet is leading on this?

**Comment by kyordhel** [comment]
The specification was left out of the rulebook to save space since it's quite intuitive.

We expect pairs of audio files (e.g. uncompressed PCM wave files at 48kHz, 16 bit, mono) and plain text files (e.g. UTF-8) containing the transcript. Obviously, the audio files should be cropped to contain only entire sentences, and the text file should contain only the transcript of that sentence. A long audio file with all the interaction between the robot and the operators is unacceptable since it can't be used for training or automated machine learning.
