### ISSUE TITLE
Q: Will incomplete commands be issued to robots in GPSR?

### ISSUE THREAD

**Issue by LarsJanssenTUe** [RoboCupAtHome/RuleBook#620]
Currently the GPSR Command Generator generates commands that miss information. There is however nothing stated in the challenge regarding missing information. What is the decision for this regarding RWC2109 (f.e. extra points like previous years?), especially considering the decisions made during RGO2019?

**Comment by johaq** [comment]
At the German Open we decided not to use commands with missing information for GPSR. The TC will decide what to change based on the prep competitions shortly after they are concluded.

**Comment by kyordhel** [comment]
After 8 years of robots dealing with incomplete commands and missing information, I think robots are ready to handle with it without any additional reward. To keep things fair, all participating robots would have to receive at least one of them, but I see no problem with it since nowadays is kind of problem solved when using a generator. 

Nonetheless, a final decision will be made by the TC on this regard for the world cup.

**Comment by kyordhel** [comment]
@LarsJanssenTUe if your question has been answered, please close the issue.
