### ISSUE TITLE
Schedule Slots

### ISSUE THREAD

**Issue by balkce** [RoboCupAtHome/RuleBook#623]
This issues is relevant to #590 and considers what was seen in the German Open 2019 in terms of scheduling.

[Copied from [here](https://docs.google.com/document/d/1a82p-WXr7EfugQy-IUSCdqHzqCNU0zVeHZomp8yIvO4)]

Having one big slot for all the attempts of one scenario is hard on the judges (3 hours is a LOT of time), and stressful on the teams since there isn’t much time to go back and work on non-minor issues. The following schedules were proposed by @swachsmu , which merit discussion:

**Proposal 1:**

- In the first day of the competition, there is currently a 3 hour slot for each scenario, implying at least 3 attempts per slot, 6 attempts in total.

- Change to have instead a 2 hour slot per scenario in the morning/midday, and another 1 hour slot per scenario in the afternoon, with a break between slots as necessary.

- As for the second day, remove the 3 hour slot, and replace it with two 1-hour slot per scenario. Preparing the arena and testing for all tests lends itself to chaos.

**Proposal 2:**
- Do not test all teams in the same schedule slot. Divide teams in subsets

**Comment by balkce** [comment]
Additionally, and also relevant to #590 :

[Also copied from [here](https://docs.google.com/document/d/1a82p-WXr7EfugQy-IUSCdqHzqCNU0zVeHZomp8yIvO4)]

If the teams inform the TC/OC of their tasks just one day prior, it requires a LOT of preparation, since: 1) it entails buying all of that is required for all the tasks during the setup days, and 2) the arena needs to be prepared to test ANY task (even those that are not be chosen by the teams).

We should settle on how much time in advance do teams need to inform the TC/OC of what tasks they’re going to do.

A case can be made on announcing them some weeks prior the competition to facilitate organization.

**Comment by kyordhel** [comment]
Against what common sense would advise (@swachsmu recommendations are wise), I bust be devil's advocate and remind you that we were required to have **maximum 2 tests per day**.

Therefore, splitting the test blocks wouldn't be an option.

However, nothing says that we can't have fixed runs, i.e. the second set of test slots cannot start earlier (e.g. block starts 1st 9:00, 2nd 9:30 regardless performance).

As of requiring tests, teams must announce 1 month in advance their candidates. That will reduce the workload since we know which tasks won't be attempted at all.

**Comment by balkce** [comment]
> the second set of test slots cannot start earlier (e.g. block starts 1st 9:00, 2nd 9:30 regardless performance).

I think that this is a good compromise.


> teams must announce 1 month in advance their candidates. That will reduce the workload since we know which tasks won't be attempted at all.

Agreed. This means we need to send out a call for tests as soon as the rule book is finalized. (*cough* #628 *cough*)

**Comment by kyordhel** [comment]
> we need to send out a call for tests as soon as the rule book is finalized

No. We need a preliminary list now.

With all due respect to our Technical Committee members, the TC missed all self-imposed deadlines for this year. I've zero confidence in having the final version of the Rulebook ready by May 31st.

By the end of the month all teams should have a good idea on which tests they will have ready. Issue #590 suggest 3/3 for Stage I and 2/2 for Stage II which seems fine to me (@airglow told me most teams only tested one task 3 times per scenario).

**Comment by johaq** [comment]
I'm kind of against forcing teams to announce that early. Yes, as TC it is nice to know in advance but I know how much can still happen in the month prior to the robocup. I also think knowing so far in advance has actually very little organizational benefit. It is only good know which objects need to be there (no need for yellow jacket if no teams want to do farewell) but due to gpsr and eegpsr we probably need every object anyway. In terms of setup knowing one day in advance was perfectly fine for setting up.
