### ISSUE TITLE
Can score of main goal be less than zero?

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#637]
In several tests the *Deus Ex Machina* reductions overweight the score of the main goal. This was done on purpose to prevent point farming and abusing human help, i.e. having the human assistant to solve the task and get positive scoring.

However, this means that completing the main goal might lead to big negative scores that may also overweight the task bonuses. Hence we got this question:

**Should the main goal scoring be rounded to a minimum of zero?**

Right now, the rules imply we just sum everything and get the scoring. However, there is a rule in 
General Rules that specify that no test can provide a negative scoring (unless it comes from extraordinary penlties). This can be taken as precedent.

**Comment by johaq** [comment]
Yes, I absolutely think so. We do not wanna penalize teams for attempting a task. I think this is adequately covered in the general rules.

**Comment by kyordhel** [comment]
@johaq No, it is not. We should add the rule.

**Comment by johaq** [comment]
Section 3.6.3:
Minimum score: The minimum total score per test in Stage I and Stage II is 0 points. Teams cannot receive negative points.

**Comment by kyordhel** [comment]
I think you misunderstood what I said. Not a minimum of Zero per task, but a minimum of zero for achieving main goal. Let's say:

**Main goal**
- Main goal reward +250 [x1]
- Bypass ASR -100 [x1]
- Bypass Manipulation -100 [x2]

**Bonus goals**
- Bonus goal reward 200 [x1]
- Bonus goal reward 300 [x0]

The total score would be -50 for the Main goal +200 for a Bonus goal = 150

My question is whether this is good or we should clamp the main goal to a net zero.

**Comment by johaq** [comment]
Ah sorry, I see what you mean. I do not have a strong opinion on this, I would be fine with either solution.

I slightly tend towards letting the -50 stand in your example because I want teams to first focus on solving the main goals as well as possible before attempting the bonus goals.

**Comment by moriarty** [comment]
Yes, I think we should let the -50 from the above example stand... or we should score the entire tasks and keep track of how negative teams get, and have the information available if we need it later for some tie break or qualifying decisions: but publish zeros....

This later option I describe is confusing, because we’re then ranking the zeros based on the negative scores which we throw away. But negative scores just look bad for the public and are morally bad for the competitors.

For example:
Team C attempts everything without ex-machina rules, but messes up and drops something or has a major collision, somehow this result is either negative or zero, but rounded to zero.

Team B attempts very little, constantly used ex-machina rules and scores negative, and again rounded to zero.

In my opinion Team C’s zero should be worth more than Team B’s zero.

**Comment by MatthijsBurgh** [comment]
> In my opinion Team C’s zero should be worth more than Team B’s zero.

So the new scoring is too strict as it doesn't represent the performance correctly...

**Comment by johaq** [comment]
Well this is somewhat a fundamental question for our competition. Is a robot that attempts everything autonomously but ultimately fails or a robot that achieves something but has to ask for help more useful or more worthy of points. I think there is not an easy answer that covers every case. 
I think we need to see the results in Sidney and critically evaluate: "Do the scores accurately represent the performance of the teams?"
In Magdeburg I think there were some minor cases. I.e. one robot following a few meters outside scoring the same as a robot not following at all. I am somewhat fine with this because I think we are at a point where we expect robots to robustly follow and not reward robots for following a few meters even though it is of course better than not following at all.
If there are some egregious cases in Sydney where one robot vastly outperforms another but still scores the same, then we need to rethink the new scoring.

**Comment by balkce** [comment]
Sorry to throw a wrench into this, but: didn't we also establish that if the main goal is not achieved than there would be no considerations for bonus rewards? It seems to me that if the robot was not able to achieve the main goal, than the bonus rewards are mute. Correct me if I'm wrong.

**Comment by johaq** [comment]
Mauricio pointed out that with DEM penalties you can achieve the main goal and still have negative points. We could of course also simply argue that if the robot needs that much help we consider the main goal not achieved and therefore do not consider bonus points.

**Comment by DavidPL1** [comment]
> Yes, I think we should let the -50 from the above example stand... or we should score the entire tasks and keep track of how negative teams get, and have the information available if we need it later for some tie break or qualifying decisions: but publish zeros....
> 
> This later option I describe is confusing, because we’re then ranking the zeros based on the negative scores which we throw away. But negative scores just look bad for the public and are morally bad for the competitors.
> 
> For example:
> Team C attempts everything without ex-machina rules, but messes up and drops something or has a major collision, somehow this result is either negative or zero, but rounded to zero.
> 
> Team B attempts very little, constantly used ex-machina rules and scores negative, and again rounded to zero.
> 
> In my opinion Team C’s zero should be worth more than Team B’s zero.

I agree with your opinion and yes, your second option is confusing but you have a point. I think a way to address both issues could be shifting the score of all teams in order for the worst scoring team to reach at least 0 points.

**Comment by kyordhel** [comment]
Thanks for your comments. That pretty much settles the question.
