### ISSUE TITLE
Q: Startup position and object placement in Storing Groceries

### ISSUE THREAD

**Issue by rishihahs** [RoboCupAtHome/RuleBook#643]
I have a couple questions regarding storing groceries:

1. Do we start from a closed door like other tasks? #585 seems to imply yes, but the [notes](https://docs.google.com/document/d/1a82p-WXr7EfugQy-IUSCdqHzqCNU0zVeHZomp8yIvO4/edit) from the German Open (which took place after that issue) has the following sentence that seems to imply no:

> Put the shelf and table close to each other such that they only require a rotation. 5 minutes is too little for what is being asked, and movement takes time.

2. Are there partial points awarding for placing an object on the shelf, just not next to a similar object?

**Comment by kyordhel** [comment]
## 1. Do we start from a closed door like other tasks? 
Yes. Teams start outside the arena and wait for the door to be open.

We can, however, agree otherwise during the team leader meeting.

## 2. Are there partial points awarding for placing an object far from its group?

No. The robot can ask where to place an object, so no points awarded for misplacement
