### ISSUE TITLE
Q: Is it allowed to take multiple object in Storing Groceries?

### ISSUE THREAD

**Issue by Jackey-Huo** [RoboCupAtHome/RuleBook#654]
Our robot has spare space in the belly and has the ability to take some objects with it. So Is it allowed for a robot to take multiple objects at once, navigate to the shelf, and place it one by one?

**Comment by kyordhel** [comment]
## TL; DR; YES

Humans rarely move one object at a time. We expect human-like behavior. When transporting objects, people commonly uses both hands, bags, baskets, trays, fingers, arms, armpits, hips, and whatever comes handy to ease the task. Robots can do the same, taking advantage of their own anatomy.

There is, however, little need for this in Storing Groceries since the table with the groceries will be placed near the table, approximately at grasping distance. Normally robots only need to turn.

**Comment by Jackey-Huo** [comment]
Got it, thanks for the quick reply~
