### ISSUE TITLE
Can we get the point even if the wrong objects are inserted in the right order? -- Smoothie Chef

### ISSUE THREAD

**Issue by kinmaru** [RoboCupAtHome/RuleBook#666]
In Smoothie Chef task, the robot has to take fruits in the right order, but can we get the point even if the wrong objects are inserted in the right order?
For example, can we get the point in the following case?
operator's request): apple → orange → banana
result): apple →  lime → orange → banana

**Comment by kyordhel** [comment]
# TL;DR: No.

I ask my robot for a strawberry smoothie.

Ingredients:
- Strawberries
- Sugar
- Milk
- Ice

My robot gets confused and pours also red hot chilli peppers instead of strawberries. Did I got my strawberry smoothie? I'm not sure, but the robot goes to the box and back to the factory.

Basically, if we allow wrong objects in the recipe, a robot can do *everything in* and expect scoring. Besides, robots can rely on DeM if the recognition confidence is too low.
