### ISSUE TITLE
Receptionist - Announcing John

### ISSUE THREAD

**Issue by syedaraza** [RoboCupAtHome/RuleBook#669]
2 hours before receptionist start, the OC will "Select and announce a volunteer as John".

Is John's drink preference included in the announcement (i.e., so that we can properly introduce John to the first guest)?
Will John make him/herself available for training/registration during the 2 hours?

A similar question was asked here https://github.com/RoboCupAtHome/RuleBook/issues/495#issuecomment-480492631

**Comment by moriarty** [comment]
No, we’re not going to waste John or Jane’s time and allow teams to collect datasets of them.

This task functionality has been shown in previous RoboCups, single shot training and recollection.

**Comment by johaq** [comment]
Yes, John's favourite drink will also be announced.

**Comment by syedaraza** [comment]
@johaq got it.

@moriarty ok. will this (one shot) training be done during the 5 minutes of the test? Or the teams will have John available for training 2hr before the test? The test says 'John is already known to the robot' which implies that training john should not be a part of main test's time.

**Comment by kyordhel** [comment]
Just as the rulebook says, we will tell teams who’s gonna be John 2h before the test.

**Comment by benatuts** [comment]
@kyordhel The rulebook isn't clear. If it were people competing (rather than robots), I would expect it would be reasonable to ask John to come over and shake hands with the competitors. However, if John is a VIP then human competitors might only expect to be able to see him from afar.

Social norms are less clear when we have a robot -- is it reasonable to expect that John will comply when asked to come meet and "shake hands" with a team's robot? Or will teams only be able to note identifying characteristics from afar?

Clarity is important because 2 hours is not a lot of time to adapt if our expectations are wildly different from that of the referees or of John.

**Comment by kyordhel** [comment]
Okay then. Prepare considering you’ll have to train John during the test within your five minutes.

If the rulebook says that the TC will announce John 2h before the test, you can expect we will do so in a way that john is known when the robot enters the arena in a fair and easy way for all teams. We might even allow a team member to be John. It can also be me, or even Chuck Norris in mind, so there should be no problem.

**Comment by syedaraza** [comment]
Allowing a team member to be John seems like a good idea. It will be reasonable and manageable for both teams and OCs.

**Comment by kyordhel** [comment]
Whatever decision the TC makes, it will be announced during the Team Leader meeting prior to the competition day.
