### ISSUE TITLE
Q: Start point in "Where is This?" 

### ISSUE THREAD

**Issue by sangtian719** [RoboCupAtHome/RuleBook#671]
I'm unclear about the meaning of "Right before a run at the entrance door, the team is told a position where they should **start** the robot."

This seems to contradict slightly with the start location: "The robot starts outside the arena. When the door opens, then robot navigates to the Information Point".

Could you explain how it might play out? 

e.g., The referee describes a location to the team, and then the team has a few seconds to communicate that to the robot (button/speech), then the test and timer starts when the entrance door opens?

Thanks!!!

**Comment by johaq** [comment]
Yeah this is little confusing since there was a change after german open. It will play out similar to this:
1. You wait with your robot at the entrance.
2. When it is your turn, the referee will tell you at the door where your information point is.
3. You then get your robot as fast as possible to that point. Pushing, carrying, remote control, whatever.
4. There, you start the task. Your start procedure needs to be approved during inspection.

**Comment by sangtian719** [comment]
Thanks!
This was so helpful for me!

**Comment by AdelaidaZC** [comment]
Thanks!

**Comment by justinhart** [comment]
Closing this, as it was settled at the team leader meeting at RoboCup.
