### ISSUE TITLE
Switch to YCB Object set for known objects

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#673]
Suggested on mailing list from Hiroyuki:

http://www.ycbbenchmarks.com/

I think this is a good idea.
Any other standard Object Set could be used however that is the one which was mentioned in the email.

We could still supplement the objects on site with unknown objects or a small number of known objects.

| Pros | Cons |
| ------ | ------- |
| Less late night training on site | Less variation each year |
| Compare results against outside of RoboCup | Cost (full 70 object set from YCB ~700$ ) |
| Reuse objects from event to event | shipping costs and storage of objects between events |

I've emailed with the maintainers of the data set about purchasing a set. The response:
> How many objects do you typically use? The YCB kit contains 77 items, so the cost of the materials plus our labor to maintain inventory, fulfill orders, etc., leads us to the price. We have been talking about possibly splitting the kit into smaller groups of items if that would increase adoption, so we could discuss that.

We typically use ~30 objects.

And some of our objects will be the same: eg: we'll always need a place setting - Fork, Knife, Spoon, Dishes set. I don't think we'll get complaints from the participants if we switch from our Fork/Knife/Spoon to the one in the YCB dataset, as we currently use plastic items or flatware and those ones are not flat.

The YCB Benchmarks data set is categorized into 5 categories here: http://www.ycbbenchmarks.com/object-set/ - we could use just 2 of the 5 categories, or perhaps even a smaller subset of those objects.

If we use a smaller portion of a larger standard data-set, this could reduce the costs for teams who wish to only use the data-set for RoboCup, but leave the option open for them to purchase the entire dataset for comparing and publishing outside of RoboCup.

**Comment by moriarty** [comment]
@LeroyR can you provide any additional arguments or contribute *pros* vs. *cons* to the discussion?

We were previously discussing this via e-mail and whatsapp, but wanted to open an issue publicly to gather more input.

**Comment by moriarty** [comment]
@justinhart and @kyordhel I've added you as assignee's here just to get your feedback- it was discussed on email/whatsapp but for the public audience.

**Comment by moriarty** [comment]
http://juxi.net/acrv-picking-benchmark/# also provides a decent standard object set, with some overlap from the above set but the 42 objects cost under 300$

**Comment by kyordhel** [comment]
I think @moriarty pretty much summarized the pros and cons of using a standard set of objects. On top of that I would add the following points to consider:

- Purchasing sets before competition may de-incentivize teams from sharing models (Trustees wonder why each team trains their own set instead of sharing models).
- Bringing pre-trained objects to the competition would mean:
    - @Home is not producing standardized data sets
    - Team have tuned their recognition algorithms, making recognition more robust and accurate
    - We would be voiding the *unstandardized scenario* standpoint of @Home
    - This might deviate us from the goal of having online (in test) object training
- Some team may have troubles purchasing the sets, even making them unaffordable
    - Additional customs tax
    - Possible custom blocks in some countries
    - Long delays in deliveries
- Potentially harder for the audience to understand since people will be unfamiliar with the objects (non-relatable objects).
- Using standard data sets would allow us to test performance with large object databases (not 70, but 700, later 7000, and beyond) which, eventually, robots shall handle.

Whether these points are pros or cons, is to the reader to decide.

In my opinion, RoboCup@Home is the space to test scientific research in a real-life-like setup, and not the other way around. Tests/Tasks address integration, so the number of variables in play make them hard to benchmark and almost impossible to produce *publishable* results. Our results are scientifically valuable nonetheless. Our competition sets one of the few spaces in which algorithms can be taken to the limit, outside the comfort zone of standard data sets due to the unexpected variety of products we may find in the market. In @Home, the 78% accuracy of YOLOv2 feels more like 56%.

It seems to me that the gain of incorporating a standard data set to the competition is scarce and doing so goes against the spirit of the competition. Furthermore, it somehow trivializes the role of object recognition in the competition. However, I am also aware that reducing the weight of object recognition (and arguably manipulation), can help to redirect efforts to other areas that haven't got enough attention.

Before adopting or vetoing the YCB set, I think it would be important to propose a roadmap for Robot Vision including, among others, object recognition. Some features that have been already proposed are: detection in low-light conditions, affordance recognition, best grasping angle, unrecognized object classification and inference, and online object training. The use of standard data sets should derive not from an isolated proposal, but from a long-term planning. Furthermore, this roadmap should be compatible with the roadmap for manipulation. This means that if robots must be able to *pour* sands or liquids into a container, the chosen set must consider such objects. The same applies to actions like adding sugar to a coffee, grabbing a tray, using a cloth or sponge to clean, etc. In this regard, the adoption of a standard object set as a partial solution (i.e. a few more objects are added during the competition) is also feasible.

Conclusively, I think it is of the uttermost importance to come out with the aforementioned roadmap before taking a final say on the topic. Should the milestones of the roadmap benefit from the adoption of a standard object set, I would be the first one in backing up the decision.

**Comment by nickswalker** [comment]
The food and kitchen sets look very reasonable. Maybe with some leg work we could source this subset more economically. Adding local items would probably still be necessary and desirable to maintain the spirit of the competition.

![](http://www.ycbbenchmarks.com/wp-content/uploads/2015/08/Food-items-1024x728.jpg)

![](http://www.ycbbenchmarks.com/wp-content/uploads/2015/08/Kitchen-items-1024x759.jpg)

Another thought on alignment with the real world: in the future, there will be a class of objects that the robot already has a highly detailed model of, either because they're so common that robot makers go out of their way to produce them, or because manufacturers see it as a feature to make the models available to help automation. Including YCB objects is also a way of representing this class of objects in the competition.

**Comment by johaq** [comment]
I'm not a fan of the idea. My reason is one that @kyordhel already touched upon. My understanding of @home is that it is supposed to bring lab research into real world scenarios. This feels like the opposite by adjusting our scenario to the current state of research.

**Comment by justinhart** [comment]
It wasn't just Hiroyuki who mentioned this. @komeisugiura also discussed this with us while we were at RoboCup.I think that @nickswalker is right with trying to source only the subsets of items that we need, and finding good sourcing to save money.

There are a few benefits that @komeisugiura brought up.

1. Teams spend time annotating objects and training them into YOLO during the competition that could probably be better spent.

2. Every year RoboCup spends money on objects placed into the arenas.

3. We can probably do more interesting object recognition demos and research if the items are known ahead of time.

I really think that this is a toss up, and that it will be more easily answered in the future when we have a more solid roadmap.

**Comment by kyordhel** [comment]
If I recall correctly, what @komeisugiura suggested was to 1) foster teams to exchange models of the arena objects, and 2) have the league buying only one example set and teams contributing with the rest. Neither of these points prevent us from having a standard set or using new objects each year.

I must say I absolutely support Komei's standpoint. Whether we use standard object sets or not, we must foster a league-level joint effort.

**Comment by johaq** [comment]
We basically have three options now. Fully standardized, partly standardized, and not standardized. Fully standardized is too much of a change for EC this year so we vote between partly and not at all. 
Deadline is 02.08.
Eligible to vote are all committee members. Majority option will be presented to EC for review and then assigned to TC for implementation.

**Comment by johaq** [comment]
My vote is for **not standardized**

**Comment by johaq** [comment]
TC vote is: keep non standardized objects.

**Comment by peterpena** [comment]
@johaq the new TC members were subscribed to this thread after your comment 7 days ago. May we reopen and have a proper vote?

**Comment by johaq** [comment]
It's fine by me but don't you get notifications for all issues? You cannot rely on people tagging everyone everywhere. 
I reopen the vote until friday 09.08.

**Comment by nickswalker** [comment]
My vote is for **partially standardized**.

**Comment by peterpena** [comment]
@johaq We do get notifications after we are subscribed.

My vote is for **partially standardized**.

**Comment by peterpena** [comment]
In real world scenarios, there will always be standard and non-standard objects. We can not always expect every item at home to be an unknown object. Having teams train the robot for every item in a household in < 2 days seems unrealistic and wasted time for teams that can focus on other areas to improve their performance.

**Comment by johaq** [comment]
Maybe I should give my reasoning for no standardization as well:
Firstly a service robot should imo be able to learn new objects reasonably quickly. As a manufacturer I do not want to limit myself to certain markets by being limited where standard objects are available. As a consumer I do not want to rely on software updates to support needed objects.
Secondly and more importantly why I am very much against the mix is because of the rule overhead it creates. Do we have to make sure there is always an even number of standard and non standard objects present? Does recognizing and handling a non standard object give more points? Can teams opt out of having non standard objects there?

Honestly if you have someone taking pictures of objects for two days straight you are probably doing something wrong and I would like teams to come up with ways to avoid that which touches on very important research topics such as learning with small data sets (https://arxiv.org/abs/1901.09054) and data augmentation (https://arxiv.org/abs/1712.04621). I would much prefer teams come up with object recognition solutions that are useful for adaptable robots instead of every team using the same yolo net.

**Comment by kyordhel** [comment]
# No voting in GitHub

Please. Let's reserve issues for discussion and keep the poll separate so we can see the results live, clean, and easy to update should someone change their mind.

@johaq please make an open poll and send it to the TC mailing list (e.g. with easypolls.net). Only TC members are allowed to vote. Options are
- Fully standardized
- Fully non-standardized
- Semi-standardized (e.g. 50-50)
- I don't care!

# Work plan
1. We run the poll till August 12th, 2019
    - Should a TC not vote, automatically waivers their role as TC
2. We re-run the voting poll with the top 2 candidates to make a final decision
    - Deadline is August 16th, 2019
    - Should a TC not vote, automatically waivers their role as TC
3. If TC votes to use an standard object set in the competition, we open an issue to discuss which set will be chosen.
    - EC expects at least 3 different proposals
    - A partial object set is available
    - As cheap as possible
    - Worldwide shipping, paying special attention to key countries (finalist team in the past 4 years):
        - China
        - EU
        - Japan
        - Mexico
        - South Korea
        - USA
4. Once we have candidate object sets, TC votes and decides.
5. The official announcement is made on the website and mailing lists

# Considerations:
- **No big changes:** The selected object set is [vaguely] mentioned in the Rulebook. It will be used during the competition. Detailed information will be available in the website. This is because whatever set we choose, it must have little to no impact on the rules.
- **Zero-tolerance to discrepancies**: A standard set is standard. German, Chinese, and Spanish cans of coke cannot be exchanged.
- **Donations:** Teams are required to donate objects for the competition. The LOC cannot be made responsible of providing standard object sets.
- **Caduceus objects:** Caduceus objects, cannot be part of the standard object set (e.g. apples, pears, etc).
- **Test-specific objects:** Objects that are meant to be used for a specific, particular test cannot be part of the standard object set unless @Home produces a standard set for scientific use.

**Comment by peterpena** [comment]
I agree that @Home teams should not be taking pictures of objects for two days, but data is needed for convolutional networks and the more human resources there are, the easier it is to attain it. With convolutional neural networks, detection has improved drastically and as long as you can feed it enough data, you can get great results. I also agree that that current research is looking into ways of eliminating the need of huge amount of data to train convolutional neural networks, but we cannot put this burden on all teams as a point of entry to perform at RoboCup@Home. There are still important research questions that needs to be solved after object detection and without being able to see anything, they cannot rbe addressed at RoboCup. The truth of the matter is it is still a research area, and our current setup of all non-standard items has not really shown to be effective and teams (especially smaller teams) are blocked from showing and testing the rest of the system. There must be other ways to incentivize teams to seek solutions to data reduction for object detection and I think partial standardization is a first good step towards this direction.

**Comment by LoyVanBeek** [comment]
I'm in doubt: @Home is about integration of a many skills, of which object recognition is just one of many. Spending much training time on that thing alone is maybe out of proportion. 

Also, this means you have an implicit contest going on in your setup days: who can train objects the fastest? 

Given that there are only limited objects available, I'm kind-of impressed with everyone's cooperation that 'contest' hasn't been a bigger issue before. 

My suggestion would be to have a standardized object set and add in some 5 local objects too that have the same probability of appearing as the standardized ones, which also do not give a bonus. Object recognition and training is then still a capability you need, but takes less time. 
So: semi-standardized.

**Comment by moriarty** [comment]
> TC vote is: keep non standardized objects.

When/Where was the vote?

If still open: I am in favour of **partially standardized** with most objects being known in advance: eg 75/25 or 60/40 Known in advance/Trained on-site.

**Comment by kyordhel** [comment]
@moriarty 

# Voting poll open in Telegram's TC group

**Comment by justinhart** [comment]
I need to get added to the TC Telegram.

**Comment by nickswalker** [comment]
After looking around at import restrictions, it seems like the hardest thing we'd have to deal with is food items. But it should be fine as long as we stick to non-perishables. Stable sourcing will eventually be a problem no matter what we do. It's preferable to work within the limits of existing community object sets, that way we can follow their lead on substitutions. 

Here's my proposal for a 14 item subset of YCB:

![687474703a2f2f7777772e79636262656e63686d61726b732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30382f4b69746368656e2d6974656d732d31303234783735392e6a7067](https://user-images.githubusercontent.com/924295/63896910-6b190000-c9a8-11e9-9fd8-d1e66908f9d6.jpeg)
![687474703a2f2f7777772e79636262656e63686d61726b732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30382f466f6f642d6974656d732d31303234783732382e6a7067](https://user-images.githubusercontent.com/924295/63896911-6b190000-c9a8-11e9-9345-4bebee640295.jpeg)

A bunch of pantry/grocery items and a couple cleaning items. We would supplement with fruit, local drinks and snacks. I'm not sure if there's as much value in the pitcher, but it seems like a nice thing to standardize as well. Grocery store cost of these in the states would be less than $30, so I think even with markup, pricing could be reasonable if Amherst were to agree to sell sets to teams.

I think we should consider officially marking the Ikea dishes, cups and utensils standard for 2020, since it seems to have been informally standard anways. The YCB equivalents are harder, but could imaginably be adopted in the future.

**Comment by moriarty** [comment]
I’m also not in the TC telegram group.

Also- I’m still in favour of this but didn’t have time to put together a PR

**Comment by kyordhel** [comment]
@justinhart @moriarty you're now in the Telegram Group

@nickswalker There is a big No-go for the Windex and Soft-Scrub. Several countries have strict regulations regarding import of chemicals and that include cleaning products since some have compounds that can be used to make explosives. Not sure if it's viable that provider sends empty bottles, specially since the cilour of the liquid can differ.

### Proposal
In addition to that standard set, I would like to propose this one, created and maintained by @Home alone

![image](https://user-images.githubusercontent.com/8583949/63934617-0b7c2c80-ca5c-11e9-96cc-5d69e6ba9a92.png)

IKEA KALAS 2019 tableware for children:
- 6 dishes $1.99/€1,99/₤1.25/¥199
- 6 bowls $1.99/€1,99/₤1.25/¥199
- 6 cutlery sets $1.99/€1,99/₤1.25/¥199
- 6 cups $1.99/€1,49/₤1.25/¥199

Uglier than previous version, resistant, durable, color-segmentable, hypoallergenic, designed for kids, cheap.

**Comment by moriarty** [comment]
The Vote by TC was for some portion of YCB Dataset and some portion of objects bought on site as previous years.

**Comment by moriarty** [comment]
I ordered an object set, and it arrived yesterday, the Windex / SoftScrub / Etc. were emptied prior to shipping to avoid any issues.

Actually the entire set was shipped in a nice box for storage and transport.

**Comment by MatthijsBurgh** [comment]
Has there been a decision on which subsets of YCB set? I see that @nickswalker proposed a subset. If there has been a decision, we should email all the teams, so they can order there set.

**Comment by moriarty** [comment]
@MatthijsBurgh no that was still being discussed by TC, I haven’t kept up with the discussion, but I thought it best to let teams know sooner in case they just order the entire set, or go out and buy close enough substitutes from local markets.

All the models and collected data from the dataset is available for free, so you can train now on the entire set.

**Comment by kyordhel** [comment]
#709 kinda solves this issue. I'll keep it open till the website has been updated.

**Comment by airglow** [comment]
Maybe a bit late to the party :). I created a dataset from objects by IKEA as a part of publication for IROS later this year ([Preprint](https://arxiv.org/pdf/1905.06002.pdf)). The whole dataset is around 50$. The original purpose is the evaluation of imitation learning tasks (quite similar to the Smoothie Chef task).  Of course it could be re-used for mobile manipulation tasks.  The objects in this dataset can be combined to a variety of actions like cleaning a table using a sponge, setting a table, watering plants, cleaning a floor using a dustpan, ironing cloths, filling a washing rack .... Basically a set of common activities in a domestic environment. Some of them come in variation of color or shape (this comes along with the "alike" category from RoboCup@Home).

![objects](https://user-images.githubusercontent.com/1682186/66322623-b668eb80-e922-11e9-9c4c-93373988cb4a.jpg)

Those objects have been used for the dataset. An exact list can be found below. Pre-trained models for yolo and MaskRCNN are provided and training data is provided on pixel level image segments. By this teams can also compare their models and data augmentation methods against other ones or a baseline. 

Benefits for RoboCup@Home: it's very cheap and easy to acquire in most countries (see [IKEA map](https://en.wikipedia.org/wiki/List_of_countries_with_IKEA_stores#/media/File:Map_of_IKEA_stores.svg)). Further should be ship-able without issues as no foods are part of this dataset (AFAIK this is a problem with the YCB dataset). It should even be possible to take them in a suitcase. 

| Name         |  Number       |  Type                                   
|--------------| --------------| --------------------
| 365+         |  604.063.04   |  plates                                 
| JÄLL         |  202.428.90   |  ironing board                         
| BITTERMANDEL |  204.323.81   |  vase                                  
| STEKA        |  926.258.00   |  pan                                   
| PS 2002      |  303.879.72   |  watering can                          
| LILLNAGGENA  |  402.435.96   |  Shower squeegee
| FÖRDUBBLAA   |  903.459.41   |  2-piece knife set
| HEAT         |  870.777.00   |  trivet
| ANTAGENA     |  202.339.61   |  Dish brush
| BLASKA       |  701.703.29   |  Dust pan and brush
| GNARP        |  303.358.41   |  3-piece kitchen utensil set, black
| SVAMPIG      |  602.576.05   |  sponge
| FLUNDRA      |  401.769.59   |  dish drainer
| FÄRGRIK      |  003.189.56   |  mug
| VISPAD       |  602.575.25   |  colander
| GLIS         |  800.985.83   |  box with lid 
| FEJKA        |  903.751.55   |  Artificial potted plant 
| GUBBRÖRA     |  902.257.31   |  Rubber spatula

Table:  Object list for Simitate

**Comment by moriarty** [comment]
@airglow sorry you are late to the party. Their was a vote in the TC Meeting and the YCB object set was chosen, it is only undecided what subset of the YCB objects will be used.

**Comment by LeroyR** [comment]
It is not possible to order a subset of the YCB object set. Also the cost is 700$ + shipping / customs / VAT (carbon footprint?).

Instead of going to a random discounter and getting some test objects for 20$(we can eat/use afterwards) we have to order this thing months in advance for costs outside any reasonable budget. 

All containers are cleaned/empty for international orders. Which ones will be used in the competition full or empty? Do we refill the windex with something blue so it matches?

**Comment by moriarty** [comment]
All containers are also cleaned & emptied for domestic shipping inside of USA aswell.

You can go out and buy a subset of the objects yourself, and just buy the ones which you think make sense.

The 700$ is actually the approximate cost of the items if you go out to local shops in USA and buy them.

I’m strongly pushing for these objects as they’re more realistic and varied than the Ikea alternatives.

**Comment by johaq** [comment]
Well, you can't if you are not in the US.

**Comment by LeroyR** [comment]
> All containers are also cleaned & emptied for domestic shipping inside of USA aswell.

so we use emptied objects for the challenges, that's a step back. 

How does recognition work if the training data contains filled windex bottles? 
As you cant purchase the objects locally, how do we handle if (emptied) containers get destroyed by customs?
Are the teams still able to learn/test with the objects at the cup if they choose to not purchase the 700$ kit and used 'just similar' items during preparation?

**Comment by kyordhel** [comment]
This is an official statement.

All objects with chemical products and other liquids shall be stored and
transported empty, and will be filled with water during the competition.

**Comment by johaq** [comment]
Switched to YCB standard objects for 2020. Obtaining the objects can be discussed here: #719. 
Please open new Issues for problems and discussions to keep things more focused.
