### ISSUE TITLE
Future of cloud computing

### ISSUE THREAD

**Issue by maximest-pierre** [RoboCupAtHome/RuleBook#676]
I just want to point out that most teams are now heavily dependent on cloud computing (AWS, Google, and Baidu). When the internet goes down most robot won't work.

Even if the rulebook says that you must have a local backup for this exact case, in practice almost nobody actually has it. 

I feel that the teams are just paying for a pre-made solution instead of doing some actual research. 

Should we continue to allow cloud computing in AtHome?

PS. Cloud computing is different from an external computing device that is physically in the arena network.

**Comment by LoyVanBeek** [comment]
What kind of cloud services are being used? Are there local-running alternatives for those?

**Comment by kyordhel** [comment]
Some questions arise.
1. Is this happening in SSPL only?
     - I haven't seen such behavior in neither OPL nor DSPL.
     - Top OPL teams rely on standalone features running in the robot.
     - Top DSPL teams implement standalone features running in the backpack.
2. The backup is a *should have* feature. If the team has no backup, the robot won't score.
    - Enforcing this policy would be a logistical nightmare during robot inspection.
    - Even after the inspection, we can't no guarantee that the fallback module is running.

Although I strongly oppose to external/cloud computing, I don't see any other way to make a Pepper run decently. Furthermore, even though all three leagues enthusiastically tried on-line solutions in 2017-2018, network conditions make them unpractical.

As of now, I would rather promote a cloth schoolbag for pepper with an Alienware inside, rather than banning cloud services. I might not be a big fan of them, but if teams want to try Amazon/Google/Whatever online solutions, it's their call.

**Comment by maximest-pierre** [comment]
1. This year was an awesome year for the internet. I only saw it once or twice during SSPL that we had to stop because of no network connection. 
2. There is no practical way of knowing this short of pulling the plug from the access point.

For the pepper, if the teams want to have a cloth bag with a gaming laptop they should suggest it.

**Comment by johaq** [comment]
With regards to pepper we had a running system on pepper that did not rely on the network at all. Afaik it is the same for UTS. So it is definitely possible but I think additional on board computing would be a huge help here.
When it comes to cloud services, I'm kinda in favor of getting rid of them. My biggest issue is that it makes a lot of rules not enforceable. Yes, we already rely on teams playing fair and there will never be a way to be sure nobody is cheating but with cloud services allowed it just opens so many possibilities.
On the other hand cloud services have the clear advantage to allow new teams to use a ready and proven solution to focus on other necessary abilities of which there are a lot to even start competing in @home.

**Comment by kyordhel** [comment]
Indeed, but although integrating Cloud Services is scientifically irrelevant (you can't get any publication out from it), these solutions work almost out of the box. In contrast, tuning a system to run in a low-end computer requires a huge time investment and research, yet it's barely acknowledged in the academia (if at all). Therefore, I think the option should remain open as it is valuable for research groups with limited budget, personnel, or heavily oriented research lines.

In addition, several teams would like to access their custom computing resources available over the internet (e.g. accessing your university data center) in order to test their algorithms in the competition. This, I think, is the most valuable addition of allowing online computing in the competition.

**Comment by LoyVanBeek** [comment]
That was exactly the reason for me to advocate cloud services before approval a couple of years ago. I have become less enthusiastic about cloud computing for practicality reasons like those mentioned above, but @Home is about integration. 

There is a lot of stuff to get working, which are all just part of the puzzle. Even if your object recognition is in the cloud and has 100% accuracy, there is no guarantee it will give you any points if your grasping is off. 

It is an interesting warning though that the top teams run everything as local as possible, maybe a big(ger) warning in the rules is a good thing.

**Comment by RemiFabre** [comment]
I'm in strong favor of cloud services (even if we don't use them). In addition to the points already made here, I'll add this one:
@Home is an application driven competition. If having access to the internet allows the robot to become actually useful in a home then great. WiFi is certainly available in most houses that would use a service robot today. 
The task is hard enough for now. We should, in my opinion, use anything that works and makes sense.

On the other hand, I believe robustness is key and relying blindly and solely on cloud services is a dangerous bet for now.

**Comment by justinhart** [comment]
I think that we should continue to allow cloud computing. It's not that using cloud computing adds research value. It's that bypassing it's use creates busy-work. My group doesn't research speech-to-text technology. There's no reason for us to invest time in speech-to-text technology. We are unlikely to begin to publish on speech-to-text technology. We use Google Speech to bypass needing to develop something. Groups will invest research energy into the problems that they research. As @LoyVanBeek points out, the top teams seem to run everything locally, and that's a good strategy, but I don't see it as a reason to mandate that teams not use cloud services.

**Comment by maximest-pierre** [comment]
My only major problem is something @johaq said regarding enforcing the rules. Currently, a team can use "cloud computing" to send a video stream back to a cloud provider or a teammate to manually classify. We have no way of distinguising genuine cloud providers, a teammate or a human.

**Comment by justinhart** [comment]
Cheating is already against the rules, so they would have to hide this from
us regardless of rules against cloud computing. If they intend to cheat,
they'll do it with our without additional rules.

**Comment by LoyVanBeek** [comment]
If you really want to cheat, you could just as well hide a network dongle with 4G SIM-card in your robot to always be connected to the internet.

**Comment by kyordhel** [comment]
Whatever. *How to cheat* is off-topic.

It seems the *plethos* is all in allowing Cloud Computing and, since we are a democracy, it's very likely to stay. Before closing this issue, nonetheless, shall we discuss the topic in the next TC meeting? @justinhart, @moriarty please speak your mind.

**Comment by awesomebytes** [comment]
As @johaq said, UTS could run 100% offline too, and I'm pretty sure UChile could too... it's just a massive burden to fit everything in that computer. I'd keep Cloud computing. As @justinhart also mentions, it helps to solve some stuff that some research groups won't invest into, like Speech recognition.

**Comment by justinhart** [comment]
I respect Maxime's opinion, but I don't think it needs to go to the
meeting. I see this discussion dragging out if introduced at the meeting.

**Comment by moriarty** [comment]
Long story short:

Let’s keep cloud computing.

If it doesn’t work and they don’t have a backup: too bad, no points.

It’s as difficult to enforce and regulate as any of the other external compute devices, but that’s too bad- we’ll just need to deal with any issues during competitions.

I’ve typed and deleted several responses to this issue: and agree with Justin- let’s not discuss it in a meeting it will be a lot of talk and we likely won’t change anything.

Both SoftBank and Toyota were strongly in favour of cloud computing. I don’t think they wanted to see the backpack on the HSR, because in a typical household network environment the communication with the cloud resources would be reliable.

**Comment by kyordhel** [comment]
Since we agree, cloud computing stays.
