### ISSUE TITLE
Faking Robot Rule is Never Enforced

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#725]
Currently we have this rule:
**Faking**: If a team starts a test, but it does not solve any of the partial tasks (and is obviously not trying to do so), a penalty of \scoring{\penaltysmall points} is handed out.
The decision is made by the referees and the monitoring TC member.

Personally I think this rule is confusing as is shown by new teams repeatedly asking for explanations of this rule. Furthermore, this is never enforced. I have never seen a team get this penalty even though I have seen plenty of times when a robot did not even enter the arena. We of course do not give the penalty because we do not want to punish the team for having a malfunction. Still, as a referee I can not know whether the team had a malfunction or just pushed their robot to the door knowing it would not do anything. So either we actually enforce this rule which means this penalty gets applied to every run where the robot does not score or if we do not want to do this, we need to remove this rule.

**Comment by RemiFabre** [comment]
What is the goal of the rule? Reducing how often a passer-by sees a robot not doing anything?

**Comment by Slothologist** [comment]
From what I can gather it's also about bypassing the penalty of not attending a test (see basically any scoresheet and section 3.9.1.2). So in theory without this rule if you did fail to announce not attending a test in advance, you could just roll the robot to the starting area anyway and not get the 500pt penalty. With this rule you would discourage people to do just that. (It is not clear for me however, why the penalty of this rule is only 250pt, it should at least be more then 500pt, otherwise it's an encouragement to show up and waste everybody's time.) Additional benefits include time saved for referees and volunteers and -as you pointed out- lame robots.
In practice however, it is oftentimes not even clear for the teams themselves why their robot did nothing when starting the test. So when would it ever be obvious for the referee? Additionally, teams spend valuable time bringing their robot to the arena, waiting for their turn and partaking in the tests. So there is already an indirect bonus to just skipping test which you know you would not score in.

**Comment by johaq** [comment]
Well, as a referee I can't tell whether the team did that. So the rule is pointless.

**Comment by DavidPL1** [comment]
I agree with @johaq. One cannot possibly tell by looking at the robot if it is faking or actually having an issue. So either the penalty has to be applied always or not at all. And I guess that if the penalty is always applied instead of robots doing nothing we won't see any robot at all, as trying to solve a task is rather punished than encouraged.

**Comment by RemiFabre** [comment]
I agree with everything being said.  I would change the rule so that the referee can stop the test early but without any extra penalties:
"If a team starts a test, but does not solve any of the partial tasks (and is obviously not trying to do so), the referee and the monitoring TC member can stop the test before the end of the allowed time."

**Comment by Slothologist** [comment]
That's already included in a more broad way into 3.7.14.3:

> **Inactivity**: Robots are not allowed to stand still or get stuck into endless loops. A robot
not progressing in the task execution (and obviously not trying to), is consider as inactive.
Robots must be removed after 30 seconds of inactivity.

**Comment by johaq** [comment]
I'm surprised about the limited feedback.
Are all other teams fine with receiving a 250pts penalty if their robot does not move during a test or if it does not score during a test?

**Comment by ARTenshi** [comment]
I think this rule is more about teams trying to get bonus points only or not completing the core of the task (e.g. asking for human help to solve more than half of the task). This rule prevents those cases, I think.

**Comment by alex-mitrevski** [comment]
I agree with @RemiFabre; the test should be stopped early, but without extra penalties. Otherwise, I think this rule makes an assumption that teams are trying to game the system for collecting points rather than solving the tasks, which I hope is not the case.

If, as @ARTenshi mentioned, teams are trying to collect bonus points without solving the main part of a task, I suppose they should not get any points for the task, i.e. the bonus points should be conditional on performing (at least a fraction of) the main part of the task.

**Comment by Slothologist** [comment]
> I think this rule is more about teams trying to get bonus points only or not completing the core of the task (e.g. asking for human help to solve more than half of the task). This rule prevents those cases, I think.

I severely disagree. 
Because the bonus objectives of a task are obviously part of that task, this rule ("If a team starts a test, but it does not solve **_any of the partial tasks_** (and is obviously not trying to do so), a penalty of 250pt is handed out.") does not apply. 

Furthermore, humans helping the robot is already pretty extensively covered in section 3.8 (Deus ex Machina: Bypassing features with human help).
A reduction of up to 30% of the maximum achievable(!) points is applied (3.8.2.3). This means if you try to game a 1000pt task for 100 bonus points, you are fined 300pt and get out of the task with -200. 

That however assumes, that you even _can_ abuse a task like this, which would mean imho that the task is badly designed. Upon skipping over the first few tasks of stage 1, It seems very difficult (if not outright impossible) to abuse them in this manner. 
Most of the times, the bonus points are given for a more difficult version of the main task, e.g. main objective: move an object; bonus objective: move a _tiny_ object.

**Comment by moriarty** [comment]
At one point, there was a penalty for not showing up for the scheduled test.

Teams would just keep hacking away until the last minute, and then we'd call them into the arena, and they would be still at their tables and tell us they were not going to participate in the test... So before we started each round of tests, we asked the teams who was planning to participate, then we created the schedule and posted it.
Teams were not allowed, to try to squeeze into the schedule at the last minute.

This rule, was to discourage teams from committing to test, getting scheduled for the test, but really not being ready for the test and showing up and not doing anything... 

We care about teams showing up for tests, and doing well in there tests. We want to try to schedule as accurately as possible, to give teams who are prepared the most time to do well.

@johaq If this rule is causing confusion just remove it.

Ideally what we want to get get to, is robots consistently solving tasks, no point farming, no "Deus ex Machina", basically binary scoring: task solved = 1, task not solved = 0... and then maybe maybe apply some weight.
