### ISSUE TITLE
Restart Rule Application

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#726]
So currently the restart rule is only applied to the restaurant test.
I think if we have the restart rule it should be applied to all Stage 2 tests.

**Comment by RemiFabre** [comment]
In that case, it could be a RuleBook wide rule. It's just that a severe external interference almost never happens outside of the restaurant test. But, if a hooligan jumped over the apartment wall and messed with a robot, it would make sense to repeat the test, even if it's a Stage 1 run.

**Comment by johaq** [comment]
You don't need interference for the restart to happen. It is up to the team.

**Comment by RemiFabre** [comment]
Indeed. I got confused with this sentence that only the Restaurant task has: 
"Disturbances from outside:
If a person from the audience (severely) interferes with
the robot in a way that makes it impossible to solve the task, the teams may repeat the
test immediately."

In that case, what does "when the test slot permits it" mean? Does it means that if we're out of schedule then restart mechanic is off?

Teams might start restarting as soon as they think they can do better with a rapid parameter tuning (I would). I'm afraid this will mess up the test schedules. If you want to go though with this, we need a way to prevent point farming. Yet this restart mechanic is good because it prevents silly mistakes to ruin a run (like @cduss forgetting to plug a cable, or forgetting to change the test coordinates).

I would replace the sentence:
"Scoring:
If the score of the second attempt is lower than the score of the first one, the
average score of first and second run is taken."

By:
"Scoring:
After a restart, only the score of the second run will be considered. A 20% score reduction will be applied on the total score."

**Comment by johaq** [comment]
when the test slot permits it means that the test allows a restart. I rephrased it less confusing in current version of #722.
