### ISSUE TITLE
Share trained models

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#745]
## Is your idea/suggestion related to a problem? Please describe.
During (physical) RoboCup setup days, teams learn the new objects etc. But each team needs to do this for their own robot.

## Describe the solution you'd like
Would it make sense for teams to share the trained models? This competition being about open source etc. 

## Describe alternatives you've considered
Share the data used in training, but that is typically a *lot* of data. Ideally both model and training data are shared. 

## Additional context
RoboCup@Home tried doing data sharing a couple of years ago and it was more work to me as TC than there was any benefit to any team back then. But given https://modelplace.ai/models and https://huggingface.co/models and other, this might work better.

**Comment by alex-mitrevski** [comment]
I support the idea. We (b-it-bots) always share models that we use in a competition or in published work (provided that a model is good enough to be of any use to others). We currently have a dedicated repository for this (https://github.com/b-it-bots/mas_models), but we are open to other options as well.

Sharing training data is trickier because of the data size (after augmentation). But our augmentation code is also available (https://github.com/b-it-bots/dataset_interface), so other teams are welcome to use it and train their own models on the generated data.

**Comment by LoyVanBeek** [comment]
The data sharing is difficult since it requires some structure to the training data too (eg. labels and bounding boxes and whathaveyou), which was lacking (my/our bad, in retrospect).
