### ISSUE TITLE
Q: Do operators wear masks during tests?

### ISSUE THREAD

**Issue by hskAlena** [RoboCupAtHome/RuleBook#749]
## Summary
Do operators wear masks during tests? That might impact person identification performances.

## Details
For example, tasks like "5.3 Farewell" in 2019 rulebook require person identification, mainly using facial information.
However, wearing masks will hinder using facial information, so I'd like to know whether operators during tests wear masks or not.

**Comment by alex-mitrevski** [comment]
Hi @hskAlena, it will have to be possible for operators to take their masks off during tests; we wouldn't want to have this new challenge that would distract from the main task objectives.

**Comment by MatthijsBurgh** [comment]
Then I have a follow-up question. Are the operators not wearing any masks at all in such challenges or will the robot need to ask for the operator to take it off?

(I don't think there is any mask rule in Thailand at the moment, so probably also not during RoboCup. Of course people are free to choose to wear a mask.)

**Comment by alex-mitrevski** [comment]
There won't be a need to ask; our working assumption is that the operator as well as the volunteers will be without masks in the tests where interaction is an essential part of the challenge (such as `Find My Mates` or `Farewell`). Operators are, of course, free to wear a mask during the tests in which interaction is not required (e.g. `Storing Groceries`).

**Comment by MatthijsBurgh** [comment]
@alex-mitrevski thanks!

**Comment by maximest-pierre** [comment]
So I did a bit of research and Thailand still has a mask mandate for both outdoor and indoors in effect at this moment with fines. As with everything related to this global situation things will change without notice. 

We would need to confirm with the LOC and venue about safety precautions related to masks.

**Comment by alex-mitrevski** [comment]
@maximest-pierre That may be true for now, though they were preparing to relax the rules last time I was reading about that. In any case, our TC opinion is that it would be a major change to have masks _in the tasks_ since, as I said before, it would be a distraction from the actual task objectives. Essentially, we don't want to turn RoboCup@Home into a competition for "person recognition with masks." So, if necessary, an exception has to be requested for this (not sure who is in touch with the LOC, but every scientific event I've travelled to during the pandemic has allowed exceptions, for example for speakers; I don't see a reason why this one would be different).

**Comment by maximest-pierre** [comment]
I was looking at both the UK government and the US government sites for travel restrictions. They are both pretty up-to-date with the current information.

https://www.gov.uk/foreign-travel-advice/thailand/coronavirus

I have the LOC email somewhere. I am going to send them an email asking about mask mandates for the event. I will also cc the whole OC, EC and TC. @alex-mitrevski

**Comment by alex-mitrevski** [comment]
Thanks @maximest-pierre!
