### ISSUE TITLE
Which version of the rulebook will the 2022 rule be based on? 

### ISSUE THREAD

**Issue by SJ-YI** [RoboCupAtHome/RuleBook#751]
At this point competing teams have roughly one month left until robot shipment, but we are still not told which rule to expect fot this year. 

-Current master version (updated 2 years ago) says there are 9 tasks, and some of  the objects will be from YCB dataset.

-Latest comment (https://github.com/RoboCupAtHome/RuleBook/pull/748#issuecomment-1045329087) says that 2022 rule will be based on 2019 rule (10+9 tasks) and only task scores will be adapted 

So it seems that there will be 19 tasks this year (the same as 2019), only with different task scores. Can someone clarify this? If then, when will the final task scores will be announced?

**Comment by alex-mitrevski** [comment]
Hi @SJ-YI, the rulebook version the TC has been working on is indeed based on the 2019 rulebook. The changes for this year are introduced with PR https://github.com/RoboCupAtHome/RuleBook/pull/748

I unfortunately don't know when the the final/official version will be announced since we haven't heard back from the reviewers yet. Please follow the PR in the meantime and sorry for the confusion.
