### ISSUE TITLE
Q: [Find My Mates: Photo as a description]

### ISSUE THREAD

**Issue by ikuzo198** [RoboCupAtHome/RuleBook#752]
In RoboCup 2019, it seems that a team got perfect scores only by showing a photo of a living room with a guest. [Youtube](https://www.youtube.com/watch?v=NHwkNndb9R8)

Is a photo of guests in a living room considered a description, or should the photo have a text or voice explanation?

**Comment by alex-mitrevski** [comment]
Hi @ikuzo198, we are after a textual description in this task; whether it's spoken or displayed on the robot's screen is less important. Showing a photo is technically not against the rules, but it goes against the spirit of the task, which is that of being able to recognise distinctive human features.

**Comment by yuzoo0226** [comment]
Hi @alex-mitrevski ,does the order in which the guest's information is given to the operator affect the score? Otherwise, Is it okay to give information about four guests simultaneously using a photo?
When describing the guests to the operator, is it necessary to give their names explicitly? If names need to be given, we believe that this should be specified on the score sheet.

**Comment by MatthijsBurgh** [comment]
Hi,

When you are talking about Tech United Eindhoven, let us join the conversation.

The current rulebook, the one from the PR that is not merged yet 😠, doesn't mention anything about the spirit of the challenge. So in my opinion this method would still result in full points.

I would also like to mention that the rulebook has changed over the last years to give more freedom to the teams on how to solve a task. instead of constraining the teams to solve a problem in just one way.

**Comment by rokusottervanger** [comment]
I'd reason that if a good solution for the task is "against the spirit of the task", the task is wrong. If you want to test a specific skill, you should either isolate that skill, or find a task where this skill is essential. This task is does not seem to be a great example of the relevance of the skill of describing distinctive human features.

**Comment by alex-mitrevski** [comment]
Thanks everyone for the feedback. I thought that the objective of the task was clear based on the task description, but I have just added a clarification about the expected description format to avoid confusion.

Please let me know if you don't think the change is reasonable.

**Comment by rokusottervanger** [comment]
I feel the challenge description is utterly inadequate at describing the scenario. What is the practical situation in which this task is at all relevant? Why would an operator want to know visual appearance features of (some of the) party guests? What practical situation do you envision to test here? 

The "spirit of the league" is to develop useful robots for daily life, is it not? Showing a photo of a person sounds like a great user experience when trying to communicate a person's visual features. Why not accept very usable solutions to real life problems, even though the are not what YOU as TC envisioned? It is up to the TC to state the problems, it's up to the teams to come up with solutions. Not the other way around. It doesn't sound "in the spirit of the league" to enforce specific solutions. Just my 2 cents...

**Comment by MatthijsBurgh** [comment]
> It is up to the TC to state the problems, and up to the teams to come up with solutions. Not the other way around. It doesn't sound "in the spirit of the league" to enforce specific solutions.

I totally agree with @rokusottervanger

**Comment by ikuzo198** [comment]
We agree too.
Thank you.
