### ISSUE TITLE
Make External Speaker Mandatory for DSPL

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#770]
This is a small thing but hibikino having an external speaker on their hsr makes it so much easier to referee their test.
I would make an external speaker mandatory for DSPL since the robot's internal ones are just not loud enough for the robocup setting.

Asking the DSPL teams: Is there a problem with this idea that I'm not seeing since I don't work with a hsr?

**Comment by MatthijsBurgh** [comment]
I am not sure how easy it is to implement. As I don't think there is a speaker port on the robot, atleast not on the HSRB version 5, which we have.

But maybe Hibikino could share their solution. This is something that should work on all HSR I think.

**Comment by akinobu1998** [comment]
We, Hibikino use an external USB speaker like the following.
https://www.elecom.co.jp/products/MS-P08USBBK.html
We connect the USB cable to the USB hub on the HSR. We also need to change the speaker setting on the HSR. We can share the details with pictures.
(FYI, we use HSR 71 and 91. This solution works for both HSRs.)

**Comment by fagnerpimentel** [comment]
In an older rulebook, an audio output plug was mandatory for use with arena speakers. I think we should bring him back.
```
Audio output plug
1. Mandatory plug: Either the robot or some external device connected to it must have
a speaker output plug. It is used to connect the robot to the sound system so that the
audience and the referees can hear and follow the robot’s speech output.
2. Inspection: The output plug needs to be presented to the TC during the Robot Inspection
test
```

**Comment by LeroyR** [comment]
As Far as i remember: On the old Biron Platform we had a case where, during competition, the external speaker caused inference with the sensors (robot odometry, tobi was rotating in rviz while standing still) :sweat_smile:

**Comment by ARTenshi** [comment]
Provided this connection problem has been solved by Hibikino, it would be a good improvement because, although it's a standard platform, it doesn't mean it should be an outdated standard platform. Furthermore, I would also like to apply this update to the mic, especially considering that the atHome league is moving towards GPSR (where voice commands are a key feature).

**Comment by johaq** [comment]
What is the current mic and why is it not adequate?
Is it easy to switch the internal mic or would you also propose to use an external mic?

I think we need to be somewhat careful to not stray too far from the standard platform idea. We already have the laptop and maybe a speaker. We need to make sure that any external parts need to be very easy to add. I think we ensured this for the laptop with the backpack design and I think it holds for plugging in a speaker.

**Comment by ARTenshi** [comment]
It's a standard microphone array (no brand is provided) so, now that it was mentioned, I just wanted to explore what improvements can be done to a standard platform to boost the level of the challenges (e.g. there is an official rdbd hand-camera tweak); in this context, maybe a directional mic can improve user experience (instead of having them repeating the voice commands or bypassing them with QR codes).

**I also see the difficulty of this because new teams should solve current problems using the provided hardware before thinking about new challenges.

**Comment by MatthijsBurgh** [comment]
I know the type of MIC, but I am not going to drop it here. As this issue is about the speaker. When we want to discuss about a different MIC, we should open a new issue.
