### ISSUE TITLE
Deus ex machina too penalising for SSPL

### ISSUE THREAD

**Issue by tomkimsour** [RoboCupAtHome/RuleBook#786]
## Problem description
Looking at the deus ex machina of grasping focused tasks like Storing groceries and Serve Breakfast, there seems to be no point for SSPL teams to even try the task as you wouldn't be rewarded for giving informations to the operator. 

For example in Storing groceries, say the robot ask to take the orange by pointing at it, moves to the cabinet and point where to place the object. The score would be of -100.

## Suggestion
Shouldn't there be a slight adjustment in order to give points for categorizing where to place the object by precisely pointing at the place (almost touching the surface it should be placed on)?

**Comment by LeroyR** [comment]
Yes, there should be points for recognition and showing/describing the placement. Also the goal and penalty section need to be clarified.

Currently the scores are inconsistent regarding penalties. Storing groceries has: +30 pickup and -30 for handover while Carry my luggage has +100 for picking up the bag but no penalty for deus ex machina (let the operator handover the bag.)

I assume 'A human moving an object' penalty means that the robot is still able to scores 20 points (30 from pickup, 90 from placement, -100 penalty) even without manipulation. While no specific penalty means 0 points for skipped goals. Otherwise entering the area scores more points (0), than instructing the human to move 5 objects to a possible wrong location (-800 :smile:)

Also, a human pointing at a target location is harder than object recognition.

**Comment by tomkimsour** [comment]
Sorry for not being clear I meant the robot points at where to place the object to the operator moving the object.

**Comment by johaq** [comment]
This is an issue that is somewhat difficult to fix, since the manipulation capabilities between standard platforms are so large and we want the same rules for all leagues. For this we might to discuss again if separate rules for SSPL might make sense.

> Carry my luggage has +100 for picking up the bag but no penalty for deus ex machina (let the operator handover the bag.)

You won't get points for picking up the bag if you ask for a handover in carry my luggage. Yes, not all possible DEM penalties are stated in every test. It is not ideal but also difficult to add every possible form of assistance.

> I assume 'A human moving an object' penalty means that the robot is still able to scores 20 points (30 from pickup, 90 from placement, -100 penalty) even without manipulation. While no specific penalty means 0 points for skipped goals. Otherwise entering the area scores more points (0), than instructing the human to move 5 objects to a possible wrong location (-800 smile)

This should be addressed with  #791
