### ISSUE TITLE
Q: Stickler for the Rules; Guests may not follow the robot’s instructions.

### ISSUE THREAD

**Issue by quetalasj** [RoboCupAtHome/RuleBook#802]
## Summary
What does ` Guests may not follow the robot’s instructions` mean in `Stickler for the Rules` task?

## Details
I see in #797 this question maybe was partially answered, but I would like to clarify some details.

1. It is clear that the guests may ask for additional information in case there is some ambiguity in robot's instructions but if the instructions are designed in the way that the ambiguity is excluded will the guests still asks additional information that may look unnatural in this case?
2. As I understand it is possible that the robot asks to follow him but the person didn't begin to follow the robot immediately or stopped during the following, however just long or continuous ignoring and violation of the instructions by the guest is impossible, right?

**Comment by johaq** [comment]
1. I cannot answer this definitively. In all tests referees and volunteers might ask for things that the robot already answered just because they did not understand the robot, did not pay enough attention, or forgot. We cannot guarantee how tests will go especially when HRI is involved and even more especially HRI with volunteers.
2. When guiding a person the robot needs to make sure that the person won't get lost. People will not outright ignore the robot's instruction unless the robot is rude or unclear.

**Comment by quetalasj** [comment]
Thank you for the answers!

Could you also clarify about this regular reward:
"Confirm that the guest is following the rule."

Is this reward for confirming that the person isn't get lost following robot's instructions?
Or is it for confirming that the same person doesn't break the rules again?

**Comment by tomkimsour** [comment]
Last year at least it was point for confirming the person does not break the rule again. So that was by saying either that the person did follow the rule or that the person is breaking it again.

**Comment by johaq** [comment]
See #797

**Comment by quetalasj** [comment]
Thank you!
