### ISSUE TITLE
Getting away from state machines (more open world)

### ISSUE THREAD

**Issue by PetervDooren** [RoboCupAtHome/RuleBook#805]
## Is your idea/suggestion related to a problem? Please describe.
Currently many teams use Finite state machines to do their challenges. This is not a problem in and of itself. However it often leads to a robot going through the same steps making extensive use of its knowledge of where things will be for a given challenge. Rather we'd like to move to challenges that are formatted more like Restaurant and Stickler for the rules.

- Issue outlined in TC meeting 31/07/2023

**Comment by PetervDooren** [comment]
For the most part this can be solved by ensuring the robot needs to react to at least some sensor information. For example the place where the breakfast must be served.

It can also be the way in which humans are instructed to interact with the robots. Now humans will follow the instructions of the robot even when the interaction is unnatural.

In general this is a problem that needs to be adressed per challenge. A solution that works for one might not work for another.

**Comment by sunava** [comment]
Perhaps we should go back to visualizing things; therefore, Visbox was originally designed so that referees could see what the robot perceived. If this is not possible due to network issues or other reasons, it should appear on the robot's display where it perceived an object. Furthermore, any type of human-robot interaction should proceed in a way where the robot doesn't say, "please give me the milk," but rather, "please give me the milk on the top-right shelf, third row."

If the robot does not follow these given rules, the referee will not acknowledge it. Only in this way can we ensure that perception was genuinely used and that there is a certain knowledge base on the robot. Additionally, unknown objects that do not belong to the challenge should be reintroduced and should not be used. For example, in a "serve breakfast" challenge, there could be ice tea on the shelf. Therefore, for each challenge, we should clearly define what is allowed in terms of visualization and human-robot interaction to prevent situations where the robot simply says, "please give me the spoon," and the spoon is obviously part of the task, so it will be there.

**Comment by sunava** [comment]
Template for pdf report instead of vizbox stuff discussion on 20.11.23 for perception.

**Comment by sunava** [comment]
idea: check box  for "check report for locations cause HRI was not specific enough"

**Comment by MatthijsBurgh** [comment]
I think you should focus on the desired robot behaviour, not its implementation.

**Comment by sunava** [comment]
We decided to move this to the next iteration of the rulebook
