### ISSUE TITLE
GPSR command generator provides nonsense

### ISSUE THREAD

**Issue by PetervDooren** [RoboCupAtHome/RuleBook#807]
Sometimes the GPSR command generator will provide commands which no sane human would ask of the robot. 
Should we keep command generator?
Or make something new which can randomly make the commands. We do want to keep the random aspect so referees and participants dont know whats coming. 

Issue outlined in TC meeting 31/07/2023

**Comment by YuqianJiang** [comment]
I think we can clean up the generator (or write a new one) so that it only generates reasonable high-level tasks (get an object, clean the table, greet the guest, etc.). This will significantly reduce the number of possible commands, but the operator can rephrase them to test natural language understanding. If the robot is not able to understand, the operator can still give the original command or QR code for partial points.

The scene should also be random to discourage state machines. We can make a random generator of object locations, or the referee can configure the arena however they want.

**Comment by moriarty** [comment]
It would be great if the referees could generate 3 commands and look at them at the start of the run.
