### ISSUE TITLE
DSPL: Collaborative Software Foundation for Efficient Development. 

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#811]
## Is your idea/suggestion related to a problem? Please describe.
The problem is redundant and thus inefficient development by the teams. Lack of collaboration results in missed opportunities to advance the field collectively. 

Not every team should develop the same features independently, leading to wastage of time and resources. You can only use the other teams’ modules when you share the same foundation. 

I don't know of any team that imports skills from other teams' code from the previous years. You always have to adjust the components to your platform, so it is just easier to develop a lot on your own. The teams develop concurrently without merging their progress.

## Describe the solution you'd like
We need common interfaces.

Enforce or at least encourage the use of the same software foundation. Reward when published code is used by other teams. We need to agree on a foundation and push it forward. That would really allow us to drive the field: One team wins in a task, is incentivized to publish their results, and the other teams can integrate that solution and focus on pushing other tasks forward instead of building the same features on their own.

**Comment by PetervDooren** [comment]
An important part here is incentivising teams to put effort in making their code usable by other teams. This is not just making everything open source but also managing dependencies of components, writing tutorials and keeping stable versions. 
Right now we have an award for best open source stuff. (or something to that effect) but this is apparently not enough encouragement.

I don't think common interfaces is the main problem in this regard. bridging interfaces is easy enough and ROS provides common interfaces for many things.

But I also believe this is not a problem that can be fixed with changes in the rulebook alone. At some point the community will have to take initiative.

**Comment by hawkina** [comment]
I get where you are coming from but if we enforce everyone to use the same things, it will discourage variety. Why bother testing out a new tool or package for e.g. planning if someone else already has an implementation of something?
It sort of happens naturally already. Almost every team is now using Yolov8 for perception and AMCL and the ROS Navigation stack, which is fine since these are really good tools and just work nicely. But enforcing this seems wrong to me. If nobody ever tries out something different or new, there won't be any progress either and we would get stuck in an optimization problem.

It also happens naturally that people exchange information after the competition and I've seen code being re-used across teams in DSPL already. Sure, one can encourage this further but I wouldn't enforce it via rules.
