### ISSUE TITLE
[Navigation] Rework navigation

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#83]
The navigation test is not working that well as it should.
The scenario want to use 2 doors, which are usually not available. Something can be improvised locally, but is not preferred. 

The doors are supposed to allow the TC to direct the robot towards obstacles. The test would be clearer and simpler if the task is more linear and instead the TC moves to obstacles to the robot's path.

What do we actually want to test:
- (3D) Obstacle avoidance
- Replanning if needed. The distinction between replanning and avoidance is that for avoidance, the robot can just go around the obstacle and have like a small detour. Replanning is taking a significantly longer path, maybe go back to a previous room and rach the target via a completely different path. 
- Bonus for dealing with movable obstacles. In this case, the robot need to go to a small table that is surrounded by movable objects, like rolling chairs, that block the path. The robot needs to be within grasping distance of the table and thus needs to move 1 of the chairs.

```
+-----------------------------+
|       +-+ |Tab| +-+         |
|       |M| +---+ |M|         |
|       +-+  +-+  +-+         |
|      <---+ |M| +--->        |
|            +-+              |
|                             |
|                             |
|      +------------+         |
|               |             |
|               |             |
|               |             |
|               |             |
|               |             |
|               |             |
+-----------------------------+
```

Where M are the movable objects around a Table. These can be chairs the robot has to push or humans that can be asked to move. The robot has to stand very close to the person when it asks to move.

The difficulty of writing this test is that we want to test intelligence but can only observe behavior.

**Comment by kyordhel** [comment]
*Task*
The proposed task is defined as follows:

- **Entering the arena:** The robot starts outside the environment and must wait until the door opens.

- **Waypoint 1 (door):** After entering the arena, the robot must navigate to *Waypoint 1*, which may be any location (room, placement location, furniture, beacon) and is reachable via several paths that include doors. One of the doors will be shut. The robot may:
  - To take a different path.
  - Open the closed door.

- **Waypoint 2 (obstructed path):** After reaching *Waypoint 1*, the robot must navigate and reach (to grasp distance) *Waypoint 2*, which is a placement location. However, *Waypoint 2* is surrounded by people or moveable furniture with which the robot must interact in order to reach its destination.

- **Waypoint 3 (following a human):** After entering the arena, the robot must navigate to *Waypoint 3*, which may be any location (room, placement location, furniture, beacon). Here is waiting a *Professional Walker* the robot must memorize and follow outside the arena.

- **Waypoint 4 (going back):** Upon reaching *Waypoint 4* the *Professional Walker* will command the robot to stop following him, using the instructions given by the robot. Then, the robot must navigate back to the starting point (*Waypoint 3*).

- **Leave the arena:** Robot must leave the arena through the indicated door.

**Obstacles:**
while navigating to *Waypoint 1* and *Waypoint 2* the robot will find each of the following obstacles:

- *Small object:* Box sized object < 1dm^3 (between 5 and 15 cm tall). 
- *3D Object:* A bar table, normal table, rolling chair: some object that is wider at its top than on its bottom, thus requiring more than just a laser scanner mounted near the ground to avoid obstacles.

**Comment by LoyVanBeek** [comment]
Great!

**Comment by kyordhel** [comment]
Also, the following needs to be stated
- Specify that there is no penalty for using the Continue Rule
- Specify exactly when the robot reaches a waypoint.
