### ISSUE TITLE
Simplify rules for manipulation & object recognition

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#87]
We stuff the shelf with all objects randomly placed over all shelves. There is a minimum distance so robots can actually grasp them. 
The robot outputs a report with a single image that gives an overview of the shelf with as much objects as possible labeled. 

There are also some unknown objects. They should be labeled as 'unknown' and not as anything else. Their label cannot be empty either.

**Comment by kyordhel** [comment]
I do not (completely) agree with that.

As a fully proficient myopic disordered rat, I often take a look at shelves to try to figure out where the object may be, and then I get closer and inspect part of the shelf to perform recognition.

For instance, firs I glance the rack and locate all my jam flasks. After that, I get closer and check every jam flask while looking for the raspberry one.

As for me, the following criteria is OK:

- A single image with an overview of the complete shelf with guesses (maybe bounding boxes with an ID and some lines / arrows indicating the grasping plan).
- A set of images of properly recognized object in the shelf or in the robot's manipulator (maybe referencing the ID).
- False positives are penalized

I don't mind if a robot needs to take an object to identify it, nor if it uses its nose instead of their eyes. Let's be explicit, not restrictive.

We may instead provide an example PDF of the recognition report.

**Comment by LoyVanBeek** [comment]
+1 on the take the thing first. 
Stuffing the whole shelf with object is mainly about giving the teams enough opportunity to do object recognition.
I don't care how they do it (as long as the robots do it). But the thing with different types of object on different heights is confusing. Just give a lot of randomly distributed objects and move a s much as you can in those 3 minutes.

**Comment by kyordhel** [comment]
My point while designing the test was:
- Force robots to manipulate at different heights
- Force robots to manipulate objects they don't know
- Force robots to manipulate heavy/hard-to-grasp objects

Therefore, the intended setup was:
- Known object in middle shelf
- Known object in low shelf
- Known object in high shelf
- Unknown/Alike object in middle shelf
- Tray/Bowl/Cloth/Heavy/Hard-to-grasp object in middle shelf

You are right on stating that the test is confusing, but I don't like giving more points to a team with a super-fast arm manipulating known light and small objects when you have a team that grasps the tray and the cloth only.

**Comment by LoyVanBeek** [comment]
Its hard to force robots (i.e. team) to do anything, we can at best give a high enough incentive. 

I want teams to have a super-fast arm manipulating the tray and a cloth. We don't have those in there right now but we could add those of course.

**Comment by kyordhel** [comment]
+1 to manipulating tray and cloth.
Incentive? Points!

We F need a meeting

**Comment by kyordhel** [comment]
What do you think about this, Loy? We populate the bookcase with known / alike / unknown / tray / cloth objects (as stated in issue #90) up to... lets say... 10 objects. The robot must properly identify 5 and manipulate those 5.

This way we are making robots to look among many objects and generate a plan for the ones they can grasp better, but with the prerrequisite that it must manipulate 3 known (top, botton, middle), 1 alike (middle) and 1 cloth/tray/bowl (middle).

A robot may also grasp an object before knowing which object is, but I'm not sure on how to deal with this right now.

**Comment by LoyVanBeek** [comment]
If there are 10 objects, the robot should attempt to classify all 10. Labeling as unknown is better than not labeling or labeling incorrectly. 

I think that the current robots are not able to pick/place 5 objects in 3 minutes. Humans are able to do this in 30 seconds, so we should push for this still. 

In the end, I want a report in which I can recognize the object to check whether the label is OK. If the robot is holding the object in the picture, fine.

**Comment by LoyVanBeek** [comment]
As in meeting: Do https://github.com/RoboCupAtHome/RuleBook/issues/87#issuecomment-97070145 but add random objects as well.

**Comment by LoyVanBeek** [comment]
Done, per #90
