### ISSUE TITLE
Remove additional Poster rewards

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#884]
## Describe the bug

There should be only one Poster Award instead of League specific.

**Comment by SparkRibeiro21** [comment]
Regarding Awards:
Shouldn't there be a 3rd place trophy for OPL when we had 17 teams competing? It seams weird that in other RoboCup leagues there are less teams and they give trophies to the three best teams and RoboCup@Home OPL with 17 teams has no 3rd place trophy.

**Comment by sunava** [comment]
Make a proposal to EC to see if we can get a third place :)

**Comment by johaq** [comment]
I believe the amount of trophies is strictly given according to Robocup guidelines. I can check for the official thresholds but I believe with SSPL spots going to OPL next year, we should have three trophies again for OPL.

**Comment by johaq** [comment]
![image](https://github.com/user-attachments/assets/bea42a2f-b0e4-4d4f-a016-52be16a98873)

Ok so this is the official Robocup policy. Please note that is not per league but for the entirety of @Home. So since we had 20+ teams across all leagues we had 5 awards (2 OPL, 2 DSPL, 1 SSPL). So next year IF we get to 20+ participants again it will be most likely 3 OPL and 2 DSPL. If not then 2 OPL and 2 DSPL.

**Comment by LeroyR** [comment]
We are able to reward two posters so we keep the two poster sessions.
