### ISSUE TITLE
Change or Remove Topic for Final

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#886]
## Additional context
We had food twice now. We could also just remove the topic. Anyone has an idea why/when the topic was introduced?

**Comment by LeroyR** [comment]
@johaq @myszzka96 @moriarty @mleonetti EC decision?

**Comment by MatthijsBurgh** [comment]
In favor or removing the forced topic for the final. Each university might be focusing on other stuff. Which does not always fit into one forced topic. Let teams show their best stuff. Which will make the finals more interesting. Teams talking too much instead of robots doing shit, should be penalized much more.

**Comment by ARTenshi** [comment]
We must rethink the final; teams can show their research in any other context (e.g. Poster presentation or RoboCup symposium), so we should restrict the final to an (open?) at-Home theme. Furthermore, I am more for a one-slide/one-minute presentation and the remaining time for the robot doing something (maybe with some comments from the team telling what's happening and how they have addressed that problem) -- they can use extra slides for the Q&A session.

**Comment by sunava** [comment]
Johannes: def get rid of the topic
