### ISSUE TITLE
Make robot state more visible /vizBox

### ISSUE THREAD

**Issue by hawkina** [RoboCupAtHome/RuleBook#889]
**Issue**
- currently the robot drives around a lot and the audience doesn't always know what is going on. It would be beneficial to visualize what is going on somehow.
- Connecting to the arena network is always an issue for this and depending on the robot can generate problems, hence why teams tend to not use the arena networks at all. 

**potential solutions**
- if there are screens available in the Arena's - like this year in Eindhoven - the robot could stream what it shows on it's display to the screen. - This comes mainly from the development in DSPL of visualizing instructions to the human users, showing what the robot has heared, etc. on the screen. 
- revival of vizBox?
- If network is such an issue, can we come up with another solution? e.g. video stream wirelessly via some other interface? (thinking of HDMI transmitters here or something)

**Comment by johaq** [comment]
I would of course be in favor of having visualizations of robot perception, the problem here is who has enough time to code the vizBox and what is the reward for teams using it?
In case of point rewards: Is it a flat bonus? In that case what if a team uses vizbox but the robot crashes immediately after entering? 
Is it a percent bonus? In that case it might be too many points in relation to effort.

**Comment by ARTenshi** [comment]
Hello,

adding to it, it's not very clear how it will help to the audience to understand what's going on unless we provide clear guidelines that are both simple and informative (which would require some experience in science communication to the general public).

**Comment by akinobu1998** [comment]
Personally, I think it is too hard for teams to prepare for visualization.
HDMI transmitter is easier to visualize (just transmit RVIZ) however, it uses 2.4/5GHz (same as Wi-Fi) so it is unstable in the competition or demonstration site in my experience.

I saw some teams do demonstrations (especially in stage II). It may be possible to ask them to visualize or explain their motion. Connecting the camera to the display may also help the audience to understand (usually, the robot's movement is hard to see because of the walls).

We can also consider the demonstration award for them (or if possible, teams who proceed to stage II can also contribute or even in stage I).

**Comment by johaq** [comment]
We could maybe start with something easy like:
1. Stream of the robot's main camera
2. Subtitles of what the robot is saying
I think this would already help understanding greatly and is not difficult to implement. Bandwidth/Connection is the bigger problem probably.

**Comment by MatthijsBurgh** [comment]
I am in favor of improving the experience for the audience. Though IMO the competition has the highest priority.

To have this working, there should be a very stable network connection. And a very well designed network setup, which should block communication between teams. But still allow communication from the robot to the arena screens, etc.
It should be reasonable to setup with different hardware setups of the organizing events.

This network setup should also be communicated to the teams quite some time in advance. I.E. Tech United has been running challenges without any network connection. Just plugging in a cable in between challenges to pull some code.

**Comment by johaq** [comment]
Yeah I think the problem here is. This is something we can only really decide on site whether it is possible due to the network. But at the same time it is something that needs to be announced well in advance for teams to prepare for. 

So the only possibility I see is requiring it and then still decide on site whether it is doable or not. This would of course be frustrating for teams if not possible after they put work into it...

Maybe another reason why we should only require something that is doable with very little effort.

**Comment by ARTenshi** [comment]
Again, the initial problem is "currently the robot drives around a lot and the audience doesn't always know what is going on", and I don't think that VizBox (or any other similar system) is the solution; we rather should focus on the design of the tasks to make them intuitive and easy to understand while challenging and challenging at the same time.

**Comment by akinobu1998** [comment]
In that point of view, the task explanation video this year is very helpful in understanding the task for the audience I think.

**Comment by sunava** [comment]
It is too difficult atm. wifi issue connecting issue etc. it would be nice to have but it not realizable
