### ISSUE TITLE
Reduce Time Limit for "Stickler for the Rules" Challenge

### ISSUE THREAD

**Issue by sunava** [RoboCupAtHome/RuleBook#895]
The time limit for the "Stickler for the Rules" challenge needs to be reduced. This adjustment might also be applicable to other challenges as well.

Task:

Reduce the time limit for the "Stickler for the Rules" challenge.
Consider applying similar time limit reductions to other challenges, if appropriate.

**Comment by johaq** [comment]
To elaborate. One of the goals of this test would be for robots to have integrated or on the fly perception. So instead of moving to viewpoint, look around, move to next viewpoint etc., the robot would drive around the arena and look for people while driving. This is difficult to enforce or encourage with points, so one solution might be to just reduce the time limit to encourage teams to develop quicker and integrated perception.

**Comment by ARTenshi** [comment]
Or we can complete redesign the story of this test that no one likes as it is. Let's come with some ideas next meeting about this (that would be easier to discuss in person than in an issue).

**Comment by PetervDooren** [comment]
Enforcing people to make integrated perception will be difficult. 
One potential solution I can see is to make the scenario more dynamic. Have guests walk around, even between rooms. This way a static approach to perception is a lot less reliable.

If you want to reskin this challenge as something people will like better. Consider the cocktail party challenge from a couple of years ago.

**Comment by sunava** [comment]
We gonna remove it anyway
