### ISSUE TITLE
Rethink the finals

### ISSUE THREAD

**Issue by sunava** [RoboCupAtHome/RuleBook#899]
**Action:** 

Decide Challenge [TC Meeting] -> Implement Rulebook Change
Discussion: Let it open? Have certain task? How is the “presentation” of the human vs robot ruled out? Research of different areas should be scored. 
**Idea:** @hawkina  make it something like gpsr and task are more fixed

Shall we have different scenarios/task:
- Transform
- HRI
-

**Comment by sunava** [comment]
Johannes idea: Do it open -> u can choose from a list of tasks -> teaks: " we can show these 3 task in the 5 minutes frame" etc.. or "we can show this 1 task in the frame" ...

**Comment by PetervDooren** [comment]
I would keep the open character of the finals. Otherwise a lot of teams may not have a challenge where they can showcase their unique strengths. 
I dont mind the human presentation aspect. (although a lot of people lack showmanship) We had commentary last tournament and this is essentially the same but from the people who made the robot.

**Comment by johaq** [comment]
So I will try to outline my idea better.
I see the following problems with the current finals: 
- Most teams prepare the finals the night before leading to mediocre performance. In Eindhoven I think I saw 1-2 finals where I thought this went how the team wanted it to go.
- Teams can potentially show completely different things making comparison difficult and Jury scoring intransparent.
- Ideally the finals gives us ideas on what to add to Rulebook. This is difficult with an open demonstration since they might not really fit into any of the existing tests.

My idea roughly:
We have finals teams A and B. Each team can chose one of the Stage 1 or 2 tests. Then both teams prepare a presentation of both tests where they are expected to add something extra to the test.
Example: Team A chooses Storing Groceries, Team B chooses Carry my Luggage. To start Team performs Storing Groceries where they show that they can grasp objects that are very flat. Then Team B performs Storing Groceries but they did not come up with anything extra. Then Team A performs Carry my Luggage also without something extra. Then Team B performs Carry my Luggage and they show they can still follow a person from 15m away. The scores then is the score of both tests plus a jury score for the extra performance (could also be just the jury score, not sure). Of course both teams are free to also present something extra for the test they did not choose.

Benefits:
- Reduce preparation time since a finals team should have every test prepared. But we still have the creative part of coming up with something extra for the test the other teams chose
- Since you only need to prepare something extra for one test hopefully teams come prepared with something to robocup already
- Potentially very easy path to add new things to the Rulebook. I.e. add something a finals team showed as a bonus goal for next year. If enough teams score the bonus add it to the regular test.

Potential problems:
- Teams might choose a test not based on how well they do in it but based on how badly the other team performs in it. This might be solved by weighing the extra performance in your chosen test more heavily so you are incentivized to chose the test you perform the best in
- Maybe too restrictive
- This would mean we cannot allow a third team in the finals in close cases. Maybe we add a third place match instead.

**Comment by ARTenshi** [comment]
In my opinion, teams have shown their skills during the previous days, so we can propose a simple but meaningful task for the final for the teams to show the state of the art on service robots, for example, Clean Up where we scatter 30+ objects around the house and both robots (at the same time) take them to their correct locations, and the score in this task sums to the current total.

This task should serve as a reference for the performance of the best robots and might attract the audience -- i.e. through a simple and easy-to-understand challenge, we use the best teams to show off what the league has to offer.

This is one example of a task, but it can be any -- regarding a task focused on one skill, I can read you now arguing that it might be unfair for teams that can't perform well on it, but it is rare that the finalists get points only in one skill but rather they score in most tasks.

Luis
